Gnucash/gnucash

src/report/standard-reports/account-piecharts.scm

These patches refactor the piechart reports to make the code easier to read.  Of course, this is a subjective judgement - but I think that the changes make it cleaner.

Refactor piechart code to make it clearer

---

src/report/standard-reports/account-piecharts.scm

These patches (based off https://github.com/Gnucash/gnucash/pull/32) implement a new type of pie chart (similar to the assets piechart) that groups not by the account hierarchy but by security/currency.
See http://lists.gnucash.org/pipermail/gnucash-user/2015-August/061783.html.

Add piechart grouped by security/currency.

---

src/import-export/csv-exp/Makefile.am

Building on master on Windows fails for me with the error below. The missing symbols are in the gnu-gnome library, so cvs-exp needs to link to it. Adding one line in cvs-exp/Makefile.am to do this link fixes the problem for me.
Error:
libtool: link: rm -fr  .libs/libgncmod-csv-export.dll.a
libtool: link: gcc -std=gnu99 -shared  .libs/gncmod-csv-export.o .libs/gnc-plugin-csv-export.o .libs/assistant-csv-export.o .libs/csv-tree-export.o .libs/csv-transactions-export.o  -Wl,--whole-archive ../../../lib/stf/.libs/libgnc-stf.a ../../../lib/libc/.libs/libc-missing.a -Wl,--no-whole-archive  -L/c/gcdev/gnucash/build/src/gnome-utils/.libs -L/c/gcdev/gnucash/build/src/backend/xml/.libs -L/c/gcdev/gnucash/build/src/app-utils/.libs -L/c/gcdev/gnucash/build/src/engine/.libs …

link gnc-gnome into gncmod-csv-exp

---

CMakeLists.txt

This should fix the nightly build of master on Windows.

CMake: Don't try to install COPYING file that does not exist.

---

CMakeLists.txt

Needs PR 9 from gnucash-on-windows also.

Allow HTMLHELP_DIR to be specified on cmake command line

---

src/engine/test/Makefile.am
src/report/business-reports/Makefile.am
src/report/locale-specific/us/Makefile.am
src/report/report-system/Makefile.am
src/report/standard-reports/Makefile.am
src/report/stylesheets/Makefile.am
src/report/utility-reports/Makefile.am

This version of guile needs some extra paths added to GUILE_COMPILE_ENV and GNC_TEST_DEPS.
Tested with the following configure options, on Gentoo ~amd64:
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/gnucash-2.6.13-r1 --htmldir=/usr/share/doc/gnucash-2.6.13-r1/html --libdir=/usr/lib64 --disable-schemas-compile --enable-compile-warnings=minimum --disable-debug --disable-password-storage --enable-ofx --disable-aqbanking --enable-python --with-guile=2.0 --disable-doxygen --disable-gtkmm --enable-locale-specific-tax --disable-error-on-warning --enable-dbi

fix compilation with guile-2.0.12

---

src/doc/xml/gnucash-v2.rnc

"price" is a legal value, as per code in [1]. Added value to RELAX NG
file to pass validation of modern gnucash files.
[1] https://github.com/Gnucash/gnucash/blob/51e29e7836af814868f51161cb3263465a5e951f/src/backend/xml/io-gncxml-v2.c#L1037
51e29e7836af814868f51161cb3263465a5e951f = current HEAD of branch maint

Value "price" allowed in attr cd:type for element book (RELAX NG file)

---

src/cmake_modules/GncFindPkgConfig.cmake

For CMake versions 3.1 through 3.4 inclusive, we need to use a custom version of FindPkgConfig.cmake to work around a bug introduced in CMake 3.1. The bug is fixed in CMake 3.5. For versions less than 3.1 or greater than 3.4, use CMake's versions of FIndPkgConfig.cmake.

Use default PKG_CHECK_MODULES for CMake version > 3.4

---

src/app-utils/app-utils.i

to allow to retrieve the path of a book from a report in guile via (qof-session-get-url (gnc-get-current-session))

add gnc_get_current_session to swig interface

---

po/en_GB.po

For the last few months, I've had a minor frustration over the fact the menu items in my en-GB variant of Gnucash's "Actions" > "Budget" are:
- New Budget
- Open budget
- Copy Budget
So this pull request makes all instances of 'Budget' capitalised.

Consistently capitalise budget in en-GB menu items

---

src/register/ledger-core/split-register-model-save.c

Currently Gnucash crashed when you try to save scheduled transactions. This fixes the issue.

Fix crash while saving scheduled transaction template

---

CMakeLists.txt

Cherry picked 992f3232 from master; fixed conflicts. 
This fixes the cmake compile for maint on Fedora 25.

Adjust CMAKE_C_FLAGS for better release/debug behavior.

---

src/bin/Makefile.am
src/engine/test/test-date.cpp
src/engine/test/utest-gnc-pricedb.c
src/gnome-utils/Makefile.am
src/import-export/csv-imp/assistant-csv-trans-import.cpp
src/import-export/csv-imp/gnc-csv-trans-settings.cpp
src/import-export/csv-imp/gnc-csv-trans-settings.hpp
src/import-export/csv-imp/gnc-tx-import.cpp
src/import-export/csv-imp/gnc-tx-import.hpp
src/libqof/qof/gnc-date.cpp
src/libqof/qof/gnc-datetime.cpp
src/libqof/qof/gnc-datetime.hpp
src/libqof/qof/test/CMakeLists.txt
src/libqof/qof/test/Makefile.am
src/libqof/qof/test/gtest-gnc-datetime.cpp
src/libqof/qof/test/test-gnc-date.c

Primary use case is for parsing dates from external sources (importers).
Current implementation causes the test to abort in a segfault. I don't see any reason for that unfortunately. It seems to happen in boost:regex' memory housekeeping at the end of the test run. Running under gdb results in the following bt:
```
Program received signal SIGSEGV, Segmentation fault.
malloc_consolidate (av=av@entry=0x7ffff5b4bae0 <main_arena>) at malloc.c:4204
4204              nextsize = chunksize(nextchunk);
Missing separate debuginfos, use: dnf debuginfo-install gtest-1.7.0-8.fc25.x86_64
(gdb) bt
#0  0x00007ffff580bfbb in malloc_consolidate (av=av@entry=0x7ffff5b4bae0 <main_arena>) at malloc.c:4204
#1  0x00007ffff580db20 in _int_free (av=0x7ffff5b4bae0 <main_arena>, p=0x6f25a0, have_lock=0) at …
```

Add constructor to create GncDate from string and predefined date format

---

src/report/report-system/html-acct-table.scm

Bug 776396 - Foreign currency reports, amounts are not aligned correctly
This commit will improve the styling of the table element used
for foreign currencies in the Balance sheet report so they
end up aligned with the other currencies.
Follow up on feedback on:
- https://github.com/Gnucash/gnucash/pull/147
- https://bugzilla.gnome.org/show_bug.cgi?id=776396

Bug 776396 - Foreign currency reports, amounts are not aligned correctly

---

src/report/report-system/html-acct-table.scm

This commit will further improve the styling of the table element used for foreign 
currencies in reports with stocks or foreign currencies. Adds non-breaking space 
between foreign currency/stock and report currency.

Bug 776396 Further Fix

---

src/import-export/test/Makefile.am

libgncmod-test-engine.la uses some functions defined in libtest-core.la, so libtest-core.la should be put after libgncmod-test-engine.la

Fix import-export compile on windows

---

src/report/report-system/html-fonts.scm

Add vertical-align top.
Previously, text fields would have vertical-align:default = centre. This means long transaction descriptions would cause all other fields to be vertically centred. This amendment will ensure the transactional report text are aligned from the top.
Cosmetic change only.

Add vertical-align:top to default text fields.

---

gnucash/gnome-utils/dialog-account.c
gnucash/gnome-utils/dialog-utils.c
gnucash/gnome-utils/dialog-utils.h
gnucash/gnome-utils/gnc-cell-renderer-popup-entry.c
gnucash/gnome-utils/gnc-combott.c
gnucash/gnome-utils/gnc-date-edit.c
gnucash/gnome-utils/gnc-dense-cal.c
gnucash/gnome-utils/gnc-dense-cal.h
gnucash/gnome-utils/gnc-gnome-utils.c
gnucash/gnome-utils/gnc-gtk-utils.c
gnucash/gnome-utils/gnc-gtk-utils.h
gnucash/gnome-utils/gnc-tree-model-account.c
gnucash/gnome-utils/gnc-tree-view-split-reg.c
gnucash/gnome-utils/gnc-tree-view.c
gnucash/gnome-utils/ui/CMakeLists.txt
gnucash/gnome-utils/ui/Makefile.am
gnucash/gnome-utils/ui/gnucash-fallback.css
gnucash/gnome-utils/ui/gnucash.css
gnucash/gnome-utils/window-main-summarybar.c
gnucash/import-export/dialog-import.glade
gnucash/import-export/import-main-matcher.c
gnucash/register/register-gnome/gnucash-item-edit.c
gnucash/register/register-gnome/gnucash-item-edit.h
gnucash/register/register-gnome/gnucash-sheet.c

Highlights...
Add a fall back css file that has a lower priority than themes.
Change the way the dense calendar is drawn, now theme-able and can look more like the default calendar, below is some css that hopefully should give you an idea, the only thing I was not sure about was the default names...
Changed the up/down arrow to be drawn based on theme which brings it more inline with the rest of the look.
Bob
calendar {
color:yellow;
background-color: lightgrey;
}
calendar.header {
background-color: lightgreen;
}
calendar.highlight { color: red;
background-color: pink;
}
calendar:indeterminate { color: alpha(currentColor,0.2); }
calendar:selected { 
color: white;
background-color: grey;
border-radius: 10px;
}
.calendar {
border-color: white;
}
.calendar.header {
background-color: …

Gtk3 update5

---

.travis.yml

This PR has the Travis build system do CMake builds (Makefile and Ninja) in addition to the autotools build.
We did not need a PPA for cmake, as Trusty provides a cmake3 package. 
Also, I did not move the script part to a separate file, as I figured out that using 'set -e' will allow us to put one command per line in the 'script:' section and have a failing line fail the whole build.

Enable CMake build in Travis CI

---

libgnucash/engine/Account.c

The reconcile account dialog always displays a value of 0.00 as the
Ending Balance, regardless of account and statement date.
This is caused by function xaccAccountGetReconcilePostponeBalance
returning the wrong value, returning TRUE when it should return FALSE,
and setting balance to the default {0,1}.
The code uses bal.denom!=0 as an indicator that a valid balance was
received in variable v. However, bal is initialized to {0,1}
making the test always true even when we didn't receive a valid
value in variable v.
Thus, this function returns TRUE with *balance={0,1} when no valid
balance was found in "reconcile-info/postpone/balance".
This patch fixes the function to return FALSE if v doesn't hold
a valid value or if bal.denom is set to 0.

fix reconcile dialog always showing ending balance of zero

---

gnucash/report/report-system/html-barchart.scm
gnucash/report/report-system/html-linechart.scm
gnucash/report/report-system/html-piechart.scm

Many of the standard reports specify colors to use in their charts. However, these colors are ignored in the chart rendering code.
These commits modify the rendering code of all 3 types of charts (bar, pie and line) to fix this issue. This is done by adding the jqplot option "seriesColors"  to pass the requested bar/pie/line colors to jqplot. If no colors are requested, we let jqplot use default colors by setting "seriesColors: false".

Fix report colors

---

gnucash/report/report-system/html-barchart.scm

Bar colors specified by a report only apply to positive bars in the plot. Negative bars still have the default colors, which are slightly darker shades of the default positive colors.
This commit forces negative bars to have the same colors as positive bars.

report: fix negative colors in barcharts

---

gnucash/gnucash-310.css
gnucash/gnucash-320.css
gnucash/register/ledger-core/gncEntryLedgerModel.c
gnucash/register/ledger-core/split-register-model.c
gnucash/register/register-core/table-allgui.c
gnucash/register/register-core/table-allgui.h
gnucash/register/register-core/table-model.c
gnucash/register/register-core/table-model.h
gnucash/register/register-gnome/gnucash-header.c
gnucash/register/register-gnome/gnucash-item-edit.c
gnucash/register/register-gnome/gnucash-item-edit.h
gnucash/register/register-gnome/gnucash-sheet-private.c
gnucash/register/register-gnome/gnucash-sheet.c
gnucash/register/register-gnome/gnucash-sheet.h
gnucash/register/register-gnome/gnucash-style.c

The first lot of commits get the cell margin, border and padding from the CSS values. Previously the border would take up 1px when not specified and the padding default was 2px. This is still the case but with margin so there should be 3px top and bottom which should be enough space for the double line so I have moved it back up and does not interfere with the cell. Also the cell alignment is now a common set of functions which fixes a header alignment issue. I have cast a new toggle button so that the button width can be controlled which leads in to commit 'Change the look...', with these changes the button is removed and replaced with the arrow and possible frame, this could be adjusted if it was a way to go. The latter commits were the code reduction for the cell colours.
Bob
To test …

Item edit cell padding and code reduction of cell colours

---

gnucash/gnome-utils/gnc-dense-cal.c
gnucash/gnome-utils/gnc-dense-cal.h

This PR fixes Gnucash crashing when in Windows you click on a date that does not have any scheduled transactions marked. It seems to stem from the treeview being empty and not being displayed so if there are no entries I add a blank. There are also a couple of changes to help improve when the popup is displayed.
Bob

Fix dense calendar on Windows

---

src/core-utils/gnc-features.c
src/core-utils/gnc-features.h
src/import-export/import-match-map.c
src/import-export/test/CMakeLists.txt
src/import-export/test/test-flat-bayes.c
src/libqof/qof/kvp_frame.c
src/libqof/qof/kvp_frame.h

With 2.8 soon able to write guid and flat bayes kvps, 2.6 will also need
to be able to read them. Due to the nature of the change, though, 2.6
will also be able to write guid and flat bayes kvps. 2.8 is able to read
2.6-type bayes kvps, and will convert them to a guid/flat model. With this
commit, 2.6 can read and write in this model, but is not able to convert
a database between the two.

GUID/Flat bayes handling in 2.6

---

gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome/dialog-invoice.c
gnucash/gnome/dialog-invoice.h
gnucash/gnome/gnc-budget-view.c
gnucash/gnome/gnc-budget-view.h
gnucash/gnome/gnc-plugin-account-tree.c
gnucash/gnome/gnc-plugin-budget.c
gnucash/gnome/gnc-plugin-business.c
gnucash/gnome/gnc-plugin-page-account-tree.c
gnucash/gnome/gnc-plugin-page-account-tree.h
gnucash/gnome/gnc-plugin-page-budget.c
gnucash/gnome/gnc-plugin-page-budget.h
gnucash/gnome/gnc-plugin-page-invoice.c
gnucash/gnome/gnc-plugin-page-owner-tree.c
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-plugin-page-register.h
gnucash/gnome/gnc-plugin-page-sx-list.c
gnucash/gnome/gnc-plugin-register.c
gnucash/gnome/gnc-split-reg.c
gnucash/gnome/gnc-split-reg.h
gnucash/html/gnc-html-webkit2.c
gnucash/register/register-gnome/gnucash-register.c
gnucash/register/register-gnome/gnucash-sheet.c
gnucash/register/register-gnome/gnucash-sheet.h
gnucash/report/report-gnome/gnc-plugin-page-report.c

The main focus of these changes make the notebook page contents the primary focus so that you can use the keyboard straight away. Also stepping through the pages with ctrl+alt+pg_up/pg_down works consistently.
All seems to work as expected.
Bob

Make the notebook pages the primary focus

---

gnucash/report/standard-reports/transaction.scm

Bugfix infobox display when no accounts were matched. Good catch @gjanssens

ENH: display infobox when no accounts matched

---

po/de.po

I correct some typos in the text for importing as CSV.
there is also a button untranslated. I can't find why. the Text is "_New Account" I chck this with an aktual *.po -> *.mo file.

correct typo

---

gnucash/report/standard-reports/category-barchart.scm

If accounts / show level < minimum-level of accounts
Previously the report would crash
This commit now displays an empty report.

bugfix: fix report crash if acc-depth too low

---

src/report/report-system/report-collectors.scm

This bugfix affects net-linechart and net-barchart - assumes the min-date for dates must be 0. Net worth bar & line charts with dates earlier than 01-01-1970 were incorrect. I'll fix in time64-ftw as well.

bugfix incorrect min-date handling

---

gnucash/report/standard-reports/transaction.scm

This fix was needed due to crossed-wires whereby time64 merge didn't take a previous fix into account. This is needed for common-currency to work.

TP->T64: gnucash/report/standard-reports/transaction.scm

---

gnucash/gnome/gschemas/org.gnucash.gschema.xml.in.in
gnucash/register/register-gnome/gnucash-register.c

Correct two times 'horzontal' to 'horizontal' in the source code

correct typo in horizontal

---

gnucash/report/business-reports/easy-invoice.scm
gnucash/report/business-reports/fancy-invoice.scm
gnucash/report/business-reports/invoice.scm
gnucash/report/business-reports/job-report.scm
gnucash/report/business-reports/owner-report.scm
gnucash/report/business-reports/taxinvoice.eguile.scm
libgnucash/engine/gncInvoice.c
libgnucash/engine/gncInvoice.h

This commit fixes business reports caused by 91f4b190394df6
whereby the posted-date for unposted invoice was changed
from 0 to MAXINT. Now we need to use (gncInvoiceIsPosted)
or (gncInvoiceDateExists) instead.

BUGFIX: invoice posted-date is no longer 0 for unposted invoices

---

gnucash/report/report-system/commodity-utilities.scm

I think this patches correctly for now.
Addendum to e0300d3 - was crashing reports.
And 45f61a3 had couple bugs.
value/share swapped
no need to define comm-list in create-commodity-list

BUGFIX: numeric->number in commodity-utilities.scm 

---

src/report/report-system/report-collectors.scm
src/report/standard-reports/test/test-generic-category-report.scm

This is caused by commit 766e74096 - min-date was
erroneously thought to mean 'min date of date-list'
but actually meant 'negative infinity date'. This
commit changes date comparison logic to always
return #t when comparing
(gnc:timepair-le min-date date) for
the first date interval.
Test case also created. The test is derived from the
equivalent test in unstable.
I believe this fixes maint. I think merging onto unstable
will lead to conflicts, both to report-collectors.scm
and to the unit test. When resolving the conflict,
unstable must take priority.
This is the maint equivalent to #276

bug 793278 fix for maint

---

src/report/report-system/commodity-utilities.scm

45f61a3 had couple bugs.
- value/share was inadvertently swapped
- no need to define comm-list in create-commodity-list to return it

BUGFIX: create-commodity-list in commodity-utilities.scm

---

gnucash/report/standard-reports/income-gst-statement.scm
gnucash/report/standard-reports/transaction.scm
libgnucash/app-utils/app-utils.scm
libgnucash/app-utils/options.scm

This PR includes several (I believe are well-designed) commits:
1. xaccSplitGetReconcile to identify reconciled txns instead of (reconciled-date == 0)
2. (infobox)->(gnc:render-options-changed options) is more generalized, reduces strings.
3. TR: omit display $0 - I managed to eliminate these extra monetary subtotals.
4. Merge TR-no-account and TR-no-accounts-after-filtering, reduces strings
5. income-gst-statement.scm reworked into a transaction.scm derivative.
6. Add 2 helper funcs in options.scm to support 5 above.

Scheme progress

---

gnucash/register/ledger-core/split-register-control.c
gnucash/register/ledger-core/split-register-model.c
gnucash/register/ledger-core/split-register.c
gnucash/register/ledger-core/split-register.h
libgnucash/app-utils/gnc-ui-util.c
libgnucash/app-utils/gnc-ui-util.h

Two preferences were being used heavily in the drawing of the register especially when it is obscured so it makes sense for them to be saved in the split_register structure so they can be easily be referenced.

Cache a couple of split register preferences

---

CMakeLists.txt
gnucash/report/report-system/html-document.scm
gnucash/report/standard-reports/test/CMakeLists.txt
gnucash/report/standard-reports/transaction.scm
libgnucash/app-utils/options.scm

A few commits, mainly to prepare for srfi-64 and sxpath-based tests which will need well-formed XML renders.
1. Change html break tag from `<br>` to `<br />`
2. Opening `<html>` tag was mistakenly deleted two years ago.
3. Test for SRFI-64 and enable testing group. This group will be run on systems containing guile-2.0.10 onwards, such as travis-ci arch.
And a minor amendment to TR according to guile guide.
After this, TR-unittest #270 can progress.

Unstable prepare srfi64

---

gnucash/register/ledger-core/split-register.c

This way is a safer way to update the cache values in case the settings
changed signal fails to trigger or there is a double trigger and the
cached value gets out of sync with the preference value.

Use the gnc_prefs_get_bool values to update split-register cache values

---

gnucash/register/register-gnome/gnucash-item-edit.c

When the register is obscured by another window, the sheet would get
lot of draw events. This was tracked down to getting the foreground
colour for the item-edit widget for the state GTK_STATE_FLAG_NORMAL.
Changed this to use the value obtained from gtk_widget_get_state_flags.

With register obscured the sheet kept being redrawn

---

gnucash/gtkbuilder/assistant-hierarchy.glade

There is no spacing between the text and the frame in the dialog "New File" > "New Accounts Hierarchy Setup". In some cases - when changing the window size - the text appears next to the frame. It does not look very clean. As a solution, I have defined here a small spacing: 5px.
Example 1:
Example 2:

Add spacing between border and text in "New Accounts Hierarchy Setup"

---

accounts/ru/acctchrt_auto.gnucash-xea
accounts/ru/acctchrt_autoloan.gnucash-xea
accounts/ru/acctchrt_common.gnucash-xea
accounts/ru/acctchrt_homeloan.gnucash-xea
accounts/ru/acctchrt_homeown.gnucash-xea
accounts/ru/acctchrt_kids.gnucash-xea
accounts/ru/acctchrt_otherloan.gnucash-xea
accounts/ru/acctchrt_renter.gnucash-xea

Remove the emacs comments at the end of files:
`<! -- Local variables: -->`
`<! -- mode: xml        -->`
`<! -- End:             -->`
This comments are to help emacs recognize that the files are xml
since they don't have 'xml' as an extension (see PR #300).

Remove the emacs comments at the end of files

---

accounts/de_DE/acctchrt_auto.gnucash-xea
accounts/de_DE/acctchrt_autoloan.gnucash-xea
accounts/de_DE/acctchrt_brokerage.gnucash-xea
accounts/de_DE/acctchrt_common.gnucash-xea
accounts/de_DE/acctchrt_full.gnucash-xea
accounts/de_DE/acctchrt_houseown.gnucash-xea
accounts/de_DE/acctchrt_investment.gnucash-xea
accounts/de_DE/acctchrt_kids.gnucash-xea
accounts/de_DE/acctchrt_otherasset.gnucash-xea
accounts/de_DE/acctchrt_otherloan.gnucash-xea
accounts/de_DE/acctchrt_skr03.gnucash-xea
accounts/de_DE/acctchrt_skr04.gnucash-xea
accounts/de_DE/acctchrt_skr49.gnucash-xea
accounts/de_DE/acctchrt_studium.gnucash-xea
accounts/de_DE/acctchrt_wohnungsw.gnucash-xea

Clean Up for Account Hierarchy Templates: "de_DE" (german):
* Add XML namespaces
The parser in GC 2.6 makes no use of it, but future versions might change.
Defining the namespace has the benefit, you can check the syntax of template files with `xmllint`:
`for i in *-xea; do xmllint --noout $i; done`
* Remove emacs-comments at the end of files:
`<! -- Local variables: -->`
`<! -- mode: xml -->`
`<! -- End: -->`
* Add `<gnc-act:exclude-from-select-all>1</gnc-act:exclude-from-select-all>` for `acctchrt_full.gnucash-xea`
This template should not be selected if the user clicks the button "Select All",
because it consists of all other non-business templates, which would be selected with "Select All".
BTW: This template is currently not active.
If these changes are not ok, please just cancel …

 Clean Up for Account Hierarchy Templates: "de_DE" (german)

---

accounts/C/acctchrt_brokerage.gnucash-xea
accounts/C/acctchrt_business.gnucash-xea
accounts/C/acctchrt_carloan.gnucash-xea
accounts/C/acctchrt_cdmoneymkt.gnucash-xea
accounts/C/acctchrt_checkbook.gnucash-xea
accounts/C/acctchrt_childcare.gnucash-xea
accounts/C/acctchrt_common.gnucash-xea
accounts/C/acctchrt_eduloan.gnucash-xea
accounts/C/acctchrt_fixedassets.gnucash-xea
accounts/C/acctchrt_full.gnucash-xea
accounts/C/acctchrt_homeloan.gnucash-xea
accounts/C/acctchrt_homeown.gnucash-xea
accounts/C/acctchrt_otherloan.gnucash-xea
accounts/C/acctchrt_renter.gnucash-xea
accounts/C/acctchrt_retiremt.gnucash-xea
accounts/C/acctchrt_spouseinc.gnucash-xea
accounts/C/acctchrt_spouseretire.gnucash-xea

Clean Up for Account Hierarchy Template: "C" (english):
* Add XML namespaces
The parser in GC 2.6 makes no use of it, but future versions might change.
Defining the namespace has the benefit, you can check the syntax of template files with `xmllint`:
`for i in *-xea; do xmllint --noout $i; done`
* Remove emacs-comments at the end of files:
`<! -- Local variables: -->`
`<! -- mode: xml -->`
`<! -- End: -->`
* Add `<gnc-act:exclude-from-select-all>1</gnc-act:exclude-from-select-all>` for `acctchrt_full.gnucash-xea`
This template should not be selected if the user clicks the button "Select All",
because it consists of all other non-business templates, which would be selected with "Select All".
BTW: This template is currently not active.
If these changes are not ok, please just cancel this …

Clean Up for Account Hierarchy Templates: "C" (english)

---

gnucash/gnome/gnc-plugin-account-tree.c
gnucash/gnome/gnc-plugin-budget.c
gnucash/gnome/gnc-plugin-page-account-tree.c
gnucash/gnome/gnc-plugin-page-budget.c
gnucash/gnome/gnc-plugin-page-invoice.c
gnucash/gnome/gnc-plugin-page-owner-tree.c
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-plugin-page-sx-list.c
gnucash/gnome/gnc-plugin-register.c
gnucash/report/report-gnome/gnc-plugin-page-report.c

When selecting the File->New with existing register pages open a crash
can happen as the register pages get closed forcing a page-changed
signal to queue the page focus function when there is no page. Add a
call to remove the page focus function in the ..destroy_widget function.
Also with the addition of g_idle_remove before the add when page-changed
is emitted the page focus function only gets run once.

Fix Segmentation fault when going to File->New

---

gnucash/gnome-utils/gnc-tree-view-split-reg.c
gnucash/gnome/assistant-hierarchy.c

Bug 793699, I could not get it to fail but have refactored so the start_spath is defined in the while loop and freed also in the while loop so should fix the issue.
Bug 794031, this looks like it has not worked for a very long time but I can see no reason for it not to work so have enabled the cell render toggle for the placeholder column and provided a call back. Looks OK with my testing but maybe I have missed something, the other way to clear this bug is to delete the surplus text.
Bob

Fixes for a couple of bugs 

---

CMakeLists.txt
gnucash/gschemas/CMakeLists.txt

Adding the COMPILE_SCHEMA option allows a choice to compile the gschema or not, defaulting to 'ON'. This is useful for distributions that choose to not compile the gschema when producing packages for some good reasons.

Add COMPILE_SCHEMA to allow disabling gschema compilation

---

bindings/python/gnucash_core.py

Using the function gnc_price_create and book as a parameter, it is possible to create the new GncPrice object. This will remove the necessity of cloning the prices from existing ones in Python scripts.

Allow creation of prices in Python bindings

---

gnucash/gnome/dialog-price-edit-db.c
gnucash/gnome/gnc-plugin-page-account-tree.c
gnucash/gnome/gnc-split-reg.c
gnucash/gtkbuilder/dialog-account.glade
gnucash/register/ledger-core/gnc-ledger-display.c
gnucash/register/ledger-core/split-register-model.c
libgnucash/app-utils/gnc-component-manager.c

Test for valid widgets before trying to get there sensitivity. Also if the register was open when the account is deleted an invalid component_id error is logged so check for it being valid before using.

Bug794360 error when deleting accounts with subaccounts

---

gnucash/register/register-gnome/gnucash-sheet.c

When double clicking on header to autosize columns need to add the
padding_border values to get correct width.

Bug794806 - Autosize too small

---

gnucash/report/business-reports/easy-invoice.scm
gnucash/report/business-reports/invoice.scm
gnucash/report/standard-reports/advanced-portfolio.scm
gnucash/report/standard-reports/transaction.scm

This fixes a div/0 error identified in bug 792800. It is thought to be related to negative-stock-balance situation rather than high-precision security error. From #321.

Bug 792800 - Advanced Portfolio Report tries to divide by zero balance and aborts

---

gnucash/report/business-reports/job-report.scm
gnucash/report/business-reports/owner-report.scm
gnucash/report/business-reports/taxinvoice.eguile.scm
libgnucash/engine/gncInvoice.c
libgnucash/engine/gncInvoice.h

This commit replaces gncInvoiceDateExists calls to gncInvoiceIsPosted. I think it's a reasonable assumption that all posted invoices will have posted-date.

Eradicate gncInvoiceDateExists

---

borrowed/gwengui-gtk3/w_combobox.c
borrowed/gwengui-gtk3/w_groupbox.c
borrowed/gwengui-gtk3/w_lineedit.c
borrowed/gwengui-gtk3/w_textbrowser.c
gnucash/import-export/aqb/gnc-ab-utils.c
gnucash/import-export/aqb/gnc-file-aqb-import.c

The first and fourth commits were errors migrating from the gtk2 Gui to the gtk3 version.
The second and third errors I observed while trying to fix the first one which I think are correct.
The last commit fixes a couple of transient parent warnings when doing a MT940 file import.
I do not use the Aqbanking stuff but was able to create a user and account via the wizard, a strange thing when setting the currency for a account is that there are two 'Pound Sterling' options but was unable to set it to either, maybe because it was the default currency, others worked OK.
If the first four fixes are accepted then the gwenywdar library would need to patched on Windows along with the Aqbanking compile fix.
Bob

Various gwenywfar fixes

---

gnucash/report/report-system/html-fonts.scm
gnucash/report/standard-reports/income-gst-statement.scm
gnucash/report/standard-reports/transaction.scm

The main fix here is an exception catcher for invalid-regex for account/transaction matcher. There are also a few other IMHO harmless refinements. Please cherry-pick if this is preferred.

TR: catch invalid regex instead of report crashing.

---

gnucash/report/standard-reports/transaction.scm

This will allow 'show subtotals only' if sortkeys are date-types. This allows, for example, prime-sortkey=date, yearly. sec-sortkey=date, monthly.
This can still produce invalid combinations eg both sortkeys = date and subtotals = none means this option is invalid. But I figure the user will need to make some effort to produce this combination.

Bug 795064 - Enable subtotal-only if sortkeys are dates

---

src/import-export/ofx/gnc-ofx-import.c

NOTE: I'm the maintainer of the FreeBSD port here:
http://www.freshports.org/finance/gnucash
And I'm going to update the port including this modification. I'd like to upstream it or have suggestions for a better fix.
Thanks in advance.

FreeBSD does not have the daylight global. so I just check tm_is_dst

---

gnucash/report/locale-specific/us/taxtxf.scm

Missed out from timepair->time64 conversion.

Bug 796081 Tax Schedule Report - An error occurred while running the report

---

CMakeLists.txt

Fixes build on case-sensitive filesystems. See https://trac.macports.org/ticket/56536

Fix build on case-sensitive filesystems

---

libgnucash/engine/gncVendor.c

Since the data types did not match for the billterms and taxtable,
those references/guids were not saved to the database.
Similar to the PR before, but for the maint branch here.

Fix permanent storage of vendor details.

---

gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome-utils/gnc-tree-view.c
gnucash/gnome/gnc-budget-view.c
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-split-reg.c
gnucash/gnome/reconcile-view.c
gnucash/register/register-core/table-allgui.h
gnucash/register/register-gnome/table-gnome.c

Bug 795471 hopefully fixes the budget issue. There are still the existing gtk warnings about size allocation which I can get rid of if I move the gbv_treeview_resized_cb to the totals_tree_view but then I can not find a way to reliably keep the tree views in sync. The other budget changes seem appropriate but can be removed if not.
Bug 796083 could be fixed by dropping the model from the tree view and reconnecting but that raised other issues so opted to queue a redraw of the tree view instead.

Couple of bug fixes

---

data/accounts/ca/acctchrt_common.gnucash-xea
data/accounts/en_GB/uk-vat.gnucash-xea
data/accounts/ja/acctchrt_full.gnucash-xea

acctchrt_common:
there is a gratituous "i"
acctchrt_full (ja):
the Retirement and Spouse's retirement accounts have two parents
(Investment as well as ROOT), removed ROOT.
uk-vat:
the root account was pasted a line too high 7y ago. all other files have
the header block continuous

Small XML related fixes removing ambiguity improving uniformity

---

gnucash/report/business-reports/balsheet-eg.eguile.scm
gnucash/report/business-reports/balsheet-eg.scm
gnucash/report/business-reports/receipt.scm
gnucash/report/business-reports/taxinvoice.scm
gnucash/report/locale-specific/us/taxtxf.scm
gnucash/report/report-system/html-document.scm
gnucash/report/stylesheets/stylesheet-easy.scm
gnucash/report/stylesheets/stylesheet-fancy.scm
gnucash/report/stylesheets/stylesheet-footer.scm
gnucash/report/stylesheets/stylesheet-head-or-tail.scm
gnucash/report/stylesheets/stylesheet-plain.scm

This commit does away with anything gtkhtml related. Pulled out from another PR because it's different enough.
Also POTFILES.in is always regenerated during CMake - it means during development it was always annoyingly being scanned for changes. Deleting from repo means it is not tracked as directed by .gitignore in project root.

Eradicate gtkhtml in .scm

---

gnucash/report/standard-reports/test/test-transaction.scm

This modification will convert string to number (using a customized function defined in same file) to remove need to encode £ sign in scheme.
@jralls test-html-utilities-srfi64.scm uses emoji in scheme code... will this also fail in MacOS? (or is it OSX?)

[test-transaction] modify test to be acceptable to MacOS

---

gnucash/report/report-system/report.scm
gnucash/report/report-system/test/CMakeLists.txt
gnucash/report/report-system/test/test-report-system.scm

Hi,
please note that this my first pull request, it may be not the most mature pull request you have ever come across.
This pull request has three aspects:
- it fixes a bug in the current code: if the report definition is triggered for a report without a GUID, then GnuCash terminates with an error message from Guile. With this fix, an error dialog message is popping up to notify the user, and after acknowledgment the start-up of GnuCash resumes as normal.
- it adds test cases for the report definition in report.scm
- it adds a flag to report.scm that can be set to avoid calls to GUI dialogs that are not working for the tests, so by setting the tests before test-begin (and resetting after test-end) these calls can be suppressed.
Looging forward to your comments.

Bug787401 test report definition

---

gnucash/report/report-system/html-text.scm
gnucash/report/report-system/test/test-extras.scm
gnucash/report/standard-reports/test/CMakeLists.txt
gnucash/report/standard-reports/test/test-net-charts.scm

This adds basic net-barchart and net-linechart testing. It will be a prelude to #365, ensuring the reports survive. I think #365 is now ready as well.
It does not test the data generated... data is encoded in javascript `d0.push([x,y])` methods.

Maint test net charts

---

gnucash/register/ledger-core/split-register-model.c
gnucash/register/register-core/table-allgui.c
gnucash/register/register-core/table-allgui.h
gnucash/register/register-core/table-model.c
gnucash/register/register-core/table-model.h
gnucash/register/register-gnome/gnucash-sheet.c

First up, not sure if this should be against maint or master but can be changed if required.
The first patch adds the ability to create register tooltips based on cell type.
The second adds a couple of tooltips, one is based on the recn cell, this shows the reconciled date and the void reason if the transaction is voided. The other is based on the associate cell and shows the uri associated to a transaction if present. The reason for tooltips was I was thinking about a wide register layout and this would allow me to remove the void reason cell.
This could be extended to tooltips for the header but not sure if that would be required.
The last patch is for Bug 796545, not sure whether this covers the problem but maybe a start to see what is possible. There was another bug which mentions a …

Add tooltips to the register

---

gnucash/report/standard-reports/test/test-transaction.scm
gnucash/report/standard-reports/transaction.scm

This commit mainly amends the reconcile report in a few ways:
1. date filter applies to reconciliation date, rather than posted date. If reconciliation date does not exist (i.e. unreconciled split), the transaction is included anyway.
2. the balances are split to debit & credit (i.e. 'funds in', 'funds out') yet the subtotals are counted separately.
Supporting amendments:
1. test for reconciliation report
2. splits filtering is now done before sorting, because we want to sort a short splitlist.
3. modify trep-renderer to accept keyword args to support reconciliation report.
4. (unrelated) place the render-options summary above subtotal-grid

Reconciliation report amendments for 796614

---

gnucash/gnome-utils/dialog-options.c

Increase of MAX_TAB_COUNT to change appearance of dialog "Book Options" in german language.
The dialog "Book Options" looks in german different, because it has 5 tabs: four standard tabs and additionaly one tab for tax settings, which appears only for german language. The 1 to 4 tabs appearance on top (horizontal mode). The appearance switchs to vertical mode (with tabs on the left side) for 5 and more tabs. Here the setting MAX_TAB_COUNT is increased to 5. This change should make the appearance of dialog "Book Options" similar in german and other languages.
Dialog "Book Options" in english, only for comparison:
Dialog "Book Options" in german before change:
Dialog "Book Options" in german after change:

Increase of MAX_TAB_COUNT to change appearance of dialog "Book Options"

---

gnucash/register/ledger-core/gncEntryLedgerModel.c

transactions
Make the gncEntryLedgerModel 'get_date_help' function the same format
as that used in the register.

Bug 796785 - dates cannot be keyboard entered on vendor bill

---

gnucash/gnome-search/search-date.c

gnc_date_edit_get_date returns a value set to the start of the day 00:00:00 so there is a need to adjust value to 23:59:59 for LessThanEqual and GreaterThan and also use QOF_DATE_MATCH_DAY when comparing dates on one day only.

Bug796725 Date Posted options fail

---

bindings/python/function_class.py
bindings/python/gnucash_core.py
common/base-typemaps.i

Fix problems with qof_query_search_for in python bindings resulting from switch to Python 3 and different string handling.
1) Provides typemaps for QofIdType and QofIdTypeConst (patch by David Osguthorpe)
2) modification to python Query class so that search_for is a python method that creates a buffer string that stays alive as long as the query lives and calls qof_query_search_for. The latter is being imported as python Query object method _search_for.
3) Prevent Query.search_for to be overwritten by add_constructor_and_methods_with_prefix after declaration of method search_for as described above. To get that an exclude option is being added to add_constructor_and_methods_with_prefix.
Based on discussion on bugtracker: https://bugs.gnucash.org/show_bug.cgi?id=796137
This is a cleanup of …

 Fix string handling in qof_query_search_for to work with python3 

---

gnucash/report/report-system/test/CMakeLists.txt
gnucash/report/report-system/test/test-report-utilities.scm

Majority coverage of report-utilities.scm functions
Does not include:
- budget-related functions - too annoying!
- gnc:account-get-pos-trans-total-interval - don't understand
- gnc:account-get-trans-type-splits-interval - don't understand
@jralls - I can't understand (teardown) - if we call it prior to calling (test-get-account-balances) in the main test-runner, it resets all GBP symbol from "£" to "RON" causing the subsequent tests to fail unfairly. Is there another call to 'start new session'?

scheme-progress: some tests for report-utilities.scm

---

gnucash/gnome-utils/dialog-preferences.c
libgnucash/app-utils/gnc-gsettings.c
libgnucash/app-utils/gnc-gsettings.h
libgnucash/core-utils/gnc-prefs-p.h
libgnucash/core-utils/gnc-prefs.c
libgnucash/core-utils/gnc-prefs.h

When the preference dialogue is loaded and options are set, the ones with registered callbacks fire causing parts of Gnucash to be updated. This was observed with gnc_split_register_load being executed 5 times for each open register when the preference dialogue was loaded.
To overcome this, a couple of functions have been created to block and unblock all registered prefs and used while the preference dialogue is loaded. I checked to see if in the source any had the capability of being blocked but did not find any so I think it would be safe to use in the situation indicated.
There is one thing I want to change but could not work out how, that is the two gsetting functions are defined with a text parameter but should be void but when I made what I thought were the appropriate changes, it …

Block registered prefs when preference dialogue loaded

---

gnucash/report/report-system/commodity-utilities.scm

Experimental PR. Instead of repeating a whole-book query to look for prices for every commodity, cache the splitlist and reuse it for each commodity. This should dramatically cut down weighted-average ~and average-cost~ for books with large numbers of commodities. If book has 100 commodities, it would previously be running 100 queries and perform very similar analyses of the resulting splitlist.
~I've added `(get-all-splits #f)`  to clear the cache between reports, but I am unsure if I've inserted at the correct location.~
Mainly for verifying numbers are still correct, and testing how much speedup is possible. (in theory, book with N commodities with report taking t will reduce to, at most, t/N)
~This is not my preferred approach -- I'd refactor and rework but this would be disruptive to …

Generate a filtered splitlist early for weighted-average reports

---

gnucash/report/report-system/report-system.scm
gnucash/report/report-system/report-utilities.scm
gnucash/report/standard-reports/category-barchart.scm
gnucash/report/standard-reports/net-charts.scm

This is counterpart for #414 to remove previous optimization and redo.
Reuses balancelist generator from net-charts.
Subsequent to this, majority (if not all of) report-collectors.scm and collectors.scm may be deprecated.

Schemey category-barchart optimization

---

gnucash/report/business-reports/customer-summary.scm
gnucash/report/business-reports/invoice.scm
gnucash/report/report-system/report-utilities.scm
gnucash/report/standard-reports/test/test-transaction.scm
gnucash/report/standard-reports/transaction.scm
libgnucash/engine/test/test-extras.scm

~(gnc:pk) is a generally useful debugging tool. Surround any procedure call, or object, with (gnc:pk) and the program will run unchanged, yet the object will be dumped in the tracefile and 2 timestamps printed; both running timestamp and delta timestamp since the last (gnc:pk) call.~
transaction.scm upgraded to optionally toggle transaction/account anchors. seems to be an often-requested feature upgrade.

General progress .scm files

---

gnucash/gnome/gnucash.appdata.xml.in

Rename the ID from org.gnucash.Gnucash to org.gnucash.GnuCash to match
flathub, and add a launchable ID to link it to the desktop file.

Fixes to the appdata file

---

bindings/python/gnucash_business.py
bindings/python/gnucash_core.py

Let GetBalTaxValues return a list of tuples (GncCommodity, GncNumeric) by using decorate_monetary_list_returning_function. This function needs an additional arg to work here. So add args and pass them through to original function. Add some doc as well.
I used this tuple solution because there was a function that did it this way (decorate_monetary_list_returning_function). I wonder if it makes more sense to create a GncMonetary class instead.

Decorate Python GetBalTaxValues to return tuples of GncCommodity and GncNumeric

---

gnucash/gnome/CMakeLists.txt
gnucash/gnome/gnucash.appdata.xml.in

This fixes the following notice detected by `appstreamcli validate cherrytree.appdata.xml`:
```
I - gnucash.appdata.xml.in:org.gnucash.GnuCash:3
The id tag for "org.gnucash.GnuCash" still contains a 'type' property, probably 
from an old conversion.
```
And the metainfo files should be installed into /usr/share/metainfo.
See: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location

 Appdata: remove old property 

---

libgnucash/engine/Scrub.c

The refactoring provides roughly 10% reduction in user CPU use for XML file load by moving an expensive function to within an if-clause where the result is used.  The diff look like a full re-write of the function but only the if statements, indenting, and commentary changed.
Disclosure #1:  My first attempt at the pull request mechanism
Disclosure #2: I rebased my branch off of upstream/maint right before submitting this... and tied a holy knot in my own repository, but I don't think it impacts this at all.  Gah.  Learning.

Fix XML load CPU hotspot: Scrub.c xaccTransScrubPostedDate

---

libgnucash/engine/gnc-datetime.cpp

This 2-liner saves 10-20% of the user CPU for XML save.
Note that the benefit in XML save time is likely temporary given
jralls' effort to switch to UTC for XML save data.

Re-use user locale when formatting time - 10% improvement save speed

---

gnucash/gnome-utils/gnc-tree-view-account.c
gnucash/gnome-utils/gnc-tree-view-account.h
gnucash/gnome/gnc-budget-view.c
gnucash/gnome/gnc-budget-view.h
gnucash/gnome/gnc-plugin-page-account-tree.c
gnucash/gnome/gnc-plugin-page-budget.c

Another attempt at this one...
The first commit changes the default for budgets to show unused accounts so it matches the Account Treeview.
With the addition of two functions that will save and restore the account filter settings to the state file the budget will now remember these settings when the page is closed on exit. They are still being saved as part of the page saving routines as well for compatibility and in 4.x these settings could be removed from the those routines.
I have checked in version 2.6.21 that these settings are ignored and left as is but to achieve this I needed to change the key names to include an underscore so that version would not crash, this was fixed in 3.2.
The last commit adds the same capability to the 'Accounts TreeView' so if you do open a new accounts …

Bug796965 - Change the default to show unused accounts

---

gnucash/gnome-utils/gnc-tree-view-split-reg.c

gcc version 8.2.1 20181127 (GCC) gave a warning pointing at the problem.

gnc-tree-view-split-reg.c:  strncpy into datebuff risked non-null-terminated string.

---

gnucash/python/pycons/shell.py

There is no call `traceback.print` - these are obviously mistakes. And they can even cause compile-time errors as `print` is a reserved function name in Python.

Fixes to traceback calls in pycons

---

libgnucash/backend/dbi/gnc-backend-dbi.cpp

When a session is opened in the Python bindings which doesn't contain a database e.g.:
session = gnucash.Session('mysql://xxxx', is_new=False, ignore_lock=True)
The following error occurs:
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
During startup program terminated with signal SIGABRT, Aborted.
Looking though the code in gnc-backend-dbi.cpp it looks as though there's some possiblity of using 'default' databases if a dbname isn't supplied, so I think it should be possible for a dbname to be empty at this point.
With the change the error is now replaced with a 'ERR_BACKEND_SERVER_ERR' exception in Python (which I think is correct if a default database can be used).
Any comments or feedback welcome - thanks.

Resolve 'basic_string::_M_construct null not valid' error

---

data/accounts/hr/acctchrt_common.gnucash-xea
data/accounts/hr/acctchrt_eduloan.gnucash-xea
data/accounts/hr/acctchrt_fixedassets.gnucash-xea

Just noticed, that I forgott to change the "guid" string in these two files, as specified in the wiki: "Just replace all occurrences of <act:id type="guid"> by <act:id type="new">".
Only the croatian files for "eduloan" and "fixedassets" needed the change. Sorry for the inconvienience!

Croatian accounts correction

---

gnucash/report/standard-reports/balance-forecast.scm

Whoops! I could have sworn I had allowed the reserve and target lines to be negative, but when I went to chart some liability accounts just now, turns out I missed it. >.>

[balance-forecast] Allow negative values for reserve and target

---

libgnucash/app-utils/date-utilities.scm
libgnucash/app-utils/test/test-date-utilities.scm

If the original date is an end-of-month date, we take it as an indicator they always want month-delta dates to be end-of-months. This works for monthly/quarterly/halfyearly/annual. Also I'd forgotten to activate a test in test-date-utilities. Enable it.
This works for any month-end date, even leapyears.
monthly from 28/02/16 = 28/02/16, 28/03/16, 28/04/16, 28/05/16...
monthly from 29/02/16 = 29/02/16, 31/03/16, 30/04/16, 31/05/16...
Apparently human psychology is preferable to cold logic...

Bug 639049 - Asset Barchart Report includes also the first day of next month transactions

---

gnucash/report/report-system/report-system.scm
gnucash/report/report-system/report-utilities.scm
gnucash/report/standard-reports/average-balance.scm
gnucash/report/standard-reports/test/CMakeLists.txt
gnucash/report/standard-reports/test/test-average-balance.scm

This PR aims to deprecate `gnc:make-dr-cr-collector` and `gnc:make-stats-collector`.
The `analyze-splits` ~function from `average-balance` was copied nearly verbatim into `daily-reports` by wingo.~
~First it was deduped. Then~ converted stepwise to use scheme numbers via named-let loops instead of these collectors.
I was using test-average-balance to confirm analyze-splits behaviour was unchanged... however when the test is run in a different TZ the amounts differ; this corresponds to a longstanding bug whereby account period averages are sensitive to TZ.
Finally `gnc:make-dr-cr-collector` and `gnc:make-stats-collector` can both be deprecated.
Comments welcome -- I think the scheme named let loops is a much cleaner approach than using the original accumulators...

Fix  TZ dependency in average balance reports (Bug 748431)

---

gnucash/report/standard-reports/transaction.scm

A few scheme housekeeping commits.
Transaction Report can be amended to render other-account better in single-split and compound-txn cases. This amends display for both Display/Other-account-name/code, and Sortkey=corresponding-account-name.

Improve TR display/other-account and Sortkey=other-account renders

---

bindings/python/gnucash_business.py
bindings/python/gnucash_core.py
bindings/python/time64.i

Include typechecking for time64 SWIG typemaps. Allow int in addition to datetime.datetime and datetime.date. Use modifiable time64 arguments as return value.
Relates to https://bugs.gnucash.org/show_bug.cgi?id=797177.

Pr python time64 modifications

---

gnucash/python/pycons/console.py
gnucash/python/pycons/ishell.py
gnucash/python/pycons/shell.py

Make pycons great again. Turning on the ipython shell does not yet work as the ipython api from 5 on has changed a lot.

Pr pycons2to3 - fix python console in python3

---

libgnucash/app-utils/fin.scm

https://bugs.gnucash.org/show_bug.cgi?id=797195
Changed gnc:computeInterestIncrement to use a new futureValue calculation that takes time as a number of periods.

Bug 797195 - computeInterestIncrement function in fin.scm only works for annual compounding

---

gnucash/python/init.py

fix Bug 797205
https://bugs.gnucash.org/show_bug.cgi?id=797205

python console - fix deprecated positional arguments with the GObject constructor 

---

gnucash/gnome/dialog-price-editor.c
gnucash/gschemas/org.gnucash.dialogs.import.generic.gschema.xml.in
gnucash/gschemas/org.gnucash.dialogs.import.qif.gschema.xml.in
gnucash/gtkbuilder/assistant-qif-import.glade
gnucash/gtkbuilder/dialog-account-picker.glade
gnucash/gtkbuilder/dialog-import.glade
gnucash/import-export/import-account-matcher.c
gnucash/import-export/import-account-matcher.h
gnucash/import-export/qif-imp/assistant-qif-import.c
gnucash/import-export/qif-imp/dialog-account-picker.c

Just a heads up before I try and push some bug fixes for the QIF import assistant the main being the first bug that deals with tradable commodities being added as assistant pages and if you have a lot you loose the assistant buttons of the screen so on the commodities assistant page I added a notebook and then each commodity is then added as a notebook page.
The other bugs were relatively straightforward so I think should be OK with some others that should be closeble as a result.
The last commit fixes one issue with the cancel/undo but there is still another one coming from scheme that I have not figured out so may look at it separately.

Qif Import Assistant changes

---

libgnucash/engine/gnc-int128.cpp
libgnucash/engine/gnc-rational-rounding.hpp
libgnucash/engine/test/gtest-gnc-int128.cpp
libgnucash/engine/test/gtest-gnc-numeric.cpp

The division method was returning negative remainders only when the absolute value of the dividend was less than the value of the divisor for all other cases it didn't respect (a/b)*b + a%b = a. Also changed rounding to be based on the sign of the remainder so that numbers between -1 and 0(quotient 0 and remainder negative) are rounded correctly fixing Bug 796949.

Fixed division to return negative remainders.

---

libgnucash/engine/gnc-numeric.cpp

Fix error that caused strings in the form 0.nnn to be
converted to negative numerics.

[numeric] Fix constructor from strings in range (0 ,1)

---

gnucash/gnome/gnc-budget-view.c
gnucash/gnome/gnc-plugin-budget.c
gnucash/gnome/gnc-plugin-page-budget.c
gnucash/gtkbuilder/gnc-plugin-page-budget.glade
gnucash/ui/gnc-plugin-page-budget-ui.xml
libgnucash/engine/qofbook.cpp

Add an option to estimate the budget as a flat average of the reference values, instead of using it period by period.
For many accounts that doesn't have a clear seasonality, it is best to budget a flat average of the historic values, instead of copying exact values by period.

[budget]: various fixes and enhancements

---

gnucash/html/gnc-html-webkit2.c
gnucash/html/gnc-html-webkit2.h
gnucash/html/gnc-html.c
gnucash/html/gnc-html.h
gnucash/report/report-gnome/gnc-plugin-page-report.c

This removes the export to PDF button and uses the standard print
dialog with an option to print tp pdf.
The filename is pre-populated, with the path set to the default, $HOME
on linux.
There is no remembering of past output directories.  Maybe a later
update will do this.

Implement "printing" to a pdf.

---

gnucash/report/report-system/report-utilities.scm
gnucash/report/standard-reports/budget.scm

Adds some more fixes to "Budget Reports":
add multicurrency support
remove unused option "rollup budget" (it is always used)
fix color formatting in budget column
Adds a fix to the budget register:
Respect read-only state of a book and date threadshold for editing budget values
This replaces #512

Budget Report fixes

---

gnucash/gnome-utils/window-main-summarybar.c

Offshoot from #524 -- sets the summary-bar display currency to default_currency.
This seems uncontroversial -- modifies display currency only. It's also updated live in Edit / Preferences.

Set the summarybar currency to default_currency

---

gnucash/gnome-utils/dialog-transfer.c
gnucash/gtkbuilder/assistant-csv-price-import.glade
gnucash/import-export/csv-imp/assistant-csv-price-import.cpp
gnucash/import-export/csv-imp/gnc-imp-props-price.cpp
gnucash/import-export/csv-imp/gnc-imp-props-price.hpp
gnucash/import-export/csv-imp/gnc-imp-props-tx.cpp
gnucash/import-export/csv-imp/gnc-imp-settings-csv-price.cpp
gnucash/import-export/csv-imp/gnc-import-price.cpp

This PR fixes the Bug797278 by adding 'From Namespace' and 'From Symbol' columns which align with the Security Editor. I have tested all the combinations I could think off with the correct expected results.
I think it is safe for maint but there are a some translation changes so seeking confirmation.
The last commit, Bug797244 removes the inversion of prices if less than 1.
For the import, prices go against the non currency commodity and currency rates go in the direction of the import. For the Transfer dialogue prices are against the non currency commodity and currency to default currency being against the default currency. Not sure if there is more required here or if there is any benefit in rates being against the non default currency?

Bug797278 Fix for Price import

---

gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-split-reg.c
gnucash/gnome/gnc-split-reg.h
gnucash/register/ledger-core/split-register-model.c
gnucash/register/ledger-core/split-register.c

I had a look at this one and I started off thinking about adding the warning dialogue but then thought why not disable the menu options when not appropriate which is probably the correct option.
So this commit does that, disables the 'Cut' option when the cursor is on the anchor split along with 'Delete' and 'Paste'. Also added tests for the transaction being read only with appropriate options being disabled.
The only thing I am concerned with is if having some options disabled on some splits will raise questions from users.

Bug 797249 - Cutting home account causes transaction to disappear

---

gnucash/report/business-reports/business-reports.scm
gnucash/report/business-reports/customer-summary.scm
gnucash/report/business-reports/owner-report.scm
gnucash/report/report-system/html-table.scm
gnucash/report/report-system/report-utilities.scm

This line of work starts from fixing customer-summary.scm -- has issues, too numerous to mention
* counts all monetary amounts irrespective of currency
* can't handle multiple customer currencies
* formatting
* now has URL to owner-report.
* hidden useless options removed -- this report hardwired for customers; not much benefit creating parallel reports for vendors/employees/jobs. (saved-report trying to set a removed option does not cause a crash).
owner-report.scm also slightly upgraded
* running Report > Account Report (single transaction) will now run owner-report and find the appropriate APAR account according to owner's currency.
* other small srfi-1 refactoring
* timepair->t64 fix too
I'll leave this here a small while, I do not think these changes are uncontroversial, nor unsafe.

[customer-summary] work with multiple currencies

---

util/obfuscate.pl

Fixes the "Wide character in subroutine entry" error for some UTF8 entries

Check and UTF8-encode the names if needed

---

gnucash/report/reports/reports.scm
gnucash/report/reports/standard/customer-summary.scm
gnucash/report/reports/standard/owner-report.scm

a couple mishaps during recent work
@gjanssens is the intention that reports need to `(use-modules (gnucash reports))`? without this line, customer-summary and owner-report crash. i'm not sure why other reports don't need it.

fix master maint merge and reports

---

libgnucash/engine/engine.i
libgnucash/engine/qoflog.h
libgnucash/scm/CMakeLists.txt
libgnucash/scm/utilities.scm

Figuring out how to wrap qoflog.h
Still unsure how to check appropriate log domain is debug-enabled.
Checking "gnc" will be too noisy; checking "gnc.reports" means gnc:debug isn't working in libgnucash/scm

Wrapqoflog

---

gnucash/report/standard-reports/budget.scm
gnucash/report/standard-reports/test/test-budget.scm

Merges ideas from Phil Longstaff's ytd-budget.scm report
Copied from #532 which had become messy.
Screenshot:

[budget] upgrade to show YTD values

---

.travis.yml

As discussed in #545, [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).  Mention  of the __sudo:__ tag has been removed from all Travis docs because the sudo command is now _always_ available and there is no way to turn it off.

Remove the deprecated sudo tag from .travis.yml

---

gnucash/gnome-utils/account-quickfill.c
gnucash/gnome-utils/gnc-gnome-utils.c
gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome-utils/gnc-main-window.h
gnucash/gnome-utils/gnc-plugin-manager.c
gnucash/gnome-utils/gnc-plugin-menu-additions.c
gnucash/gnome-utils/gnc-plugin.c
gnucash/register/ledger-core/split-register-model.c
gnucash/register/register-gnome/combocell-gnome.c
libgnucash/app-utils/gnc-gsettings.c
libgnucash/app-utils/gnc-prefs-utils.c
libgnucash/app-utils/gnc-prefs-utils.h
libgnucash/app-utils/gnc-ui-util.c
libgnucash/app-utils/gnc-ui-util.h
libgnucash/core-utils/gnc-prefs.c
libgnucash/core-utils/gnc-prefs.h

This is a follow up for the blocking of registered preference callbacks to remove the callbacks on GncWindow close and quit.
The first few commits are straightforward adding functions to remove the preference callbacks setup in various source files.
There are two 'register' preference callbacks that are setup with a 'g_once' that are used till quit so the easiest way to remove them was to save the preference id and use that on quit.
With these changes it took the remaining callbacks from about 50 to 3 on quit.
These last few are setup via plugins so there is a couple of commits dealing with that with the final commit destroying the hash table when there are no callbacks left.
I have tested this by quitting with multiple windows open and closing windows in different orders and all …

[Master] Remove preference callbacks on quit / window close

---

gnucash/report/business-reports/balsheet-eg.css
gnucash/report/business-reports/balsheet-eg.eguile.scm
gnucash/report/business-reports/receipt.eguile.scm
gnucash/report/business-reports/taxinvoice.eguile.scm
gnucash/report/report-system/html-document.scm
gnucash/report/report-system/html-fonts.scm
gnucash/report/report-system/test/test-report-html.scm
gnucash/report/standard-reports/balsheet-pnl.scm
libgnucash/scm/utilities.scm

* Enable autodetect for rtl
* Fix guile-2.0 string-ports handling
* Better strings handling in balsheet-pnl -- I figure `~a to ~a` is better than `(display x) (display (_ " to ")) (display y)`
* Fix some i18n strings in balsheet-pnl

Maint 797279 - fixes for RTL languages and better i18n

---

gnucash/gnome-utils/gnc-tree-view.c
gnucash/gnome-utils/gnc-tree-view.h

I was going to push this but decided to see if there were any concerns.
The cause of this warning is when the spacer column of the GNC_TREE_VIEW is reduced to a size that the header button will not fit, So I have removed this column and made the menu select column do the expanding to fill any space. This resulted in the menu being activated on the whole column header so added a button_press_event callback for the 'go-down' image along with a vertical separator which I think looks OK and works.
I have tested this in all the places I think the GNC_TREE_VIEW is used and also LTR. If there are no concerns I will push this at the weekend.

Bug797341, Gtk Negative content width warning

---

gnucash/report/standard-reports/register.scm
gnucash/report/standard-reports/test/test-register.scm

Previously, for general-journal, each split was being analyzed, and only the source split was counted for totals. This change will means the source split *and* its peers were used in the debit/credit totals. From my testing it's a good fix, and I've amended test suite to accommodate.

Bug 797355 - General Journal report seems to be off balance

---

gnucash/gtkbuilder/dialog-import.glade
gnucash/import-export/import-main-matcher.c

Connect signal so that Alt-F4 will properly delete partially imported transactions. From #565

[dialog-import] connect delete_event to gnc_gen_trans_list_delete

---

gnucash/gnome/dialog-fincalc.c
gnucash/gtkbuilder/dialog-fincalc.glade

Attempt. Probably stinky code.
* the calc_clicked_cb had mechanism to abort if no fields were empty. disable it.
* to convert gnc_numeric to string, the only suitable print_info is `gnc_share_print_info_places` which takes decimal and outputs suitable print_info. Not very suitable, but works.

Bug 605602 - precision of Financial Calculator seems to depend on locale

---

gnucash/report/report-system/html-acct-table.scm
gnucash/report/standard-reports/account-summary.scm
gnucash/report/standard-reports/test/test-balsheet-pnl.scm

1. restore amount indenting in account-summary.scm for bug 797332
2. remove the "has-children && immediate-bal" conditional to artificially reduce the amount indent-level for reports using html-acct-table. This causes confusing indenting for account-trees whereby the account-depth varies across accounts.

Maint 796952 797332

---

gnucash/report/report-gnome/window-report.c
gnucash/report/report-system/html-utilities.scm
gnucash/report/report-system/report-system.scm
gnucash/report/report-system/test/test-html-utilities-srfi64.scm
libgnucash/app-utils/c-interface.scm
libgnucash/scm/test/test-libgnucash-scm-utilities.scm
libgnucash/scm/utilities.scm

Couple commits to show backtrace in report crash.
* exposes a SCM string `gnc:last-captured-error` containing last backtrace
* when rendering report-crash window, include it in `<pre>` block
* we *do* need to upgrade `gnc:html-string-sanitize` to `libgnucash` to neutralize the captured-error -- otherwise if backtrace contains `</pre>` it will prematurely end the block and mess up the error. Or even worse, backtrace could contain a `<script>` block :)
* note this snippet is not thread-safe -- `gnc:last-captured-error` could be modified in another thread and the errorpage gets the wrong string, but we'll leave it for another decade...

show backtrace in report error

---

gnucash/report/report-system/html-table.scm
gnucash/report/report-system/test/test-report-html.scm
gnucash/report/standard-reports/budget.scm

Fixes display of negative monetary-amounts so that they are rendered according to style-sheet option.
This commit fixes via the `<td>` renderer -- if it has a single datum, and has a negative monetary amount, then its tag (e.g. `number-cell`) gets `-neg` appended to become `number-cell-neg`. Some internal function ensures the resulting html becomes `<td class="number-cell neg" ...>`

Bug 797357 - Negative amounts are not displayed in red in some reports

---

gnucash/import-export/aqb/dialog-ab.glade
gnucash/import-export/aqb/gnc-gwen-gui.c

This is a (partly) fix for Bug 667490. It implements the presentation of optical TAN challenges (e.g. photoTAN) inside the enter TAN dialogue.

Optical tan

---

gnucash/gnome/dialog-invoice.c

Allow editing of some fields for posted invoice.
For reasons, see bug report:
https://bugs.gnucash.org/show_bug.cgi?id=797400
Reverts some changes done to fix:
https://bugs.gnucash.org/show_bug.cgi?id=797168

Allow edit of some fields for posted invoice

---

gnucash/import-export/aqb/gnc-ab-utils.c

Use the proper UTF8 strip function.

---

gnucash/gnome/dialog-payment.c
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gtkbuilder/dialog-payment.glade

A better #599 - Show warning if no documents were assigned to payment, and show warnings in gtklabel instead of a tooltip. Warning icon is still shown/hidden appropriately.

Better UI Refinements

---

gnucash/report/business-reports/new-aging.scm

1. Don't error out when payment doesn't have owner. Log and skip it.
2. Render the skipped list in report. Links to offending split.

Bug 797506 - New Aging errors out with guile backtrace in case of a few uncommon transactions

---

libgnucash/backend/xml/io-example-account.cpp
libgnucash/backend/xml/io-gncxml-v2.cpp
libgnucash/backend/xml/io-utils.cpp
libgnucash/backend/xml/io-utils.h

Modern versions of emacs know, how to behave on xml files.

drop emacs_trailer from xml files.

---

common/debug/valgrind/valgrind-compiz.supp
gnucash/gtkbuilder/dialog-import.glade
gnucash/import-export/import-account-matcher.c
gnucash/import-export/import-account-matcher.h
gnucash/import-export/import-main-matcher.c

These changes are as a result of ideas in #518 which I will close when I push this.
The main change is from a list store to a tree store and using a child row to display the matched information. Other changes involved are restricting the selected account currency to that of the import if provided and some changes to the tree view.
@christopherlam Could you give this a spin, hopefully I have included the good stuff and like my change to your idea.

[Master] Import Matcher changes from PR518

---

bindings/python/example_scripts/rest-api/gnucash_simple.py
bindings/python/gnucash_core.py

Python syntax fix - remove not needed semicolons.

Remove not needed semicolons in Python bindings

---

gnucash/gnome-utils/dialog-options.c
gnucash/gnome-utils/dialog-options.h
gnucash/gnome/business-options-gnome.c
gnucash/report/reports/example/hello-world.scm

Change the dialogue options to use a two column grid and setup to be the same as other dialogues. In the first column there is the 'name' of the option and the right column the option widget. There are two options that do not conform to this and they are the 'account-select' and 'list' options that have frames with the 'name' contained and so these two options use both columns.
This is a follow on from PR614 but was not sure if this would affect John's work so created separate PR, @jralls this can wait if this would interfere with your changes.
I have tested all the options and all looks good apart from radiobutton-option and currency-accounting-option-... which I can find being used.
@christopherlam Have I missed them, would it be possible to add a radiobutton example to Hello, World' …

[Master] Change dialog-options to use a two column GtkGrid

---

common/base-typemaps.i
libgnucash/engine/Transaction.c

While exploring alternatives to xaccAccountGetSplitList (gets slow e.g. account has 1000s of splits) I found `g_list_nth_data` being used in a few places which is known to be inefficient.
https://developer.gnome.org/programming-guidelines/stable/glist.html.en
My aim was to traverse an account splitlist by pointer dereferences rather than creating a GList to be converted to SCM list. I am now sure how to do yet. Creating calls to xaccAccountGetFirstSplit, xaccSplitGetNextSplit does not seem currently possible.
But these two optimisations seem very safe and correct.

Optimize glist by avoiding g_list_nth_data

---

gnucash/gnome/gnc-budget-view.c
gnucash/gnome/gnc-plugin-page-budget.c
gnucash/report/standard-reports/budget-balance-sheet.scm
gnucash/report/standard-reports/budget-income-statement.scm
gnucash/report/standard-reports/budget.scm
libgnucash/app-utils/app-utils.i
libgnucash/app-utils/gnc-ui-util.c
libgnucash/app-utils/gnc-ui-util.h
libgnucash/engine/gnc-features.c
libgnucash/engine/gnc-features.h

I guess this branch will be merged into maint, then merge maint to master, then merge #585 scrubbing function.
Modify maint branch to handle both reversed & unreversed budgets.
Scrubbing existing budget data is not done until master.
Draft. Not sure I've handled all possibilities. But I think this is safe.

[maint] budget code handles both natural and reversed amounts

---

gnucash/gnome-utils/gnc-plugin.h
gnucash/gnome/dialog-invoice.c
gnucash/gnome/dialog-invoice.h
gnucash/gnome/gnc-plugin-page-invoice.c

An attempt at fixing Gnucash#743943. The approach taken is to define parametrized strings and perform the actual translation depending on the invoice type and update of the actions on every call to `gnc_plugin_page_invoice_update_menus` accordingly.
The PR also include one tiny edit in the documentation to add a word I noticed was missing.

Fix bug 743943

---

gnucash/report/business-reports/new-owner-report.scm
gnucash/report/report-system/html-table.scm
gnucash/report/report-system/report-system.scm

I think this is good to go.
Upgrade to html-chart. `html-chart` record property `col-headers` is repurposed to contain a list-of-list-of-th-elements, instead of previous list-of-th-elements. new-owner-report can show double th row. 2 new API functions, and backward compatibility is maintained.

Maint multirow table headers

---

gnucash/report/report-gnome/gnc-plugin-page-report.c

Please check if - and amend if needed - the syntax of menu paths (I used `>`) is the correct one for the project and/or the German locale.
Thanks.

reports: bug fixes in translation strings

---

bindings/python/gnucash_business.py

gncInvoiceUnpost isn't exposed as part of the Invoice object in the Python bindings so this minor commit added it for easier unposting from Python.

Add Invoice.Unpost() to Python Bindings

---

gnucash/gnome/assistant-hierarchy.c
gnucash/gtkbuilder/assistant-hierarchy.glade

In the account hierarchy assistant the choice of account template was
decided by the your locale and so could be limited. Add two combos so
you can select account templates by language and region.
@fellen Frank does this do what you want?

[Master] Bug 797472 - Add option to choose account templates

---

gnucash/gnome/gnc-budget-view.c

Reinstate Income/Expense/Transfer/Total, but rename to:
* Inflow from Income
* Outflow to Expense
* Outflow to Asset/Liability/Equity
* Remaining to budget
Behavior should be identical to previous release v3.7

Reinstate budget editor summaries

---

gnucash/report/report-system/html-fonts.scm

When dark theme is active in Gnome Shell it sets text colour to white, combined with background colour set in default style to white lead to unreadable reports.

Fix white text on white background

---

gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome-utils/gnc-plugin-page.c
gnucash/gnome-utils/gnc-plugin-page.h
gnucash/gnome/gnc-plugin-page-account-tree.c
gnucash/gnome/gnc-plugin-page-account-tree.h
gnucash/gnome/gnc-plugin-page-budget.c
gnucash/gnome/gnc-plugin-page-budget.h
gnucash/gnome/gnc-plugin-page-invoice.c
gnucash/gnome/gnc-plugin-page-owner-tree.c
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-plugin-page-register.h
gnucash/gnome/gnc-plugin-page-sx-list.c
gnucash/report/report-gnome/gnc-plugin-page-report.c

This commit moves the setting up of the page changed signal callback to when the plugin page is inserted and also records the id used. The call back functions have been changed to reflect the signal spec and cast to the correct types. The id is used to disconnect this callback when the page is moved to a different window with the gnc_main_window_cmd_window_move_page function so it gets disconnected as early as possible before pages start changing. It is also used when the page is destroyed.

Follow up to previous commit 94cb965 / Bug 797522

---

gnucash/import-export/bi-import/dialog-bi-import-gui.c
gnucash/import-export/customer-import/dialog-customer-import-gui.c

…imported rows does not expand with window size
In the import of Customer/Vendors en Bills/Invoice, the dialog that lists rows that were not imported shows a scrollable view of only four rows.
The view does not use the available space of the window, and does not expand with resizing the window. This change fixes this issue.
In the same functionalities, the dialog for a user defined regular expression has a similar issue. This changes also fixes that issue.

Bug 797570 Import Customers/Vendors, Bills/Invoices: list view for not imported rows does not expand with window size

---

gnucash/gnome/dialog-invoice.c

In the invoices due dialog, the column 'Company' should show the name of the customer/vendor of an invoice/bill.
Currently the content is set to the owner name, but if a job is assigned to the invoice, that will show the job name.
This change changes the content to the name of the owner parent, which is always  the customer/vendor name.

Bug 797613  Due Invoices Reminder shows Job Name instead of Company Name

---

data/pixmaps/hicolor/scalable/apps/gnucash-icon.svg

SVG icon doesn't open with latest librsvg (2.48) due to bad URI.
XML parse error: error code=99 (3) in (null):10:72: xmlns:sodipodi: 'http://inkscape.sourceforge.net/DTD/s odipodi-0.dtd' is not a valid URI

Remove unwanted space from xmlns sodipodi URI.

---

gnucash/import-export/csv-imp/gnc-imp-props-price.cpp

I've noticed that in the `round_price` function, in `gnucash/gnome-utils/dialog-transfer.c:200`, commodity prices are rounded according to the following policy:
>  If both commodities are currencies, round to a fixed denominator.            
>  If only one is a currency, round to the currency's scu * a fixed factor.     
>  The fixed values are defined in gnc-pricedb.h                                
However, when importing the commodity prices from a CSV, the rounding applied is computed in a different way.
This patch amends this by making the CSV import assistant approximate commodity prices as it's done in the transfer dialog.
*_For reference, the actual code of the `round_price` function is the following:_
```
static gnc_numeric …
```

Fix rounding precision when importing commodity prices from CSV

---

gnucash/gnome/window-reconcile.c
libgnucash/app-utils/gnc-ui-balances.c
libgnucash/app-utils/gnc-ui-balances.h
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h

adds a couple helper functions in account.cpp and gnc-ui-balances.c

Bug 797640 - The Reconciliation Window starting balance calculator needs to ignore splits after statement date

---

gnucash/import-export/aqb/assistant-ab-initial.c
gnucash/import-export/aqb/gnc-ab-utils.c
gnucash/import-export/aqb/gnc-ab-utils.h

See Bug [797631](https://bugs.gnucash.org/show_bug.cgi?id=797631) for more details.

Bug 797631 - Superfluous account selection dialog on first online transaction retrieval

---

gnucash/import-export/aqb/assistant-ab-initial.c
gnucash/import-export/aqb/assistant-ab-initial.glade

A push button with text "Delete selected matches" is added to the
"Match Online accounts with GnuCash accounts" page of the "Online
Banking Setup" tool.
Additionally, the underlying tree view is set to multiple selection
mode from single selection mode.
Pushing the button will remove the matched GnuCash account from
all selected AqBanking (Online) accounts.

Bug 797636 - Incorrect Online account matches cannot be deleted

---

gnucash/gnome/reconcile-view.c

Force all splits in a transaction for the account being reconciled
(and its children), to have the same reconciliation status. This fixes
a problem when the splits have different statuses.

Bug 797648 - Fix problem reconciling multiple splits in a transaction

---

gnucash/python/pycons/ishell.py

I've only tested this with python -Wd and not actually used it.
ipapi.get() has been deprecated since 0.11 (2011) apparently:
https://stackoverflow.com/questions/13864126/no-module-named-ipapi#comment19164908_13864322

Make pycons/ishell.py compatible with Python 3 and current IPython

---

bindings/python/function_class.py
bindings/python/gnucash_core.py
bindings/python/tests/runTests.py.in
bindings/python/tests/test_account.py
bindings/python/tests/test_book.py
bindings/python/tests/test_business.py
bindings/python/tests/test_commodity.py
bindings/python/tests/test_numeric.py
bindings/python/tests/test_session.py
bindings/python/tests/test_split.py
bindings/python/tests/test_transaction.py
common/cmake_modules/GncAddSwigCommand.cmake
libgnucash/app-utils/app-utils.i

if Session is used only as a wrapper for an existing session instance
its necessary to be able to pass this instance as an argument
Session(instance=gnucash._sw_app_utils.gnc_get_current_session()) is impossible otherwise as can be used in the python shell

add instance argument to Session constructor

---

gnucash/gnome/dialog-find-transactions.c
gnucash/gnome/window-reconcile.c
gnucash/gtkbuilder/window-reconcile.glade

Here are 3 approaches to handling future reconcile dates. Not sure which one will be most effective.
1. Double-check before accepting a future reconcile date. Uses `goto` because I can't make `do..while` work.
2. ~`xaccAccountGetReconciledBalanceAsOfDate` also includes future reconciled splits likely in error. An ugly hack.~
3. ~Disallow reconcile date > 1week from today.~

Handle future reconcile statement dates

---

gnucash/gnome/dialog-sx-editor.c

Added call to qof_instance_get_destroying() so we can ignore a non-existing account if we're in the process of destroying the split.

Bug 797114 - Fixing an SX due to deleted account stuck in an error loop

---

libgnucash/engine/qofid.cpp

Patch from Jeff Law (law@redhat.com):
Rename one instance of struct _iterate to struct _qofid_iterate to avoid ODR problems with LTO.
(downstream Fedora patch)

Fix building with link-time-optimization.

---

libgnucash/app-utils/gnc-exp-parser.c

If gnc:fn returns anything other than a finite real number, abort rather than crash. Precursor to #691
test by modifying `fin.scm`:
```scheme
(define (gnc:foobar val) (and (positive? val) val))
```
and in SX formula try both `foobar(20)` and `foobar(-20)` -- now gnc:function can return anything, and will only be processed if it returns a number.

[gnc-exp-parser] don't crash when gnc:fn returns non-number

---

gnucash/import-export/import-account-matcher.c

Two tiny changes to help the workflow when selecting accounts. 
Sets the focus to the filter edit cell when the find dialog is created (i shortcut). So you can start typing right away. 
Expand the account tree fully when the "select account" dialog is created (so you can start typing and any subaccount can be found).

Set focus to filter in search

---

gnucash/gnome-utils/dialog-dup-trans.c
gnucash/gnome-utils/dialog-dup-trans.h
gnucash/gnome/gnc-plugin-budget.c
gnucash/gnome/gnc-plugin-page-register.c
gnucash/ui/gnc-plugin-budget-ui.xml

Adds UI to get reversed transaction date. Current code acts immediately and doesn't jump to new split. This commit offers a chance to cancel.
This code also tries to jump to the reversing transaction, but fails. Not sure why this jump doesn't actually work.

General UI - improve consistency of menu actions

---

libgnucash/app-utils/fin.scm

Adding definition of gnc:amort_balance() that got lost in the original pull-request for #490.
(Using guile syntax proposed by @christopherlam)

Adding lines missing from fix for Bug 797196

---

gnucash/gnome-utils/CMakeLists.txt
gnucash/gnome-utils/gnc-cell-renderer-text-view.c
gnucash/gnome-utils/gnc-cell-renderer-text-view.h
gnucash/gnome-utils/gnc-cell-view.c
gnucash/gnome-utils/gnc-cell-view.h
gnucash/gnome-utils/gnc-tree-view-account.c
gnucash/gnome-utils/gnc-tree-view.c
gnucash/gnome-utils/gnc-tree-view.h

I think this is correct and works OK but just a question.
This fix adds a new cell renderer based on a text view to fix editing the notes field on the account tree view. As part of this, when editing the notes field I am using the return key to add new lines and then to complete the edit I am using 'shift and return/keypad enter', Should this be the other way round or some other key combinations?
I have also added gnc_tree_view_add_text_view_column but there is really only one line different to that of gnc_tree_view_add_text so extracted common code to be called from these functions.

[Master] Fix issue when editing the account tree view notes field

---

bindings/python/__init__.py
bindings/python/app_utils.py
gnucash/python/init.py

An import statement was missing to actually utilize the app_utils wrapper. Modify python shell to use this wrapper.

Python app utils 2

---

gnucash/gnome/window-reconcile.c
gnucash/import-export/ofx/CMakeLists.txt
gnucash/import-export/ofx/gnc-ofx-import.c
gnucash/register/ledger-core/gnc-ledger-display2.c
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h

To make this work, I had to add the right header and make a change to the CMakeLists file.
The ofx code used to have a static int to count imported transactions, which was a bit hacky.
I replaced it with a structure that's passed to all the callbacks. The structure has
the transaction count, as well as 2 lists if accounts + statement balances.
These lists are used after the import of the ofx file to do the reconciliation.
NOTE: I wouldn't need lists since the current code only process one ofx at a time. However
I have another PR for importing several ofx files in one shot, so this PR is ready for that.
The reconciliation code is modeled after what's done in aqbanking.
- Question: should I add a preference to enable/disable automatic reconciliation after ofx import?
- Also: I just noticed …

Add reconcile immediately after ofx import, based on statement

---

gnucash/report/reports/standard/income-gst-statement.scm
gnucash/report/reports/standard/test/test-income-gst.scm

DRAFT awaiting VAT-report finalisation.
This commit enables CSV export of transaction-report and gst-report monetary columns and grand-totals.
Sample CSV output
```csv
"from","2018-01-01"
"to","2018-03-31"
"Debit",4270.88
"Credit",8314.44
```
Note dates are iso-format strings.
If a grand-total has multiple currencies, all will be listed without currency; e.g. grand-total 100GBP + 50USD will show as: `"Amount",100,50`. The order is not specified.

[UK] VAT and [AU] BAS report

---

gnucash/import-export/import-main-matcher.c

… is destroyed
This fixes the crash by adding gnc_unregister_gui_component(). Was previously a PR on master, now moved to maint.

Fix a crash that occurs when opening a new book after opening and closing the transaction matching dialog.

---

gnucash/gnome/reconcile-view.c

The previous change under this bug which propagated the status
change (reconcile or unreconcile) of any split for the account to
be reconciled (and its subaccounts) in a transaction, to all
splits for the account to be reconciled (and its subaccounts) in
the transaction, is incorrect. Each split needs to be able to be
checked or unchecked independently of any other split in the
transaction.
For instance, if an order delivery was split into 2 parts delivered and billed in different statement periods, the 2 splits need to be reconciled independently.
If anyone needs to reconcile or unreconcile multiple splits in a transaction, they can still do a multi-split selection, then use either the 'Reconcile Selection' or 'Unreconcile Selection' buttons. This is slightly more work, but we need the …

Bug 797648 Redo - Reconciliation - Treat each split independently

---

gnucash/gnome/reconcile-view.c
gnucash/gnome/window-reconcile.c

Ensure selected split (or last selected if multiples selected), is
visible after all operations when the list is refreshed.
After a deletion using the Reconcile window Delete button, the
selected split has been deleted, so preselect the next split after
the split to be deleted, so the working position in the list is
still visible. If no next split in the list, select previous.
The split preselected must have a different parent transaction to
the split to be deleted, as all splits in the transaction will be
deleted.
This PR (master) replaces maint PR 698.

Bug 797236 - Reconciliation - Retain visibility of selected split

---

gnucash/gnome/window-reconcile.c

Enable the Reconcile window debit & credit unreconciled split
lists to be automatically updated when transactions for
subaccounts of the account to be reconciled are added, modified or
deleted. This already occurs for the reconciliation account.

Bug 797388 - Add watch for each subacct of the acct to be reconciled

---

gnucash/gnome/gnc-budget-view.c

I'm 99.99999999999999% sure this is now the correct fix for this bug.
* Restores budget-3.7 behaviour for current budgets.
* Restores budget-3.7 headings "Income/Expense/Transfer"
* Renames budget-3.7 heading "Total" to "Remaining"
* Fixes future budget behaviour.
I'll leave this here a couple weeks, maybe someone can independently confirm that 3.7 behaviour is restored.

Bug 797659 - Liabilities in budget report no longer calculate correctly

---

gnucash/gnome-utils/gnc-file.c
gnucash/gnome-utils/gnc-file.h
gnucash/gnome/window-reconcile.c
gnucash/gnome/window-reconcile.h
gnucash/gtkbuilder/dialog-import.glade
gnucash/import-export/import-main-matcher.c
gnucash/import-export/import-main-matcher.h
gnucash/import-export/ofx/gnc-ofx-import.c

This adds support for importing multiple OFX files in one shot. The one thing that might be objectionable to some is the change to gnc_file_dialog returning void* instead of char*. This is something that's done quite frequently in C and in gnucash in particular (in many callback functions etc), so I don't find it particularly objectionable.
If you guys object, I can add a GSList** parameter to gnc_file_dialog, and change all existing calls to send NULL.

Add ability to import multiple OFX files at one time

---

gnucash/price-quotes.scm
libgnucash/quotes/gnc-fq-dump.in

As mentioned in Bug 796993.
Note Finance::Quote will also give an err msg but it will only show when gnc-fq-dump is run with -v for a stock quote.
Christopher Lam has also contributed scheme code, which I have included here, to give an error message during Get Quotes processing in Price Database if a currency quote or a stock quote for source 'alphavantage' or 'vanguard' is detected and the API key is missing. No warning message is given from 'Get Quotes' for the 'multiple source' sources that include alphavantage (canada,nyse,nasdaq + usa) as one of the other sources may work. Unlike previously, if a missing api key is detected, no further sources will be processed. I don't think this will be a problem as it is easy to get an api key.

gnc-fq-dump Err msg if AlphaVantage API Key is needed but missing

---

gnucash/import-export/csv-imp/gnc-imp-settings-csv-price.cpp

Found in failed win maint nightlies.
Suggesstion by shaggy.
I am not sure about [un]conditional include.
[Edit] [IRC log](https://lists.gnucash.org/logs/2020/06/16.html#T20:52:51)

Add missing #include <algorithm> into gnc-imp-settings-csv-price.cpp

---

gnucash/report/reports/standard/budget-barchart.scm

Candidate replacement for `budget-barchart.scm` was accidentally reverted in ba5bd6b4d708fcc63604fc385b293a3ab6105a1a
* upgrade to html-chart
* replaces date selectors with period selectors

budget-barchart upgrade to html-chart

---

gnucash/report/report-utilities.scm
gnucash/report/test/test-report-utilities.scm

ensure the commodity-collector adds exact amounts instead of rounding during accumulation.

commodity-collector must not round

---

gnucash/import-export/ofx/gnc-ofx-import.c

The crash is caused by an uninitialized pointer in ofx_info.
This fixed it.

Bug 797825 - OFX import crashes on import of investment transaction

---

bindings/python/CMakeLists.txt
bindings/python/__init__.py
bindings/python/deprecation.py
bindings/python/example_scripts/account_analysis.py
bindings/python/example_scripts/gncinvoice_jinja.py
bindings/python/example_scripts/latex_invoices.py
bindings/python/example_scripts/new_book_with_opening_balances.py
bindings/python/example_scripts/rest-api/gnucash_rest.py
bindings/python/example_scripts/simple_book.py
bindings/python/example_scripts/simple_business_create.py
bindings/python/example_scripts/simple_invoice_insert.py
bindings/python/example_scripts/simple_session.py
bindings/python/example_scripts/simple_sqlite_create.py
bindings/python/example_scripts/simple_test.py
bindings/python/function_class.py
bindings/python/gnucash_core.py
bindings/python/tests/CMakeLists.txt
bindings/python/tests/runTests.py.in
bindings/python/tests/test_function_class.py
bindings/python/tests/test_session.py
libgnucash/engine/qofsession.h

https://github.com/Gnucash/gnucash/commit/6a1cb5eecd794d65ab0d15161b1628750b29acb6#diff-7692ab9d58b634e3cd67f41873697da5L34 introduced SessionOpenMode as parameters to qof_session_begin. This needs to be reflected in the python bindings. This is a preliminary patch. I'd like to keep the original usage but deprecate it.

Python bindings - adapt to use of sessionOpenMode in qof_session_begin

---

gnucash/gnome-utils/dialog-account.c
gnucash/gnome-utils/dialog-account.h
gnucash/gnome/window-reconcile.c
gnucash/gnome/window-reconcile2.c
gnucash/gtkbuilder/dialog-account.glade
gnucash/gtkbuilder/dialog-preferences.glade
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h

Bug 797854 - Global Register Preference to prompt for interest payment is not being honored.
A new per-account preference is added to let the user decide whether the interest transaction dialog should be
opened automatically before the reconcile. This preference is only enabled for certain types of accounts and
the code that decides that was moved to Account.h as is it now used in two separate place.

797854 global interest pay bug1

---

gnucash/import-export/import-backend.c
gnucash/import-export/import-backend.h
gnucash/import-export/import-main-matcher.c
gnucash/import-export/test/gtest-import-backend.cpp
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h
libgnucash/engine/AccountP.h
libgnucash/engine/mocks/gmock-Transaction.cpp
libgnucash/engine/mocks/gmock-Transaction.h

The previous ofx import code performed one query for each imported transaction, which
was quite slow. The change consists of gathering all ofx transactions before doing the
query. The query must be wider to search for all matching accounts (in case the imported
transactions come from different accounts) and an enlarged date range (according to the
earliest and latest imported transaction). The rest of the code is identical to what was
done before. The final query is performed just before the matching dialog is displayed.

Speeds up the import of ofx files by only doing one query at the end.

---

gnucash/import-export/import-main-matcher.c

I'm getting this error:
/home/user/src/gnucash/gnucash/import-export/import-main-matcher.c: In
function "gnc_gen_trans_list_show_all":
/home/user/src/gnucash/gnucash/import-export/import-main-matcher.c:1716:28:
error: "import_trans_account" may be used uninitialized in this
function [-Werror=maybe-uninitialized]
per_account_list = g_hash_table_lookup (lists_per_accounts,
import_trans_account);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/src/gnucash/gnucash/import-export/import-main-matcher.c:1676:14:
note: "import_trans_account" was declared here
Account *import_trans_account;
Looks like the variable name was incorrect.
`import_trans_account` is only initialized inside a previous loop and looks like an intra-loop variable.
cc @jeanlaroche @jralls

Variable name correction: "import_trans_account" --> "split_account"

---

gnucash/gnucash-cli.cpp
gnucash/gnucash-commands.cpp
gnucash/gnucash-commands.hpp

* file_to_load argument, if present, would be a candidate for loading.
* if loading fails, show report details anyway.
How to fix?
```
* 23:44:26 ERROR <gnc.engine> gnc_uri_get_components: assertion 'uri != NULL && strlen (uri) > 0' failed
* 23:44:26 ERROR <gnc.engine> gnc_uri_get_components: assertion 'uri != NULL && strlen (uri) > 0' failed
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

[gnucash-cli] -R show should accept & try load datafile

---

gnucash/gnome/business-urls.c

Preparation for [bug 797852](https://bugs.gnucash.org/show_bug.cgi?id=797852) is to make url query parsing less ugly. There's https://uriparser.github.io/doc/api/latest/ but we don't need its full capabilities. I *think* the hash-table is freed appropriately. Any additional `g_free` leads to double-free.
After this, the real bug fix is to encode aging-report end-date into string or number for the url, and decode it in business-urls.c to create owner report with custom end-date.

[business-urls] slightly better url query parsing

---

gnucash/gnome/business-urls.c
gnucash/gnome/dialog-invoice.c
gnucash/gnome/dialog-invoice.h
gnucash/report/html-utilities.scm
gnucash/report/report-utilities.scm
gnucash/report/reports/aging.scm
gnucash/report/reports/reports.scm
gnucash/report/reports/standard/new-aging.scm
gnucash/report/reports/standard/new-owner-report.scm

A few preliminary changes to enable `&enddate=NNN` in aging -> owner-report urls.
Then the final (contentious) change: aging-report was querying invoice's lot's balance to determine whether it is paid. It will now consider only invoice activity within the aging-report period specified.
I think the C code is clean, and the scm change is reasonable.

Aging-report must not consider splits outside report period

---

gnucash/gnome-utils/dialog-file-access.c
gnucash/gnome-utils/gnc-plugin-file-history.c
gnucash/gnome/dialog-print-check.c
gnucash/gnome/gnc-plugin-page-report.c
gnucash/report/reports/standard/balance-forecast.scm
gnucash/report/reports/standard/category-barchart.scm
gnucash/report/reports/standard/net-charts.scm
gnucash/report/reports/standard/test/test-transaction.scm
gnucash/report/trep-engine.scm

Main improvement is use  api `gnc_print_time64` which accepts time64 and date format string. Allows reports and other code to format time64 to string without saving/setting/restoring current QofDateFormat.
Also a few other C cleanups - gnc_prefs_get_string always returns a newly-allocated string which must be g_freed.

General progress

---

gnucash/gnome/gnc-plugin-page-register.c
gnucash/ui/gnc-plugin-page-register-ui.xml

Adds ability to jump to arbitrary date.
Finds first split whose posted date >= specified date, and jump to it.
Works best when the register is sorted by posted-date. Also works with other sorting, although it'll jump to the first split found whose posted_date >= specified_date. Not sure if we need to offer clear filter prompt.
@gjanssens

[gnc-plugin-page-register] Goto Date

---

po/gnucash-pot.cmake

I watched, the copyright holder of new po[t] files is currently set to:
`# Copyright (C) 2020 THE GnuCash'S COPYRIGHT HOLDER`
The commit would set it to "by the translators:"
because the individual (C) comments follow.
Should it stay 
- in this form or 
- be set in a variable,
-  - here or
-  -  more up in the hierarchy?
Older files have:
`Free Software Foundation, Inc.`: old default, OK for files from TP
`THE PACKAGE'S COPYRIGHT HOLDER`: Default, if no package is set
`Gnumatic, Inc.`: dissolved
`gnucash project`
`C-DAC, GIST, Pune, India`.: OK
`by the translators`
`by the respective translator`
Individuals
An interesting aspect from the gettext manual: The msgids were created by the programmers.

I18N: Add po copyright-holder

---

gnucash/gnome/assistant-loan.cpp
gnucash/gnucash-core-app.cpp
gnucash/gnucash.cpp
libgnucash/backend/xml/sixtp-utils.cpp
libgnucash/core-utils/gnc-filepath-utils.cpp
libgnucash/engine/Account.cpp
libgnucash/engine/qof-backend.cpp
libgnucash/engine/qofbook.cpp
libgnucash/engine/qoflog.cpp

When compiling with `-Werror`,  GNUCash fails to build due to various `error: missing sentinel in function call`.
This patch resolves the issue by passing the appropriate sentinels.

Fix warnings: missing sentinel in function calls

---

gnucash/gnome-utils/gnc-currency-edit.c

https://bugs.gnucash.org/show_bug.cgi?id=102787
This change allows GTK entry completion to take effect when a user types into the combo box.

Bug 102787: Currency selection should do autocompletion

---

gnucash/gnome-utils/gnc-file.c
gnucash/gnome/gnc-plugin-basic-commands.c
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h
libgnucash/engine/test/gtest-import-map.cpp

I was going to push this but decided to create a PR instead for comment.
This is a follow up to John's recent push which stops the imap convert to flat from running the same number of times equal to the number accounts in the list when there are no bayes KVP. With no bayes KVP entries the feature GNC_FEATURE_GUID_FLAT_BAYESIAN will never be set.
I think it is OK.

Bug797945 - Imap Changes

---

gnucash/gtkbuilder/dialog-account.glade

... because using the gtkcheckbutton's label makes the checkbutton much easier to click. I think there _are_ other disjointed GtkLabel&GtkCheckButtons around which could be merged.

Merge GtkCheckButton with GtkLabel

---

gnucash/gnome-utils/dialog-account.c
gnucash/gnome-utils/gnc-tree-view-account.c
gnucash/gnome/dialog-find-account.c
gnucash/gnome/gnc-plugin-page-account-tree.c
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h
libgnucash/engine/gncOwner.c
libgnucash/engine/test/utest-Invoice.c

I'll put forward the claim that xaccAccountCountSplits is poorly used; the exact number of splits is hardly useful and the information desired can be gleaned much more effectively using `xaccAccountGetSplitList` or `gnc_account_and_descendants_empty`, a new method. I'd hope these commits are self explanatory and will be welcome.

Maint deprecate xacc account count splits

---

gnucash/report/html-chart.scm
gnucash/report/reports/standard/budget-barchart.scm

Previously, every reload caused the chart to move through an animation, which
prevented visual comparison of state before and after reload.

Disable initial report animation

---

gnucash/gnome/top-level.c
gnucash/report/html-utilities.scm
gnucash/report/report.scm
gnucash/report/reports/standard/new-owner-report.scm
libgnucash/app-utils/options.scm

Partial PR. Handle `invoice-doclink-guid=` links. This PR currently sends doclink URI in URL; it should send invoice GUID, and `top-level.c` would retrieve gncInvoice from GUID. Not sure how to do this. @Bob-IT ?
Not sure whether to add doclink as a separate column, or linkify the "Invoice" in the Type column.
Also "Display/Document Links" will now clash with "Display/Links" option.
Progress so far:

Owner-Report can display business document links

---

gnucash/gnome/gnc-plugin-page-account-tree.c
gnucash/gnome/gnc-plugin-page-register.c
libgnucash/engine/Scrub.c
libgnucash/engine/Scrub.h
libgnucash/engine/ScrubBusiness.c

This PR is as a result of looking at PR #784 for gnc_resume_gui_refresh balance.
After testing and making some changes I felt it was easier to make a new PR than add comments to PR #784 
@christopherlam  These are the changes I would make along with a bug fix that was in the same area, what do you think. This does not include the tool tips for dates.

Scrubbing follow up

---

gnucash/gnome/window-autoclear.c
libgnucash/app-utils/gnc-ui-balances.c
libgnucash/app-utils/gnc-ui-balances.h

Offshoot from #797  
@cristiklein a few optimisations -- please confirm the reasoning is acceptable:
1. If `end_value` == `cleared_balance` then there's no need to autoclear. Abort.
2. If too many ~uncleared splits (20?)~ reachable amounts (>1,000,000) then it'll lag. Abort.
3. ~If the sum a subset of uncleared splits amounts to zero, then the knapsack will always fail to find unique solution. Abort.~ - removed -- if split amounts are $1.00, $2.00 and -$3.00, a unique solution exists whereby target amount is $2.00
4. Select GtkEntry initially and when aborted to make modification easier.

Maint 608436

---

libgnucash/engine/iso-4217-currencies.xml

"Haléřů" is plural genetive, "Haléř" is singular nominative. 
https://cs.wikipedia.org/wiki/Hal%C3%A9%C5%99

Fix CZK currency partname to nominative singular

---

bindings/core-utils.i
bindings/guile/core-utils.scm
gnucash/report/html-utilities.scm
po/gnucash-pot.cmake

... but doesn't work. This should show "Exchange rates" when `entries > 1`

Use ngettext

---

gnucash/gnome/window-autoclear.c

@cristiklein @mtalexander 
Further refinement: if a valid `end_amount` is being written, the dialog will actually demonstrate the splits to be cleared. Every change to gnc_amount_edit calls `gnc_account_get_autoclear_splits` which must terminate in a reasonable time and I'm now confident it will terminate <1s due to the failsafe if num(reachable_amounts) exceeds 10^6. This feature renders the display of newly-cleared splits in a new register obsolete, but I'd leave it because the user may wish to review them afterwards.

[auto-clear] provide live feedback when a valid end_amount is input

---

gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome-utils/gnc-main-window.h
gnucash/gnome/gnc-plugin-page-report.c
gnucash/gschemas/org.gnucash.warnings.gschema.xml.in
gnucash/html/gnc-html.c
gnucash/html/gnc-html.h

This has stemmed from Bug 797982 which causes Gnucash to sometimes crash when changing books when using 'File->Open' from the first book and there are open report pages. @jralls traced this down to the use of the g_idle_add to load the reports.
To fix this I have done away with the g_idle_add and the reports now load when the page has focus. To achieve this a flag is set at the start of the restoring window pages and reset at the end which is tested on report page focus. This has the benefit of reducing the load time if the last open page is not a report page BUT when you switch to a report page you will need to wait for the report to be rendered.
While looking at this I noticed that the page focus was focusing on the scroll window and not the Webkit webview so changed that which led to …

Reports page changes

---

gnucash/ui/gnc-plugin-page-register-ui.xml
gnucash/ui/gnc-plugin-page-register2-ui.xml
libgnucash/app-utils/test/CMakeLists.txt
libgnucash/app-utils/test/test-autoclear.cpp

Hi @christopherlam,
Please find here a first draft of the autoclear tests. Unfortunately, right now the tests fail. The reason is that the test cases include two splits of the same amount. This leads to "Cannot uniquely clear splits. Found multiple possibilities.". This is a limitation of the current algorithm. It could be smarter and suggest a list of splits to clear when none or both of the two splits are included.
How should we proceed?
1. Accept the limitations of the algorithm and simplify the tests accordingly.
2. Improve the algorithm so it can deal with trickier cases.
Let me know what you think.

Auto clear tests

---

gnucash/register/register-gnome/gnucash-header.c
gnucash/register/register-gnome/gnucash-header.h
gnucash/register/register-gnome/gnucash-sheet-private.c
gnucash/register/register-gnome/gnucash-sheet.c
gnucash/register/register-gnome/gnucash-sheet.h
gnucash/register/register-gnome/gnucash-sheetP.h

If the horizontal scrollbar is present for a register and you start to tab from one cell to the next one which is not in view the sheet does not scroll to keep the active cell in view.
This commit fixes that by getting the active cell horizontal offset and width and comparing it to the sheet width and window width.
I think it is all OK and does what I think it should with testing on my Linux VM and also Windows 10.
Just thought I would park this here for any comments before pushing at the weekend.

Bug644242 - Register Panning

---

gnucash/gnome-utils/gnc-file.c

I thought I would add this here for any comment, this PR changes the 'Create New File' option on the said dialog to 'Open with No File'.
I think this is a better choice as it bring up the main GnuCash window and allows you to do 'File->New' which is the equivalent to current option, 'File->Open' so you can choose a different file or use one from the history.
If there are no concerns I will push this next week.

Bug309943 - When unable to obtain a lock, no option to open another file

---

gnucash/report/test/test-report-utilities.scm

Use unique split amounts to when testing `gnc:account-accumulate-at-dates`. The 2nd commit uncomments the 4th transaction in bank1. 
https://github.com/Gnucash/gnucash/pull/831#issuecomment-739575308 - I don't understand what you meant by "only 3 transactions can be added" - with this 4th transaction, the accumulated balance must be changed, as expected, to add 40.
Still passes on guile-2.2 and guile-3.0. This branch could be merged prior to #831

Improve test-report-utilities.scm

---

gnucash/gnome-search/dialog-search.c
gnucash/gnome-utils/dialog-account.c
gnucash/gnome-utils/dialog-book-close.c
gnucash/gnome-utils/dialog-commodity.c
gnucash/gnome-utils/dialog-commodity.h
gnucash/gnome-utils/dialog-file-access.c
gnucash/gnome-utils/dialog-preferences.c
gnucash/gnome-utils/gnc-gnome-utils.c
gnucash/gnome-utils/gnc-gnome-utils.h
gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome-utils/gnc-ui.h
gnucash/gnome/dialog-custom-report.c
gnucash/gnome/dialog-customer.c
gnucash/gnome/dialog-employee.c
gnucash/gnome/dialog-invoice.c
gnucash/gnome/dialog-job.c
gnucash/gnome/dialog-new-user.c
gnucash/gnome/dialog-order.c
gnucash/gnome/dialog-print-check.c
gnucash/gnome/dialog-sx-editor.c
gnucash/gnome/dialog-sx-editor2.c
gnucash/gnome/dialog-vendor.c
gnucash/gnome/gnc-plugin-report-system.c
gnucash/gnome/window-reconcile.c
gnucash/gnome/window-reconcile2.c
gnucash/import-export/bi-import/dialog-bi-import-gui.c
gnucash/import-export/customer-import/dialog-customer-import-gui.c

I am unsure about this one, I was looking at the bug and the context help was not working. I do not know how long it has not been working but hopefully not from the report date.
From testing, when pressing the help button, the following uri is created for the new account help button...
'ghelp:gnucash-help?acct-create' and used to open the gnome help app.
This segfaults in yelp at the '?' as 'ghelp:gnucash-help' does work.
To prove try at a command prompt...
gnome-help ghelp:gnucash-help?acct-create which segfaults but this...
gnome-help ghelp:/usr/share/gnome/help/gnucash-help/C/gnucash-help.xml?acct-create works.
To fix this, I have changed the context help to use the full path to the help files.
Looking at this I think I should add a test for getting a valid path and maybe an error …

Bug 128772 - Account Help Button does not work

---

gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome-utils/gnc-main-window.h
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-split-reg.c
gnucash/gnome/gnc-split-reg2.c
gnucash/register/register-gnome/gnucash-sheet-private.c
gnucash/register/register-gnome/gnucash-sheetP.h

Hopefully straight forward bug.
The first commit adds the account name to the read only warning dialog so when you start Gnucash with a read only register open you can tell which register the dialog refers to.
The second commit adds a test for the register being read only so that the same actions disabled for a read only book can be applied.
As part of the bug report, there was a request for some indication that a register is read only. The second commit my well of fulfilled that by disabling the menu actions but was wondering if more is required. One simple idea would be to augment the title with some text as this changes for each register tab, another idea was maybe to change the account icon to a padlock, slightly more involved but doable.
I will push this next weekend if no further …

Bug355496 - Read Only Registers

---

gnucash/report/reports/standard/balsheet-pnl.scm
gnucash/report/reports/standard/test/test-balsheet-pnl.scm

because most-recent-first is standard

[balsheet-pnl] show most recent period first by default

---

gnucash/import-export/aqb/gnc-flicker-gui.c

I think this is correct but do not like changing stuff I can not test.
@jralls Do these changes look correct ?
Change flicker_data to return a guint so that the char code can be
freed in the function which also removes the need to use g_malloc0
twice.

Free the char 'code' after g_malloc0 in gnc-flicker-gui.c

---

gnucash/gnome/gnc-plugin-report-system.c
gnucash/gnucash-commands.cpp
gnucash/report/gnc-report.c
gnucash/report/gnc-report.h
gnucash/report/report-core.scm
libgnucash/app-utils/c-interface.scm

1. To avoid using the global var `gnc:last-captured-error`, this branch will augment some C functions and handle error by passing a parameter to receive the captured error.
2. ~Also `gnc_set_busy_cursor` is currently disabled -- they seem to belong to `gnc-ui.h` but importing the latter doesn't work.~ (fixed)

Don't use gnc:last-captured-error

---

data/accounts/da/acctchrt_car.gnucash-xea
data/accounts/da/acctchrt_common.gnucash-xea
data/accounts/da/acctchrt_homeloan.gnucash-xea
data/accounts/da/acctchrt_homeown.gnucash-xea

Most of these, like "Udgifter", correspond directly to directly to en_GB
equivalents, like "Expenses". However, unlike in the en_GB version, the parent
accounts in the Danish templates are not marked as placeholders.
I have used my own judgement in a few cases where there was no direct equivalent
in the en_GB templates.
This was also discussed on the gnucash mailing list: https://lists.gnucash.org/pipermail/gnucash-user/2021-January/094762.html (and replies).

Mark most parent accounts as placeholders in Danish templates

---

data/accounts/da/acctchrt_common.gnucash-xea

There have not been any "Amt" in Denmark since 2007. The new name is "Region".

Rename "Amt" to "Region" in Danish template

---

libgnucash/quotes/gnc-fq-dump.in

I've did a small bash script that retrieve the sources from gnc-fq-dump and try to find one source that has the specific stock. At that point I've noticed that the sources returned by Finance::Quote have always a different order. Just wondering if it is done in that way intentionally (?)

sorting sources

---

gnucash/import-export/qif-imp/qif-file.scm

Quicken 2005 introduces U amount which sometimes differs from T amount. U amount has larger range, and must override T amount whenever they're not equal.
Example log output:
```
* 21:57:17  WARN <gnc.scm> qif-split has ambiguous amounts. T-21449672.96 U21,500,000.00. using U amount.
* 21:57:17  WARN <gnc.scm> qif-split has ambiguous amounts. T-20949672.96 U22,000,000.00. using U amount.
* 21:57:17  WARN <gnc.scm> qif-split has ambiguous amounts. T-21469672.96 U21,480,000.00. using U amount.
* 21:57:17  WARN <gnc.scm> qif-split has ambiguous amounts. T-21474672.96 U21,475,000.00. using U amount.
* 21:57:17  WARN <gnc.scm> qif-split has ambiguous amounts. T-21474772.96 U21,474,900.00. using U amount.
* 21:57:17  WARN <gnc.scm> qif-split has ambiguous amounts. T-21474822.96 U21,474,850.00. …
```

Bug 798085 - Incorrect transactions import of deposit with large number amount

---

gnucash/gnome-utils/gnc-recurrence.c
gnucash/gnome-utils/gnc-sx-instance-dense-cal-adapter.c
gnucash/gnome-utils/gnc-tree-model-split-reg.c
gnucash/gnome-utils/gnc-tree-view-account.c
gnucash/gnome-utils/window-main-summarybar.c
gnucash/gnome/assistant-loan.cpp
gnucash/gnome/dialog-imap-editor.c
gnucash/gnome/dialog-lot-viewer.c
gnucash/gnome/gnc-budget-view.c
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-plugin-page-register2.c
libgnucash/app-utils/gnc-sx-instance-model.c
libgnucash/core-utils/gnc-glib-utils.c
libgnucash/engine/SX-book.c
libgnucash/engine/ScrubBusiness.c
libgnucash/engine/Split.c
libgnucash/engine/Split.h
libgnucash/engine/Transaction.c
libgnucash/engine/gncCustomer.c

* mainly prepend&reverse instead of appending lists.
* introduces `xaccSplitListGetUniqueTransactionsReversed` -- assists in buildling splitlist, seems only used for Register2. This commit removes O(N^2) which should speed it up.

Several optimisations

---

gnucash/register/register-gnome/gnucash-style.c
libgnucash/app-utils/gnc-ui-balances.c
libgnucash/engine/SchedXaction.c

GLib is deprecating g_memdup. Since older versions of GLib wouldn't have g_memdup2, this PR replaces occurrences of g_memdup by memcpy.

Replace g_memdup by memcpy

---

gnucash/gnome/gnc-plugin-page-budget.c
gnucash/gnome/gnc-plugin-page-report.c
gnucash/gnome/gnc-plugin-page-report.h
gnucash/report/reports/reports.scm
gnucash/ui/gnc-plugin-page-budget-ui.xml

This parallels the invoice editor "Print Invoice" functionality. Runs the budget report using current budget.

From Budget editor, add toolbar and Edit menu to run budget report

---

gnucash/gnome/dialog-invoice.c

Adds linkage from editor to report similar to #930.
Similar to 9f4ba17d8 -- from invoice editor, click Print Invoice to create invoice report. This saves link to invoice, and reuses the report tab if Print Invoice is clicked again.

[dialog-invoice] invoice editor reuses invoice report tab

---

gnucash/CMakeLists.txt
gnucash/gnucash-core-app.cpp
gnucash/gnucash-locale-macos.mm
gnucash/gnucash-locale-platform.h
gnucash/gnucash-locale-windows.c
po/POTFILES.in

- Move Macos specific bits to its own source file. As this is objective-c use .mm extension
- Use common function signature for Macos and Windows init function and include via common header file
The only functional change is that the platform  specific functions now return a `char  *` where before the Windows function was passed a writable parameter and the MacOS function didn't have any means to return a value. It should otherwise behave exactly as before the change. More changes may follow based on discussion on the mailing list.
@jralls can you provide feedback on whether or not this will build on MacOS ? I have found the typical extension for objective-c is .m or .mm, but I wasn't sure which one would fit here. I have also made a few minor tweaks (adding a common header/set a return …

Restructure early locale initialization

---

bindings/python/time64.i

After a recent commit (a11065b823f14fbc32bb1fc132304e36f486c8b0) the python bindings have become exceedingly chatty. I rather remove this debug info than trying to make it optional as it seems a bit too complicated to me to achieve this. I suppose this has been used only for the work on @jralls commit and removing it is ok, John?

remove debug information for time conversion

---

bindings/python/example_scripts/export_account_totals.py

>>> nominator='123456'
A digit is missing in the string returned from to_string_with_decimal_point_placed. The -1 error.
>>> point_place=2
>>> nominator[:-point_place - 1], nominator[-point_place:]
('123', '56')

Fix to_string_with_decimal_point_placed

---

bindings/python/deprecation.py
bindings/python/gnucash_core.py
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h
libgnucash/engine/gnc-pricedb.c
libgnucash/engine/gnc-pricedb.h
libgnucash/engine/test/utest-gnc-pricedb.c

I am not sure about this so would like a second opinion...
This is to do with when a security on the Chart of Accounts uses column 'Present(xxx)' and uses a price entered into the pricedb which is in the future to calculate the balance. I am not sure whether having prices in the future is OK, certainly one could do it by error.
It all starts from gnc-tree-model-account.c and the value returned from xaccAccountGetPresentBalanceInCurrency which used a recursive function that had no date parameter. Changing that to use a version with a date parameter lead to a function that did not use the date so that needed changing also.
If the future price was way off, then this may of been OK but the bug report was for a day or two and hence the report.
To fix this I added a function, …

Bug798148 - Accounts page Present (XXX) column uses future prices

---

libgnucash/engine/gnc-pricedb.c

Fix the compilation error on gcc 10:
gnucash/libgnucash/engine/gnc-pricedb.c: In function âextract_common_pricesâ:
gnucash/libgnucash/engine/gnc-pricedb.c:2469:40: error:
to_price may be used uninitialized in this function [-Werror=maybe-uninitialized]
2469 |     if (from_price == NULL || to_price == NULL)
|                                        ^
gnucash/libgnucash/engine/gnc-pricedb.c:2469:20:
error: âfrom_priceâ may be used uninitialized in this
function [-Werror=maybe-uninitialized]
2469 |     if (from_price == NULL || to_price == NULL)
|                    ^

from_price and to_price may be uninitialized in extract_comon_prices

---

libgnucash/engine/Account.cpp
libgnucash/engine/Account.h
libgnucash/engine/Scrub.c

Reverts ed486a5 as that was based on seriously misunderstanding what was going on.
0f8d9f6 changes the way trading accounts are found from looking at their names and ignoring account types to looking for account-types and commodities and ignoring names in order to fix [Bug 798093](https://bugs.gnucash.org/show_bug.cgi?id=798093) with the added (supposed) advantage of allowing the top level trading account to have any name.
Sadly I overlooked a key issue in that commit: The top-level trading account and any placeholders were created with the transaction currency of the transaction that caused them to be created. The new logic wouldn't find the existing ones if the current transaction has a different currency, so it would make a new hierarchy.
This PR changes in two ways: When looking for …

Revist Bug798093

---

gnucash/gnome-utils/dialog-account.c

@jralls wrote at #820
>In gnc_account_opening_balance_button_update the account-type test should be on aw->type rather than xaccAccountGetType so that it reflects the state of the dialog rather than the account type before the dialog started.
Fix for #762

Fix for opening balance account support

---

po/zh_TW.po

This translation file hasn't been maintained for years. It contains lots of useless / misleading comments or fuzzy entry left by msgmerge, and lots of file reference does not match the latest code base.
This makes it hard to translate both on Weblate, or use desktop program like PoEdit after download the po file from Weblate. 
I've updated and merge it with latest .pot template generated from latest source code in `maint` branch.
I've also tried upload it to Weblate directly, but apparently it won't delete those garbage comment and won't add msgid that didn't exist in the current po file.

Cleanup and update zh_TW.po to match current codebase.

---

gnucash/gnome-search/search-double.c
gnucash/gnome-search/search-int64.c
gnucash/gnome-search/search-numeric.c
gnucash/gnome-utils/dialog-account.c
gnucash/gnome-utils/dialog-tax-table.c
gnucash/gnome-utils/dialog-transfer.c
gnucash/gnome-utils/gnc-amount-edit.c
gnucash/gnome-utils/gnc-amount-edit.h
gnucash/gnome/assistant-loan.cpp
gnucash/gnome/assistant-stock-split.c
gnucash/gnome/dialog-customer.c
gnucash/gnome/dialog-employee.c
gnucash/gnome/dialog-fincalc.c
gnucash/gnome/dialog-invoice.c
gnucash/gnome/dialog-job.c
gnucash/gnome/dialog-payment.c
gnucash/gnome/dialog-price-editor.c
gnucash/gnome/window-autoclear.c
gnucash/gnome/window-reconcile.c
gnucash/gnome/window-reconcile2.c
gnucash/gtkbuilder/dialog-fincalc.glade
gnucash/register/ledger-core/split-register-load.c
gnucash/register/register-core/basiccell.c
gnucash/register/register-core/basiccell.h
gnucash/register/register-core/formulacell.c
gnucash/register/register-core/pricecell.c
gnucash/register/register-gnome/gnucash-item-edit.c
libgnucash/app-utils/gnc-ui-util.c
libgnucash/app-utils/gnc-ui-util.h

I was looking at Bug 798157 which maybe should be marked as a duplicate of Bug 796761
They are both partly dealing with control characters being pasted in to register fields so thought I would try and filter them out and came up with this. This basically gets the text from the clipboard when requested, filters it and sends it back to the clipboard before the gnc_item_edit does the paste thus leaving the GtkEditable to deal with the insertion. Control characters are stripped from the beginning and end of text with a space replacing them in the middle of text.
As far as I can tell it seems to do the job but as usual I may of overlooked some aspect.

Bug 796761 - Control characters can be pasted in register fields

---

gnucash/gnome-utils/dialog-preferences.c
gnucash/gschemas/org.gnucash.dialogs.import.generic.gschema.xml.in
gnucash/gtkbuilder/dialog-preferences.glade
gnucash/import-export/import-backend.c
gnucash/import-export/import-backend.h
gnucash/import-export/import-main-matcher.c
gnucash/import-export/import-settings.c
gnucash/import-export/import-settings.h
gnucash/import-export/import-utilities.h

In the import-backend.c source file two constants were defined with a
comment about they should ideally be added to the user preference
dialog. This commit does that, the two preferences are
match-date-threshold which is the number of days a transaction match is
likely and match-date-not-threshold which is the number of days a
transaction match is considered not likely.

Add two new preferences for import for PR #935

---

bindings/python/gnucash_core.py

Fix a variable name typo in Python binding gnc_pricedb_lookup_latest_before_t64

---

gnucash/html/gnc-html-webkit2.c

Because GValue was unset earlier in this function, the `default_font_family` would point to garbage. We need to unset the GValue after the `default_font_family` is used to set the GObject, thereby avoiding a valgrind complaint about accessing unallocated memory.
```
==147251== Invalid read of size 8
==147251==    at 0x4849ECD: memcpy@GLIBC_2.2.5 (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==147251==    by 0x4C60951: g_strdup (in /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6800.0)
==147251==    by 0x5A13194: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6800.0)
==147251==    by 0x5A049EB: g_object_set_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6800.0)
==147251==    by 0x5A04CD3: g_object_set (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.6800.0) …
```

GValue: don't unset until the boxed pointer isn't used anymore

---

gnucash/gnome-utils/dialog-account.c

commodity_changed_cb(): Prevent a signal slot loop in  when recognizing multiple opening balance accounts

---

po/de.po

It had the opposite meaning of what was intended.

Fix German translation for transaction filter case sensitivity

---

gnucash/report/reports/standard/advanced-portfolio.scm
gnucash/report/reports/standard/portfolio.scm

I've got some fractional shares to 8 decimal places.

Support displaying 9 share digits in the portfolio reports

---

gnucash/register/ledger-core/split-register-copy-ops.c
gnucash/register/ledger-core/split-register-copy-ops.h
gnucash/register/ledger-core/split-register.c
gnucash/register/ledger-core/test/utest-split-register-copy-ops.c

Copied strings may be removed from the string cache while they're in the FloatingTxn/FloatingSplit so take a new reference to them.
Fix memory leaks of FloatingTxn and FloatingSplit when they're used temporarily.
Fix memory leak in FloatingTxn by freeing the m_splits list too.

Bug 798234 - Use string cache in FloatingTxn and FloatingSplit

---

bindings/engine.i
gnucash/gnome-utils/gnc-tree-model-owner.c
gnucash/report/gnc-report.c

Continuation of #1029 from valgrind.
`owner_list` is populated with `gncBusinessGetOwnerList` which calls `get_ownerlist_cb` which calls `gncOwnerNew`, and must be freed with `gncOwnerFree`.

More memory leaks

---

libgnucash/backend/xml/test/test-load-xml2.cpp

If qof_session_new() is called without a book then qof_session_load() won't do anything.
Set up a book for it to use.

Load test data from XML properly

---

libgnucash/backend/xml/io-gncxml-v2.cpp
libgnucash/backend/xml/test/test-load-xml2.cpp

The root accounts start with a non-zero editlevel because BeginEdit is called for them during loading but not committed after loading.
If the book is then closed without performing any further edits that would require a commit, the Account book_end process does nothing because the root account is still being edited and so none of the accounts are freed.

Commit root accounts after loading from XML

---

libgnucash/engine/Split.c
libgnucash/engine/Transaction.c

When g_object_new() is used, the strings that default to "" are added to the string cache. These are then not correctly removed when updating them with new values when cloning a Transaction/Split.
Use CACHE_REPLACE instead of CACHE_INSERT.

Avoid leaking string cache entries for "" in Transaction and Split

---

gnucash/gnome-utils/gnc-component-manager.c
libgnucash/engine/Account.cpp
libgnucash/engine/AccountP.h
libgnucash/engine/Split.c
libgnucash/engine/SplitP.h
libgnucash/engine/Transaction.c
libgnucash/engine/TransactionP.h
libgnucash/engine/gnc-budget.c
libgnucash/engine/gnc-commodity.c
libgnucash/engine/gnc-pricedb-p.h
libgnucash/engine/gnc-pricedb.c
libgnucash/engine/gncAddress.c
libgnucash/engine/gncBillTerm.c
libgnucash/engine/gncCustomer.c
libgnucash/engine/gncEmployee.c
libgnucash/engine/gncEntry.c
libgnucash/engine/gncInvoice.c
libgnucash/engine/gncJob.c
libgnucash/engine/gncOrder.c
libgnucash/engine/gncTaxTable.c
libgnucash/engine/gncVendor.c
libgnucash/engine/kvp-frame.cpp
libgnucash/engine/qof-string-cache.cpp
libgnucash/engine/qof-string-cache.h
libgnucash/engine/qofbook.cpp
libgnucash/engine/test/test-qof-string-cache.c
libgnucash/engine/test/utest-Account.cpp
libgnucash/engine/test/utest-Split.cpp
libgnucash/engine/test/utest-Transaction.cpp

This is a prerequisite for being able to return "" (which is const) and none of the returned values should ever be modified.
Avoid unnecessary reference counting for uses of the empty string.

Make string cache values const and don't reference count empty strings

---

gnucash/gnome-utils/dialog-commodity.c

When creating a new commodity the display symbol isn't saved so it defaults to one of the other values as appropriate.
After creating the new commodity (without providing a user symbol), set the user symbol.

Bug 798238 - "New security" dialog doesn't save the "Display symbol"

---

libgnucash/engine/qofinstance.cpp

If QofInstancePrivate has no collection then qof_instance_dispose() returns without completing the rest of its dispose processes.
Change the check for a collection so that it only affects the call to qof_collection_remove_entity().

qof_instance_dispose should remove its type string from the string cache

---

bindings/engine.i
borrowed/goffice/go-optionmenu.c
gnucash/gnome-search/dialog-search.c
gnucash/gnome-utils/dialog-options.c
gnucash/gnome-utils/gnc-amount-edit.c
gnucash/gnome-utils/gnc-main-window.c

More valgrind leaks... continuation of #1107 
because `gtk_container_get_children` always returns a new GList* and they were not consistently freed after use.

Maint leaks

---

bindings/guile/test/srfi64-extras.scm

From my understanding:
1. a change [1] in guile 3.0.7 includes an upstream srfi-64 bugfix[2] regarding test-end
2. this means in guile-3.0.7 onwards test-end does not return whether the num-failures is zero as written [3] see test-balsheet-pnl.scm currently
3. this means the test-runner in srfi64-extras.scm and tests need to be modified similarly to https://github.com/aconchillo/guile-json/pull/73 to allow failures to be detected by `ninja check` when guile is 3.0.7 or later.
4. edit -- may need to copy https://github.com/aconchillo/guile-json/pull/74/ too
[1] https://git.savannah.gnu.org/cgit/guile.git/commit/?id=de5d1a7f99b8e952b115237ebc29633062f99bb9
[2] https://github.com/scheme-requests-for-implementation/srfi-64/commit/7cf4c010398850b45f5a6939bb73f747605a0513
[3] current code …

srfi-64 in guile was fixed causing failing tests to not report failure properly

---

libgnucash/engine/Account.cpp
libgnucash/engine/gnc-lot.c
libgnucash/engine/test/test-commodities.cpp
libgnucash/engine/test/test-lots.cpp
libgnucash/engine/test/utest-Account.cpp
libgnucash/engine/test/utest-Invoice.c
libgnucash/engine/test/utest-Transaction.cpp

- init struct members properly to `is_unset` and `TriState::Unset`
- test acct kvp "equity-type" for "opening-balance" instead of "true"
- fixes gnc-lot.c struct setters
- unit test all of #1117 setters/getters. note it tests getting/setting and doesn't test kvp backend.

[account.cpp] fix bugs in #1117

---

gnucash/import-export/import-backend.c
gnucash/import-export/import-backend.h
gnucash/import-export/import-main-matcher.c
gnucash/import-export/import-utilities.c
gnucash/import-export/import-utilities.h
libgnucash/engine/mocks/gmock-Account.cpp
libgnucash/engine/mocks/gmock-Account.h

Reverted the change be6fb1abe that entirely removed the check for online_id in existing registry transactions. Added code to ensure that during the import of a transaction, splits in register transactions that have the same FITID are only ignored if the split in question corresponds to the account into which the transaction is imported.
This re-instate the behavior prior to be6fb1abe which allowed us to re-import the same file twice in a row with the second time showing no transactions to import. It also fixes bug 798298 in cases where the online_id of an imported transaction exists in the split of a register transaction, but corresponds to a different account (there no guarantee that FITID are unique from bank to bank).
What this does not fix is non-compliant OFX files in which FITIDs …

798298 reimport ofx

---

gnucash/import-export/ofx/gnc-ofx-import.c

To solve the issue in this bug, I'm processing the transactions in the ofx file per account, instead of all at once. This means that the matcher dialog is re-run for each account that's present in the ofx file (instead of once with all transactions for all accounts).
With this, the second transfer transaction in the OFX file is recognized as the other side of the transfer, and becomes a match.
One thing I had to change was to connect to "destroy" instead of "response" in the match dialog for the callback that continues processing (either with reconciling, processing transactions for the second account, or processing the next ofx file). This was needed because the imported transactions had to be recorded into the register before processing the ones corresponding to the second account, for …

Add code to handle ofx files that include transfers between accounts

---

gnucash/gnome/window-reconcile.c

The 2nd and subsequent times Statement Date is updated, the Ending Balance
was not recalculated. This was because at end of gnc_start_recn_date_changed(),
gnc_start_recn_update_cb() was called when it should not have been.
This caused the user_set_value flag to be set True (indicating statement
end amount was manually entered - which it wasn't) after the date is
changed. This causes the ending balance to NOT be recalculated when the
end date is subsequently changed.

Bug 798235 Reconciliation Ending Balance not recalculated

---

libgnucash/engine/Account.cpp
libgnucash/engine/Account.h
libgnucash/engine/AccountP.h
libgnucash/engine/test/utest-Account.cpp

After this, the only remaining GValue string leaks in account.cpp are `dxaccAccountGetQuoteTZ` and `dxaccAccountGetPriceSrc`.  To plug them would require adding more member in the `AccountPrivate` struct, which does not seem worthwhile.
tests done in 15852031d and a5d101d and 7a878e88cef08857450da2842dbe37e6d1d2d242

more GValue string leaks plugged

---

gnucash/report/reports/standard/reconcile-report.scm
gnucash/report/trep-engine.scm

* Transaction Report upgrade - can select the date to be used for date filter. Defaults to posted date.
* Transaction Report can still filter with a different date e.g. payment date, by a derived report via the `#:split->date` argument.
* Reconcile Report gains ability to filter by Posted Date, which IMHO shouldn't have been changed in the first place.

Transaction Report and Reconciled Report, and filtering by Posted/Reconciled/Entered/other dates.

---

gnucash/gtkbuilder/dialog-import.glade
gnucash/import-export/import-backend.c
gnucash/import-export/import-backend.h
gnucash/import-export/import-main-matcher.c
gnucash/import-export/import-main-matcher.h
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h

Add an "Append" checkbox to the bottom of the "Generic import transaction
matcher" window to the left of the "Reconcile after match" checkbox.
When ticked, this causes the imported Description/Notes to be appended
to the matched transaction Description/Notes respectively.
The selected ticked/unticked state of the "Append" checkbox is saved in
a key value pair for the import account, so the next import for that
account will automatically default it to the saved state.
As these mods are limited to the code for the matcher window, this should
work for all the imports that use it - ie ofx & csv file imports (both
tested) & aqbanking (I cannot test).
Can some-one please test aqbanking?
If this gets merged, I'll see if I can also do this for QIF import, and update the documentation.

Bug797678 OFX import should append not replace, existing Notes & Desc

---

libgnucash/app-utils/options.scm

Offshoot from #1191 
To reproduce bug:
- create budget
- create budget report, select it, run successfully
- delete budget
- reload budget report.
Result: segfault.
This fix stores guid instead of budget object, so, lookup a deleted guid returns null as it should. I haven't tested all combinations of saved-reports, gcm reports etc. But I'm sure it's safe.

[options.scm] gnc:make-budget-option stores guid instead of object

---

bindings/core-utils.i
gnucash/report/html-chart.scm
gnucash/report/html-utilities.scm
gnucash/report/test/test-html-utilities-srfi64.scm

using a guile's uri.scm sanitizing function with expanded charset.
More test cases are available from https://github.com/Sporkmonger/Addressable/blob/master/spec/addressable/uri_spec.rb

Bug 798392 - Reports do not display when Reports JavaScript dependencies are located at a filepath that includes special characters like hash ("#")

---

gnucash/gnome/window-reconcile.c

Reconciliation can be sped up tremendously by postponing all account
balance recalc when modifying splits' reconcile flags.
test: 
* open a large account.
* reconcile, finalize
* notice this is slow
by postponing account balance recalc until all splits' reconcile flags are set, we can speed this up tremendously.

[window-reconcile] speed up by postponing account balance recalc

---

gnucash/import-export/import-main-matcher.c

Bug 798395 ofxdirectconnect downloads crash gnucash 4.9
Add a check of temp_trans_list to avoid dereferencing a NULL pointer when there
are no transactions to match. Add a dialog to alert the user.

Bug 798395 ofxdirectconnect downloads crash gnucash 4.9

---

gnucash/gnome/gnc-budget-view.c

gbv_get_accumulated_budget_amount returns a numeric, signed for DISPLAY and must be converted to unreversed before adding to info->total.
@miklcct should test this issue is fixed. Please test budgets existing in several account levels too.

Bug 798408 - The calculation in budgets UI and reports are wrong.

---

gnucash/import-export/ofx/gnc-ofx-import.c

With some OFX_INCOME or OFX_REINVEST transactions, the FITID field was not always being set.

Bug 798391 OFX import routine keeps prompting for accepted

---

gnucash/gnome/gnc-plugin-page-budget.c

@miklcct for https://bugs.gnucash.org/show_bug.cgi?id=798407 would you be able to verify this speeds up estimate/allperiods? I do not have access to a mysql server.

[gnc-plugin-page-budget] estimate/allperiods wrap begin/commit pair

---

po/nl.po

In Dutch it is weird to say "Sales Invoice Number", instead you use
"Invoice Number". Also, the old value messed up the PDF layout because
it was so long.
5345 translated messages, 29 fuzzy translations, 6 untranslated messages.

L10N:nl: Better Invoice Number translation

---

libgnucash/engine/Split.c
libgnucash/engine/test/utest-Split.cpp

`xaccSplitGetSharePrice` returns price==0 instead of price==1 and don't save price==0 into pricedb.

Bug 798406 - 4.9 inappropriately converts dollars to shares at $1 a piece in pure cash transactions

---

gnucash/gnome/dialog-find-transactions.c
gnucash/register/ledger-core/gnc-ledger-display.c

This is a proposed fix for the bug mentioned. The first commit I think is OK but am wondering if the second commit needs to be changed.
The second commit uses a hash table to remember the template accounts that have been excluded already. I am comparing the template account pointer to do this and am wondering if it should be based on the guid string. The template account pointer should be around while program is running but when the schedule is deleted, the template accounts will also be deleted.
As I am just comparing the pointer, will this matter?

Bug741674 - Template accounts appearing in search register and gl

---

gnucash/gnome-utils/gnc-currency-edit.c
gnucash/gnome-utils/gnc-plugin.c
gnucash/gnome-utils/gnc-tree-model-budget.c
gnucash/gnome-utils/gnc-tree-view-split-reg.c
gnucash/gnome/business-gnome-utils.c
gnucash/gnome/dialog-lot-viewer.c
gnucash/gnome/dialog-payment.c
gnucash/gnome/gnc-plugin-page-owner-tree.c
gnucash/register/ledger-core/split-register-control.c
gnucash/register/ledger-core/split-register-load.c
gnucash/register/ledger-core/split-register.c

- eliminate some GValue management
- eliminate O(N^2) `xaccTransGetSplit` scanning
- eliminate `g_strdup` new gchar* returned from libguile

various code progress

---

libgnucash/engine/CMakeLists.txt
libgnucash/engine/gnc-budget.c
libgnucash/engine/gnc-budget.cpp
libgnucash/engine/gnc-budget.h
libgnucash/engine/test/utest-Budget.c
po/POTFILES.in

The first time a budget value or note is accessed, the whole kvp tree is loaded onto ~memory~struct. 
All subsequent value or note access are speedy.
Writes to value or note are written to backend *and* ~memory~struct.
Draft. ~Leaky.~

Budget backend efficiency improvements.

---

gnucash/gnome-utils/gnc-gui-query.c
gnucash/gnome-utils/gnc-ui.h
gnucash/import-export/bi-import/dialog-bi-import-gui.c
gnucash/import-export/csv-imp/assistant-csv-account-import.c
gnucash/import-export/customer-import/dialog-customer-import-gui.c
gnucash/import-export/import-main-matcher.c

I merged the triple definition of the gnc_input_dialog and the double definition of gnc_info2_dialog.
The matching dialog now has 3 additional right-click options to edit description, notes and memo.

798164 Import transaction window does not allow changing the transaction description 

---

bindings/python/example_scripts/qof.py
bindings/python/example_scripts/rest-api/gnucash_rest.py
bindings/python/gnucash_core.py

Python bindings already have some wrapping objects for
qof predicates. This adds the one missing for GncNumeric
comparisons.
Additionally fixes a wrong number for QOF_NUMERIC_MATCH_ANY
in example file.
[Provide the complete set of QOF enums in gnucash](https://github.com/Gnucash/gnucash/pull/1290/commits/62f8acf6ae265ceac29a01b290b450b9a4cf8cfd) and
[Modify examples to make use of it](https://github.com/Gnucash/gnucash/pull/1290/commits/395c7a705248615a70cb8b2ea334d309daee875f)

Python bindings: Provide wrapper for qof numeric predicate, import full set of QOF enums to gnucash

---

gnucash/report/html-chart.scm
gnucash/report/reports/standard/category-barchart.scm
gnucash/report/reports/standard/test/test-standard-category-report.scm

Includes simplication of category-barchart.scm and code from @exxus, and test code.
It would be useful if @exxus would include a description for release notes, especially handling edge cases.
The last issue relates the table output format. It contains both percentages and currency. Wouldn't this be confusing? If this is intentional, it should also be included in the release notes.

Category charts upgrade to chart allocation ratios instead of absolute values.

---

gnucash/gnome/CMakeLists.txt
gnucash/gnome/assistant-stock-transaction.cpp
gnucash/gnome/assistant-stock-transaction.h
gnucash/gnome/gnc-plugin-page-register.c
gnucash/gtkbuilder/CMakeLists.txt
gnucash/gtkbuilder/assistant-stock-transaction.glade
gnucash/ui/gnc-plugin-page-register-ui.xml
libgnucash/engine/gnc-pricedb.c
libgnucash/engine/gnc-pricedb.h
po/POTFILES.in

In progress: UI for creating well-crafted stock transactions.
Further thoughts
- `Account.cpp` to be upgraded to have `xaccAccountSetLinkedAccount (account, id, target_account)` and `xaccAccountGetLinkedAccount (account, id)` to store/retrieve in account's kvp. Thus other reports may retrieve such metadata.
- xaccAccountSetLinkedAccount (stock_acct, "proceeds-acct", asset_cash_proceeds)
- xaccAccountSetLinkedAccount (stock_acct, "capgains-acct", income_capgains)
- xaccAccountSetLinkedAccount (stock_acct, "dividend-acct", income_dividend)
- xaccAccountSetLinkedAccount (stock_acct, "expense-acct", expense_fees)

Stock editor and ACB Calculator

---

gnucash/gschemas/org.gnucash.GnuCash.warnings.gschema.xml.in

These were not working because they were missing from the temporary warnings settings schema. The warnings could only be dismissed permanently.
Add them to the temporary warnings section of the settings schema.

Fix suppression of "cut split/transaction" warnings for the current session

---

bindings/python/gnucash_core.py

Derive some numeric comparisons from Fraction class
https://github.com/python/cpython/blob/3.7/Lib/fractions.py
and general information from
https://docs.python.org/3/library/numbers.html#numbers.Integral
This is not the full set of comparisons, needs to be extended.
It would be good to extend tests to cover this.

Implement some comparisons for GncNumeric

---

gnucash/report/reports/standard/income-statement.scm
gnucash/report/reports/standard/test/test-balsheet-pnl.scm

Because it's true that a single-column income-statement should not require nested html-tables. Thanks to AdrienM for debugging. https://lists.gnucash.org/pipermail/gnucash-user/2022-March/100354.html

[income-statement] single-column doesn't need separate inc/exp tables

---

bindings/guile/gnc-kvp-guile.cpp
bindings/guile/test/CMakeLists.txt
bindings/guile/test/test-scm-kvpvalue.scm
libgnucash/engine/kvp-frame.cpp
libgnucash/engine/kvp-frame.hpp

* ~gncEntry precision bugs~ moved to #1312 
* creates a lispy kvp-frame representation
* avoids segfault when navigating non-existent frame:
```scheme
(let ((book (gnc-get-current-book)))
(define (try path)
(format #t "retrieve ~s ~s\n"
path (qof-book-get-option book path)))
(qof-book-set-option book "bla" '("top" "lvl1a"))
(qof-book-set-option book "arg" '("top" "lvl1b"))
(qof-book-set-option book "baf" '("top" "lvl1c" "lvl2" "lvl3"))
(qof-book-set-option book '"baf" '("top" "lvl1c" "lvl2" "lvl3"))
(qof-book-set-option book #("arg" "1" "2" 3) '("top" "lvl1d"))
(qof-book-set-option book
'(("a" . "alpha")
("b" . "beta")
("c" . "charlie"))
'("top" "lvl1e"))
(try '("top"))
(try '("top" "lvl1a"))
(try '("top" "lvl1b"))
(try '("top" "lvl1c"))
(try '("top" "lvl1c" "lvl2"))
(try '("top" "lvl1c" …
```

KvpValue::Type::LIST and KvpFrame <-> SCM

---

gnucash/register/ledger-core/gncEntryLedger.c
gnucash/report/reports/standard/invoice.scm
libgnucash/engine/gnc-numeric.cpp

* removes rounding for Discount, Quantity allowing input of unrounded numbers
* invoice report shows numbers as fraction or decimal appropriately
* silence gnc-numeric warning

gncEntry and invoice plugin page

---

CMakeLists.txt
cmake/configure-appdata.cmake
common/cmake_modules/GncAddSchemeTargets.cmake
common/cmake_modules/GncAddSwigCommand.cmake
common/debug/valgrind/valgrind-libgda.supp
common/test-core/test-stuff.h
common/test-core/unittest-support.h
contrib/rapid2gnucash.py
doc/examples/taxreport.gnucash
gnucash/gnome-utils/gnc-cell-view.c
gnucash/gnome-utils/gnc-frequency.h
gnucash/gnome-utils/gnc-main-window.c
gnucash/gnome/dialog-print-check.c
gnucash/gnome/dialog-sx-editor.c
gnucash/gnome/window-reconcile2.c
gnucash/gschemas/pref_transformations.xml
gnucash/import-export/import-backend.c
gnucash/import-export/import-main-matcher.c
gnucash/import-export/qif-imp/test/test-qif-merge-groups.scm
gnucash/python/pycons/pycons
gnucash/register/ledger-core/split-register.c
libgnucash/app-utils/gnc-ui-util.h
libgnucash/app-utils/options.scm
libgnucash/backend/xml/test/test-files/xml1/abcall.gml
libgnucash/backend/xml/test/test-files/xml2/abcall.gml2
libgnucash/engine/Scrub.c
libgnucash/engine/gnc-numeric.cpp
libgnucash/engine/policy-p.h
libgnucash/engine/qofquery.h
libgnucash/engine/test/gtest-gnc-datetime.cpp

Found via `codespell -q 3 -S *.po,./po,*.min.js,./ChangeLog*,./NEWS,./borrowed,./doc/README*,./AUTHORS,./libgnucash/tax/us/txf-de*,./data/accounts -L ans,ba,cas,dragable,gae,iff,iif,mut,nd,numer,parm,parms,startd,stoll`

Fix various typos

---

bindings/engine-common.i
gnucash/report/html-acct-table.scm
gnucash/report/report-utilities.scm
gnucash/report/reports/example/average-balance.scm
gnucash/report/reports/example/daily-reports.scm
gnucash/report/reports/standard/account-summary.scm
gnucash/report/reports/standard/budget.scm
gnucash/report/reports/standard/cash-flow.scm
gnucash/report/reports/standard/category-barchart.scm
gnucash/report/reports/standard/net-charts.scm
gnucash/report/reports/standard/portfolio.scm
gnucash/report/reports/standard/test/test-income-gst.scm
gnucash/report/test/test-report-utilities.scm
libgnucash/engine/Account.cpp
libgnucash/engine/Account.h

Much more efficient. Avoids generating GLists of accounts' descendants repeatedly prior to deleting duplicates.

Move function from scheme to cpp

---

libgnucash/engine/Account.cpp
libgnucash/engine/test/utest-Account.cpp

gnc_account_lookup_by_name and gnc_account_lookup_by_code were searching breadthwise.
as reported in https://github.com/Gnucash/gnucash/pull/1101#issuecomment-1098146573

[account.cpp] restore breadthwise search for 2 functions

---

gnucash/gnome-utils/dialog-options.cpp
gnucash/gnome/assistant-hierarchy.cpp
gnucash/gnome/business-options-gnome.cpp
gnucash/report/options-utilities.scm
libgnucash/app-utils/gnc-option-impl.cpp
libgnucash/app-utils/gnc-option-impl.hpp
libgnucash/app-utils/gnc-optiondb.i
libgnucash/app-utils/options.scm

@jralls  I have been looking at the new C++ options in master and have tried to fix a couple of additional errors I found so created this PR. Apart from the 'FancyDate' one, there is one I have come across that can not see where it is going wrong.
That is 'Plot Size', first off I did not realize it had changed so looking in wrong area. In the dialog, the plot size widget is 309 characters wide. I see that gnc_make_plot_size_option is getting the correct 'int' values but when it tries to create a GncOptionUIType::NUMBER_RANGE calling create_range_spinner,  the values returned do not match with the upper_bound being the very large number.

[Master] C++options posible fixes

---

libgnucash/engine/gnc-date.cpp
libgnucash/engine/gnc-date.h

With the accounting period preference settings set to 'Start/End of previous quarter' and balance sheet report using 'End of accounting period' the date is wrong, currently is 30/03/2022 when it should be 31/03/2022.
I fixed this by changing `gnc_gdate_set_prev_quarter_end` to make sure date is month end.
I think it looks correct/OK to me but after a second opinion as I am not really up on financial matters.
For the way the date was calculated... 
`gnc_gdate_set_prev_quarter_end` calls `gnc_gdate_set_quarter_end` and this function changes the date in the following way...
starts of as 01/04/2022
changes to 01/07/2022
changes to 30/06/2022
and then `gnc_gdate_set_prev_quarter_end` would subtract 3 months to get
30/03/2022

Bug 798501 - Balance wrong date end of account period

---

data/accounts/CMakeLists.txt
data/accounts/es_AR/CMakeLists.txt
data/accounts/es_AR/acctchrt_brokerage.gnucash-xea
data/accounts/es_AR/acctchrt_business.gnucash-xea
data/accounts/es_AR/acctchrt_carloan.gnucash-xea
data/accounts/es_AR/acctchrt_cdmoneymkt.gnucash-xea
data/accounts/es_AR/acctchrt_checkbook.gnucash-xea
data/accounts/es_AR/acctchrt_childcare.gnucash-xea
data/accounts/es_AR/acctchrt_common.gnucash-xea
data/accounts/es_AR/acctchrt_currency.gnucash-xea
data/accounts/es_AR/acctchrt_fixedassets.gnucash-xea
data/accounts/es_AR/acctchrt_homeloan.gnucash-xea
data/accounts/es_AR/acctchrt_homeown.gnucash-xea
data/accounts/es_AR/acctchrt_otherloan.gnucash-xea
data/accounts/es_AR/acctchrt_renter.gnucash-xea
data/accounts/es_AR/acctchrt_spouseinc.gnucash-xea

I am in the process of creating account charts for Argentina. The PR is a Draft for now, I will mark it as ready for review when all translations are completed.
Translated:

Add account charts for locale es_AR.

---

gnucash/gnome/dialog-sx-since-last-run.c

When the "since last run" notification dialog is disabled on file open, it leaks a reference to GncSxInstanceModel and any creation errors won't be displayed. Avoid returning from the function too early.

[dialog-sx-since-last-run] Fix handling of last run dialog on file open

---

gnucash/gnome-utils/gnc-main-window.c
gnucash/ui/gnc-main-window-ui.xml

This makes it easier to change the tab position quickly without opening the preferences window.
With many tabs open there's more space to display all tabs vertically but when resizing GnuCash to half the display size they use up too much horizontal space which can be fixed by temporarily making the tabs horizontal.
----
PR to master: #1350

Add action group to View menu for the tab position

---

gnucash/import-export/aqb/assistant-ab-initial.c
gnucash/import-export/import-account-matcher.c
gnucash/import-export/import-backend.c
gnucash/import-export/import-utilities.c
gnucash/import-export/import-utilities.h

`qof_instance_get` comes from `g_object_get` which returns copies and must be freed via `g_free` or `g_object_unref`. see https://docs.gtk.org/gobject/method.Object.get.htmle-Object-Type.html#g-object-get
ditto `gtk_tree_model_get`.
This means the signatures for `gnc_import_get_split_online_id` and friends are wrong -- they're not `const` and must be `g_free`d after use. I guess fixing this means changing the signature throughout?

start plugging leaks from qof_instance_get

---

bindings/python/tests/test_transaction.py
libgnucash/engine/Transaction.c
libgnucash/engine/Transaction.h
libgnucash/engine/TransactionP.h
libgnucash/engine/test/utest-Invoice.c
libgnucash/engine/test/utest-Transaction.cpp

Generates TXN_TYPE dynamically (and caches it) by analysing transaction splits, instead of relying on transaction property. ~Also eliminates TXN_TYPE_LINK merging it as TXN_TYPE_PAYMENT.~ Needs much scrutiny.

xaccTransGetTxnType generates the type (and caches it) dynamically

---

gnucash/gtkbuilder/dialog-import.glade
gnucash/import-export/import-main-matcher.c

Today I wanted to mass-rename when importing, and could not.
This commit will allow renaming desc/notes/memo, but only enabled if rows' desc/notes/memo are identical.
The disabling works piecemeal i.e. if selection has identical description but varied memo and notes, then only the description will be allowed mass renaming.
@jeanlaroche from #1162

refinement #1162 to allow edit multiple rows

---

gnucash/gnome/dialog-sx-editor.c
gnucash/import-export/import-account-matcher.c
gnucash/import-export/import-backend.c
gnucash/register/ledger-core/split-register-model.c
libgnucash/app-utils/gnc-sx-instance-model.c

more leaks. all because `qof_instance_get` for chars and structs need to be freed separately.

more leaks because qof_instance_get returns a new char*

---

gnucash/gnome-utils/gnc-account-sel.c
gnucash/gnome/dialog-customer.c
gnucash/gnome/dialog-doclink.c
gnucash/gnome/dialog-employee.c
gnucash/gnome/dialog-invoice.c
gnucash/gnome/dialog-job.c
gnucash/gnome/dialog-order.c
gnucash/gnome/dialog-sx-editor.c
gnucash/gnome/dialog-vendor.c

The former returns a `const char*` which does not need to be freed. I think this is self-explanatory.

use gtk_entry_get_text instead of gtk_editable_get_chars

---

gnucash/gnome-utils/gnc-gnome-utils.c

This comes with a few nice side effects:
* "help:" no longer needs the workaround to link directly to an anchor.
" "help:" requires the document's book id to be "index". We used to have
"index" for guide and "help" for manual. The forced alignment also
allows us to simplify the way MacOS invokes guide an manual.
Must be merged together with the "ghelp2help" branch in gnucash-docs
TODO:

Use "help:" instead of "ghelp:" to display our documentation on linux

---

data/accounts/fr_BE/acctchrt_business.gnucash-xea
data/accounts/fr_CH/acctchrt_business.gnucash-xea
data/accounts/fr_CH/acctchrt_pme-19.gnucash-xea
data/accounts/fr_FR/acctchrt_business.gnucash-xea

Hello,
For some reasons, the business account templates in French are using different names for the Assets and Equity root account than the other templates in French
In other language they are the same in all templates
This merge request fixes this

Standardize the root account names of the business account template in French

---

gnucash/gnome/assistant-stock-transaction.cpp

* add stock units column indicating gain/loss of number of units
* don't show Fee line if zero; a zero-fee split isn't generated.

stock assistant - add units column, remove zero-fee line

---

gnucash/gnome/assistant-stock-transaction.cpp

On the long side of the transaction list, dividend reinvestments with and without remainder can be merged.
On the short side of the transaction list, the 2 dividend reinvestment transactions are not relevant and should be deleted.  There is no such thing as a "compensatory dividend reinvestment".
Refer to https://bugs.gnucash.org/show_bug.cgi?id=798004#c49

Updated wording for assistant-stock-transaction.cpp

---

gnucash/gnome/assistant-stock-transaction.cpp

Stock splits and reverse stock splits are handled via a specialised stock_amount input. Instead of inputting new units, input new balance. Some error checks are included. This means the assistant is designed to generalise stock activity, yet has a special case. :man_shrugging:

Stock Assistant: specialises stock split transactions.

---

gnucash/gnome-utils/gnc-currency-edit.c

...thus typing 'dollar' would filter to all currencies using the dollar. It uses `gtk_bin_get_child` because `gtk_combo_box_get_child` is Gtk4 only.

[gnc-currency-edit] allow GtkEntry completion

---

gnucash/gnome/gnc-plugin-budget.c
gnucash/gnome/gnc-plugin-page-budget.c
libgnucash/engine/ScrubBudget.c

where should the `unreversed_budgets` feature be unset? in gnucash or in gnc-budget.c?

Further budget feature fixes

---

bindings/engine.i
gnucash/gnome/gnc-budget-view.c
gnucash/gnome/gnc-plugin-page-budget.c
libgnucash/engine/gnc-budget.cpp
libgnucash/engine/gnc-budget.h
libgnucash/engine/test/utest-Budget.c

mainly let's ensure `gnc_budget_get_account_period_note` returns a `const char*` to harmonize with other string getters. and other tidying up.

some more gnc-budget tidying up

---

libgnucash/engine/mocks/fake-qofquery.cpp

Hi everyone! When I've tried to compile tests on gnucash-4.12 to bump version in gentoo, I've hit the following error.
```
[370/398] /usr/sbin/x86_64-pc-linux-gnu-g++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_LOCALE_DYN_LINK -DBOOST_LOCALE_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DHAVE_CONFIG_H -DHAVE_GUILE22 -D_GNU_SOURCE -I/var/tmp/portage/app-office/gnucash-4.12/work/gnucash-4.12_build/common -I/var/tmp/portage/app-office/gnucash-4.12/work/gnucash-4.12/common …
```

Fix libgnucash/engine/mocks/fake-qofquery.cpp: error: pointer used after ‘void operator delete(void*, std::size_t)’ [-Werror=use-after-free]

---

gnucash/import-export/import-backend.c
gnucash/import-export/import-main-matcher.c
gnucash/import-export/ofx/gnc-ofx-import.c

An alternate and much more involved fix for [Bug 798681](https://bugs.gnucash.org/show_bug.cgi?id=798681). It first heavily refactors ofx_proc_transaction_cb by extracting several functions to make each single-purpose and short enough to easily reason about. The last commit reorders the split creation so that the import account splits are first in all cases except a reinvest, which doesn't have an import account split.

OFX Investment transaction import

---

gnucash/register/ledger-core/split-register-layout.c
gnucash/register/ledger-core/split-register-load.c
gnucash/register/ledger-core/split-register.c
gnucash/register/register-core/combocell.h
gnucash/register/register-gnome/combocell-gnome.c
gnucash/register/register-gnome/gnucash-item-edit.c
gnucash/register/register-gnome/gnucash-item-list.c

I think this may be of use and seem to recall it being requested.
This PR changes the register description cell from an entry cell to a combo cell which lists all the previous descriptions.
To make the search more akin to a modified completion, a function was added to combocell that sets the cell to use only the type ahead search. Below is an image of the description cell popped...
As is, there is a difference to a normal register and the journal. The journal with default settings, lists only the descriptions of the last 30 days where as the normal registers have all entries. This could be changed by adding the if clause at line 663 in split-register-load.c
`if (!info->first_pass)`
which will limit the descriptions to be the same as the register view. Not sure which is better ?
This …

Register description cell

---

gnucash/gnome-utils/dialog-account.c
gnucash/gnome-utils/gnc-tree-model-account-types.c
gnucash/gnome-utils/gnc-tree-model-account-types.h
gnucash/gtkbuilder/dialog-account.glade

Came across this bug regarding the account dialog layout and thought I would see what the changes would look like.
The main change is changing the account type field from a tree view to a combo and repositioning it. The parent account tree view has been set to expand to the available space. The bug also mentions changing the parent account field to a combo but I do not like that idea as I think it looks better as a tree.
Added some images below, the first one is when editing, the second is a new account and the third is the type popped...
Is it an improvement ?
Any further changes required before pushing ?

Bug769256 - Change New Account Dialog

---

gnucash/register/register-gnome/gnucash-sheet-private.c

I came across this bug and thought it may be of use so had a go at implementing it, did not take much and I was curious to see what it would look like.
Basically if a PRICE_CELL_TYPE is too narrow to display the whole number, the digits are replaced with '*'s
I think I may of been caught out by this along time ago.
Worth while?

Bug 403979 - Balance column shows only low order digits when too narrow

---

libgnucash/app-utils/gnc-quotes.cpp

from .../gnucash-4.8/libgnucash/app-utils/gnc-quotes.cpp:33: /usr/include/boost/bind.hpp:36:1: note: ‘#pragma message:
The practice of declaring the Bind placeholders (_1, _2, ...) in the
global namespace is deprecated.
Please use <boost/bind/bind.hpp> + using namespace boost::placeholders,
or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.’
The issue was fixed in boost 1.76, but, e.g ubuntu 22.04 has boost 1.74

Silence the boost (<1.76) warning message

---

gnucash/gnome/assistant-hierarchy.c
gnucash/gnome/gnc-plugin-page-register.c

This commit should be applied after the release of gnucash version 4.3.

Activate feature GNC_FEATURE_EQUITY_TYPE_OPENING_BALANCE

---

libgnucash/engine/Account.cpp
libgnucash/engine/SX-book.c
libgnucash/engine/SchedXaction.c
libgnucash/engine/Transaction.c
libgnucash/engine/gnc-pricedb.c
libgnucash/engine/gncBillTerm.c
libgnucash/engine/gncCustomer.c
libgnucash/engine/gncEntry.c
libgnucash/engine/gncInvoice.c
libgnucash/engine/gncJob.c
libgnucash/engine/gncJob.h
libgnucash/engine/gncTaxTable.c
libgnucash/engine/gncVendor.c

Chris mentioned a problem with Tax Tables not being freed on closure so had a look and I think the first commit fixes that. In the same commit there is a fix for Bill Terms as they are very similar.
I thought I would have a look at the other objects and found Jobs were not being destroyed when Customer and Vendors are so that's the second commit followed by Accounts and Scheduled Transactions Accounts.
The last commit, which I have commented out, would delete Scheduled transaction accounts that have no splits when the root template account is destroyed, This is an extension of #1082, I had 30 which does work but it fails test 22, so not sure if I need to change the test or maybe the commit is wrong.
There are two other objects that I have not yet got to the bottom of...
I have 52 …

Object that are not freed / destroyed

---

gnucash/gnome-utils/CMakeLists.txt
gnucash/gnome-utils/gnc-report-combo.c
gnucash/gnome-utils/gnc-report-combo.h
gnucash/gnome/business-gnome-utils.c
gnucash/gnome/business-gnome-utils.h
gnucash/gnome/business-options-gnome.cpp
gnucash/gnome/dialog-custom-report.c
gnucash/gnome/dialog-invoice.c
gnucash/gnome/gnc-plugin-business.c
gnucash/gnome/gnc-plugin-business.h
gnucash/gschemas/pref_transformations.xml
gnucash/gtkbuilder/business-options-gnome.glade
gnucash/gtkbuilder/business-prefs.glade
gnucash/gtkbuilder/dialog-invoice.glade
gnucash/report/report-core.scm
gnucash/report/reports/standard/invoice.scm
gnucash/report/reports/standard/taxinvoice.scm
libgnucash/engine/gnc-option-uitype.hpp
libgnucash/engine/gnc-optiondb.cpp
libgnucash/engine/gnc-optiondb.hpp
libgnucash/engine/qofbook.cpp
libgnucash/engine/qofbook.h
libgnucash/engine/qofbookslots.h

This PR is a rehash of the maint version PR #1094 and now uses the new options as part of saving in book properties.
This commit changes the preference in Business->'Report for Printing' to be saved as a book property in 'File>Properties->Business' and allow the selection of any Invoice Report to be used as the default. Every thing in the previous PR is the same apart from the saving to book properties and the inclusion of code to do that. The property being saved is a joining of the report guid and the report name which is used if said report is deleted.
Also included is code which I think achieves what PR #1247 does. This was done by presenting a dialog with the default for the report combo set to the properties setting. This dialog has a timeout which is adjustable under properties, …

[Master] Bug753307 - Custom Report be selectable as default Report for Printing

---

gnucash/gnome/dialog-report-column-view.cpp
gnucash/import-export/csv-imp/assistant-csv-price-import.cpp
libgnucash/app-utils/gnc-quotes.cpp
libgnucash/backend/dbi/gnc-backend-dbi.cpp
libgnucash/backend/sql/gnc-sql-backend.cpp
libgnucash/core-utils/gnc-filepath-utils.cpp
libgnucash/engine/gnc-timezone.cpp
libgnucash/engine/qoflog.cpp

Found by clazy - clazy-range-loop-reference

Use const references for for-loops to avoid unnecessary copies

---

bindings/python/gnucash_core.i

Small change, big effect. This makes (parts of) logging accessible to python bindings.
With this it's possible to go
```
gnucash.gnucash_core_c.qof_log_set_level("", gnucash.gnucash_core_c.QOF_LOG_DEBUG)
gnucash.gnucash_core_c.qof_log_set_level("gnc", gnucash.gnucash_core_c.QOF_LOG_DEBUG)
gnucash.gnucash_core_c.qof_log_set_level("qof", gnucash.gnucash_core_c.QOF_LOG_DEBUG)
```
and see all the debug information when calling the c/c++ code. Very helpful for coding/debugging python.
It could be worth a try
* enable code using python modules to read the logging config file as done in gnucash bin gnc_log_init()
* it would be nice to be able to just call gnc_log_init() but there's no header file for that as that is in gnucash-bin.c - could that be put into a separate file to make it accessible …

make (parts of) gnucash logging accessible from python modules

---

gnucash/gschemas/pref_transformations.xml
libgnucash/app-utils/gnc-gsettings.cpp

This changes the `gnc_gsettings_version_upgrade` process so that release versions greater than the current GnuCash version in the `pref_transformations.xml` file are not processed. It also fixes a windows bug that was failing on the glib error...
`WARN <GLib-GIO> subscribe() failed: only 64 different paths may be watched.`
The way I have done this is that after each migrate/obsolete pass, the function `clear_gset_object`(will rename this to `clear_gsettings_object`), is called which finds the GSettings object in the schema_hash, removes it and then unref's the object to release the schema path.
The down side on this is that a two GSettings objects are created and removed for each migrate and one created and removed for each obsolete.
Not sure if this is an issue, another way I did think …

Gsettting Changes

---

libgnucash/engine/kvp-value.hpp
libgnucash/engine/test/test-gnc-guid.cpp

Remove references to old boost versions

---

gnucash/gnome/gnc-plugin-page-register.c
gnucash/gnome/gnc-split-reg.c
gnucash/gnome/gnc-split-reg.h
gnucash/register/ledger-core/split-register-load.c
gnucash/register/ledger-core/split-register.c
gnucash/register/ledger-core/split-register.h
gnucash/register/register-core/table-model.c
gnucash/register/register-core/table-model.h
gnucash/register/register-gnome/gnucash-sheet-private.c

Register widths are saved in the .gcm file under sections based on the account guid. When you have for example an 'Assets' register open and the 'with sub-account' register page 'Assets+' open, they will both save there settings to the same section as there is only one guid.
To fix this, add a '+' to the end of the guid for the sub-account section as done for the title.
Also, I have modified @jralls commit earlier on to not use xaccAccountSetSortReversed as the 'sort order / sort by and filter by' are all stored in the register. This also fixes the general journal as there is no default account and if saved open segfaults Gnucash on restart.
Currently there is a function to remove those settings from used accounts and store them in the .gcm file, if I remember I added that at the …

Bug798759 saving register 'with sub-account' registers 

---

common/cmake_modules/GncAddGSchemaTargets.cmake
common/cmake_modules/GncAddTest.cmake
common/cmake_modules/MakeDist.cmake
common/cmake_modules/MakeDistCheck.cmake
gnucash/gnome/CMakeLists.txt
gnucash/gschemas/CMakeLists.txt
libgnucash/backend/xml/test/CMakeLists.txt
libgnucash/quotes/CMakeLists.txt
po/CMakeLists.txt

- In GncAddTest, set_tests_properties() is already setting the env
- In the other uses, there is no change to the environment

Remove redundant uses of cmake -E env

---

bindings/guile/gnc-kvp-guile.cpp
gnucash/gnome-search/search-core-type.c
gnucash/gnome/gnc-plugin-page-owner-tree.c
gnucash/report/gnc-report.cpp
libgnucash/app-utils/calculation/expression_parser.c
libgnucash/engine/gnc-date.cpp
libgnucash/engine/qofquery.cpp

Found by gcc 12 when compiling with "-O2 -Wnull-dereference"

Guard against some possible null pointer dereferences

---

gnucash/gnucash-core-app.cpp
gnucash/gnucash-core-app.hpp

- spotted by [bugprone-undelegated-constructor] [bugprone-unused-raii]
gnucash/gnucash-core-app.cpp:218:5: warning: did you intend to call a delegated constructor? A temporary object is created here instead [bugprone-undelegated-constructor]
CoreApp();
^
gnucash/gnucash-core-app.cpp:218:5: warning: object destroyed immediately after creation; did you mean to name the object? [bugprone-unused-raii]
CoreApp();
^      ~~
give_me_a_name

Fix  CoreApp() constructor misuse

---

gnucash/gnome-utils/gnc-main-window.cpp

gnc_main_window_update_one_menu_action() will try to print data.action_name

Fix crash with --log gnc.gui=debug

---

gnucash/gnome/gnc-budget-view.c

https://bugs.gnucash.org/show_bug.cgi?id=798570
In a budget, if you increase the number of periods (ex. from 12 months to 26 fortnights), the code attempts to delete the "totals column" (the last column which shows totals for the entire budget), then add the extra columns and then add the totals column back.  When deleting the totals column in the "totals row" (the bottom rows which show totals for each period), the wrong column was being deleted.  The "totals column" would remain which displays the entire budget totals instead of just the given period, then columns added and a second "totals column" was added.  Calculating the column to delete was not taking into account the 2 hidden by default columns (code and description).

Bug 798570 - Totals for the income, expenses and remaining to budget incorrect for one specific date

---

CMakeLists.txt
gnucash/gnome-utils/gnc-keyring.c
libgnucash/backend/xml/gnc-xml-backend.cpp

- Apple Xcode deprecates SecKeychain* and mktemp
- ~~Leave mingw - it uses guile2~~
- mingw no longer needs it, according to the build logs at
https://code.gnucash.org/builds/win32/build-logs/master

Push -Wno-error=deprecated-declarations from C*_FLAGS down to the target

---

libgnucash/app-utils/gnc-ui-util.c

Finally got back to looking at this, @jralls this is what I was thinking off.
In addition to fixing bug report, this PR changes the vertical alignment of the row contents to be at the top. This is only noticeable when say the notes field has more than one line. Also as the Account dialog notes field had word wrapping I have added it to the CoA notes cell.
Still need to do some more testing but seems to work.

Bug798558 - Irregular line spacing for securities accounts in CoA

---

gnucash/gtkbuilder/dialog-import.glade
gnucash/import-export/import-main-matcher.c

Previously, only identical Desc/Notes/Memo were unlocked for editing. This commit allows editing selected transactions' textual data, even if they are not identical.
Mainly for banks like mine who add unique garbage in the Descriptions:
```
"SHOPRITE - Visa Purchase - Receipt 12345678In MELBOURNE Date 27 Feb 2016 Card 462263xxxxxx3981"
"SHOPRITE - Visa Purchase - Receipt 12345679In MELBOURNE Date 28 Feb 2016 Card 462263xxxxxx3981"
etc
```

[import-main-matcher] allow force editing non-identical desc/notes/memo

---

gnucash/gtkbuilder/dialog-preferences.glade
gnucash/register/ledger-core/split-register-load.c
gnucash/ui/gnc-plugin-page-register.ui

This adds the blank transaction at the top of the register when in reverse sort order which I think makes sense and there may be a bug for it.
As part of this, the toolbar icon and keyboard short cut did not seem appropriate so have changed them to 'go-jump' and 'CNTRL-B', this can be changed if there is a better combination. This would then free up 'CNTRL+Page_Down' for tab navigation which I think there is also a bug report for but have not looked if other changes are needed for this.
Unfortunately I did not realise that the tool tip was so specific so that needed changing and subsequently found the preference 'Future transactions after blank transaction' would also need changing, might need some better tool tip text for that one.
I have tested this and all seems to work OK but would …

Add blank transaction at the top - the last piece for 5.1

---

libgnucash/engine/Account.cpp
libgnucash/engine/Account.h
libgnucash/engine/Recurrence.c

This demonstrates a fix to https://bugs.gnucash.org/show_bug.cgi?id=798716
It shows the structure of new functionality to add, since *I think* the current functions do not allow this.
In essence, for budget reporting, the balance difference of an account should be computed in the local currency first, and then the change should be converted to a parent currency. The results for all sub-accounts are "rolled up" the account hierarchy in the same way as usual, using `gnc_account_foreach_descendant`.
It will need formatting to match style policies and coding guidelines.

Demonstrate fx handling in budget report

---

libgnucash/app-utils/test/CMakeLists.txt

The test relies on a lot of external dependencies
- installed finance-quote-wrapper
- alpha vantage key
- network
- working remote server
Running ./bin/test-gnc-quotes from the command line will still include online_wiggle

By default, filter out online_wiggle in test-gnc-quotes
