po/de.po
based on maint, built gnucash.mo successfully
=> German translation2

configure.ac
All these options actually enabled the related features.
=> configure: fix --disable-debug, --disable-profile and --disable-locale-specific-tax

po/de.po
Rebased to the actual maint version.
merged with gnucash-2.6.15.pot and added a translation.
=> Translation de

po/fi.po
Rebased previous PR #135 on the correct branch.
=> Update Finnish translation

.travis.yml
This should be merged before #149
=> Enable python testing in travis

configure.ac, src/register/register-gnome/gnucash-cursor.h, src/register/register-gnome/table-gnome.c
The standard test(1) comparison operator is "=".
=> Use portable test(1) operator.

src/register/ledger-core/split-register-model.c, src/register/register-gnome/gnucash-header.c, src/register/register-gnome/gnucash-item-edit.c, src/register/register-gnome/gnucash-item-edit.h, src/register/register-gnome/gnucash-register.c, src/register/register-gnome/gnucash-sheet-private.c, src/register/register-gnome/gnucash-sheet.c, src/register/register-gnome/gnucash-sheetP.h, src/register/register-gnome/gnucash-style.c
More updates without any of the colour changes that I had played with so hopefully this should be OK.
=> Gtk3 update4

po/de.po
Should fix https://bugzilla.gnome.org/show_bug.cgi?id=787226
@Mechtilde
=> L10N: DE, fix bug #787226: Bill ID / Billing ID swapped.

po/de.po
Do these changes need to be committed manually?
@Mechtilde
=> L10N: DE, automatic "make pot" changes.

po/de.po
=> L10N: DE, some small corrections.

cmake/CMakeLists.txt
Change cmake config to move ofx-gschemas out of main list and check for WITH_OFX flag.
=> Made ofx-gschema dependent on WITH_OFX flag

gnucash/report/standard-reports/transaction.scm
Usability fix. This should help newcomers. Two changes:
1. Toggling Display/Account Name will also enable/disable Display/Full Account Name
2. Overhaul of the Sorting tab only presents *valid* options. e.g. 
- Changing Primary or Secondary Sort-key to 'none will disable its descendant options. 
- Changing to 'date or 'register-order will enable Date-interval choice. 
- Changing to 'account-name or 'account-code will enable subtotal checkbox
- Changing subtotal checkbox to #t will allow relevant account-name display options
- Changed order for better flow of options
This has no backward/forward compatibility issues
=> Tweak "Display", overhaul "Sorting" tab to improve UI

po/ru.po
As written in PR #204, here are my changes:
`msgfmt -c --statistics ru.po`
4672 translated messages, 8 fuzzy translations, 5 untranslated messages.
`msgfmt -c --check-accelerators="_" --statistics ru.po`
71 errors
@all: Changes for keyboard accelerators I will send separately.
=> Adjustment of some Russian translations

gnucash/gnome/gtkbuilder/dialog-find-account.glade, po/lv.po
Not sure whether to patch unstable or master. Both have spelling mistake.
=> Fix spelling insensative->insensitive

configure.ac, gnucash/CMakeLists.txt, gnucash/Makefile.am, gnucash/gnome-utils/gnc-gnome-utils.c, gnucash/gnome-utils/ui/CMakeLists.txt, gnucash/gnome-utils/ui/Makefile.am, gnucash/gnucash-310.css, gnucash/gnucash-320.css, gnucash/gnucash-fallback-310.css, gnucash/gnucash-gresources.xml
I think this covers all that was proposed.
Bob
=> Move CSS files to Gresource file

gnucash/report/standard-reports/cashflow-barchart.scm, gnucash/report/standard-reports/test/Makefile.am, gnucash/report/standard-reports/test/test-cashflow-barchart.scm
Three small changes to the just merged new report cashflow-barcharct.scm
The first 2 simplify the code a little bit and the 3rd adds a new feature: the ability to control the display of money in, out or net independently.
=> Cashflow barchart report

gnucash/gnome-utils/gtkbuilder/dialog-preferences.glade, gnucash/gnome/gtkbuilder/gnc-plugin-page-register.glade, gnucash/gnucash-310.css, gnucash/gnucash-320.css, gnucash/html/gnc-html-webkit1.c, gnucash/import-export/aqb/assistant-ab-initial.glade, gnucash/import-export/aqb/dialog-ab-trans.c, gnucash/import-export/dialog-import.glade, gnucash/register/ledger-core/gncEntryLedgerModel.c, gnucash/register/ledger-core/split-register-model.c, gnucash/register/register-core/table-allgui.c, gnucash/register/register-core/table-allgui.h, gnucash/register/register-core/table-model.c, gnucash/register/register-core/table-model.h, gnucash/register/register-gnome/gnucash-header.c, gnucash/register/register-gnome/gnucash-item-edit.c, gnucash/register/register-gnome/gnucash-item-edit.h, gnucash/register/register-gnome/gnucash-sheet-private.c, gnucash/register/register-gnome/gnucash-sheet.c, gnucash/register/register-gnome/gnucash-sheet.h, gnucash/register/register-gnome/gnucash-style.c
OK I have squashed and dropped and made the changes recommended in PR 212. I have not changed the item edit entry alignment but will have another look.
Also included are a couple of changes to remove deprecated widgets and fixes to glade files that were corrupted when merged from maint.
Bob
=> Item edit cell padding and code reduction of cell colours

gnucash/register/ledger-core/split-register-control.c, gnucash/register/ledger-core/split-register-model.c, gnucash/register/ledger-core/split-register.c, gnucash/register/ledger-core/split-register.h
Added the patch I made for bug 771667 with changes so it would apply to unstable. I believe it achieves all that was requested on that bug.
Bob
=> Reconciled split warning Bug 771667

libgnucash/quotes/CMakeLists.txt, libgnucash/quotes/Makefile.am, libgnucash/quotes/README
File itself was removed in c0fd3b3.
=> Remove gnc-value-portfolio references from dist lists.

accounts/de_DE/acctchrt_skr03.gnucash-xea, po/de.po
=> correct typo

gnucash/report/standard-reports/transaction.scm
=> Bugfix TR common currency was broken

po/de.po, po/ru.po
**ru.po**
* update to new gnucash.pot file (GnuCash 2.7.3, unstable)
* Transaction Associations Dialog
* Find Account Dialog
* About Dialog
* some other translations
**de.po**
* Transaction Associations Dialog
* Find Account Dialog
* About Dialog
* some other translations
=> unstable: update ru.po und de.po files

gnucash/report/standard-reports/test/CMakeLists.txt, gnucash/report/standard-reports/test/test-transaction.scm, gnucash/report/standard-reports/transaction.scm, libgnucash/engine/test/test-extras.scm
and TR enhancement: "Display / Summary Table", new feature with test available.
This builds upon #288 and implements the summary table generation. Also is a continuation of #270.
=> transaction.scm unit testing

gnucash/gnome-utils/dialog-account.c
=> bugfix gnc_ui_new_account_window

data/accounts/ru/CMakeLists.txt, data/accounts/ru/acctchrt_auto.gnucash-xea, data/accounts/ru/acctchrt_autoloan.gnucash-xea, data/accounts/ru/acctchrt_common.gnucash-xea, data/accounts/ru/acctchrt_homeown.gnucash-xea, data/accounts/ru/acctchrt_kids.gnucash-xea, data/accounts/ru/acctchrt_otherloan.gnucash-xea, data/accounts/ru/acctchrt_renter.gnucash-xea
Revision and extension of accounts for the Russian language.
In addition, replacing of commodity: USD => RUB.
=> Revision and extension of accounts for the Russian language.

gnucash/gnome-utils/dialog-file-access.c, gnucash/gnome/assistant-hierarchy.c, gnucash/gnome/dialog-new-user.c, gnucash/gnome/dialog-new-user.h, gnucash/gtkbuilder/assistant-csv-account-import.glade, gnucash/gtkbuilder/assistant-csv-price-import.glade, gnucash/gtkbuilder/assistant-csv-trans-import.glade, gnucash/gtkbuilder/assistant-hierarchy.glade, gnucash/gtkbuilder/assistant-stock-split.glade, gnucash/gtkbuilder/assistant-xml-encoding.glade, gnucash/gtkbuilder/dialog-account-picker.glade, gnucash/gtkbuilder/dialog-new-user.glade, gnucash/import-export/csv-imp/assistant-csv-trans-import.cpp, gnucash/import-export/import-main-matcher.c, gnucash/import-export/import-main-matcher.h, gnucash/import-export/import-match-picker.c, gnucash/import-export/import-match-picker.h, gnucash/import-export/qif-imp/assistant-qif-import.c, gnucash/import-export/qif-imp/dialog-account-picker.c, gnucash/import-export/qif-imp/dialog-account-picker.h, libgnucash/app-utils/gnc-state.c
These are mainly to do with the Qif, OFX, CSV importers.
=> Some for missing transient parent warnings

gnucash/gnome/dialog-imap-editor.c, gnucash/gtkbuilder/dialog-imap-editor.glade, libgnucash/engine/Account.cpp, libgnucash/engine/Account.h, libgnucash/engine/qofinstance-p.h, libgnucash/engine/qofinstance.cpp, libgnucash/engine/test/gtest-import-map.cpp
These changes fix the Imap Editor, sorry about the large number of changes in one commit but a lot of the changes were tied together and also did not have a clear solution for the failures to start with.
Bob
=> Imap editor fix

gnucash/gnome-utils/dialog-transfer.c, gnucash/gnome-utils/gnc-main-window.c, gnucash/gtkbuilder/dialog-preferences.glade, gnucash/register/ledger-core/split-register-control.c
I will add some fixes here as I try and fix them till this PR gets merged
=> Some Fixes after 3.0 released

README, common/cmake_modules/GncAddSwigCommand.cmake
Fixed typos in common/cmake_modules/GncAddSwigCommand.cmake
Updated README
=> Typo fix and README update

README
Off-by-one spacing and a missing closing paren bothered me.
I decided to do something about it.
:)
This is what being a good citizen of the internet looks like, right?
=> Small minor README fix

libgnucash/engine/gnc-date.cpp, libgnucash/engine/gnc-datetime.cpp
strptime/strftime supports various modifiers to their parameters.
- 'E' and 'O': alternate locale-specific formats
(used in Persian, Oriya, Azerbaijani)
- '-': padding
(used in Czech)
GnuCash passes dates as integer y/m/d without using locale-specific
formats, so we need to strip out 'E' and 'O' from the format. '-'
goes wrong in boost somewhere, as far as I can tell, so strip it out
as well.
Fixes https://bugzilla.gnome.org/show_bug.cgi?id=795247.
=> Modify date formats to strip out certian modifiers.

gnucash/report/standard-reports/transaction.scm
This is technically a bug in the TR regarding book split-action property. The reworked TR did not retrieve book split-action properly which means it was always assuming split-action was #f for sorting.
This commit redefines sortkey-list to accept split-action? as a parameter to generate the correct sortkeys. Unfortunately it will make it more complicated; I'm not sure if or how to simplify.
=> Bug 796537 - Transaction Report cannot sort by "num"

gnucash/report/business-reports/easy-invoice.scm, gnucash/report/business-reports/test/CMakeLists.txt, gnucash/report/business-reports/test/test-invoice.scm, gnucash/report/report-system/test/test-extras.scm, gnucash/report/standard-reports/test/test-income-gst.scm, gnucash/report/standard-reports/test/test-transaction.scm
this tests invoice, easy-invoice, fancy-invoice content.
eventually tests will be amended when layout+css is introduced.
=> test-invoice

gnucash/gnome/gnc-budget-view.c
Just some small changes to the budget view based on feedback on Bug 795471
=> Bug795471 - Some more changes to the budget view

gnucash/gnome-utils/dialog-account.c, gnucash/gnome-utils/dialog-account.h, gnucash/gnome/gnc-plugin-page-account-tree.c, gnucash/gtkbuilder/dialog-account.glade, gnucash/ui/gnc-plugin-page-account-tree-ui.xml
Just some thing I have been meaning to do, this dialog allows you to select an account and use that accounts colour for all sub accounts.
=> Color accounts

gnucash/gnome-utils/dialog-options.c, gnucash/gnome/dialog-find-account.c, gnucash/gnome/dialog-trans-assoc.c, gnucash/gnome/dialog-trans-assoc.h, gnucash/gnome/gnc-plugin-basic-commands.c, gnucash/gschemas/org.gnucash.dialogs.gschema.xml.in, gnucash/gtkbuilder/dialog-custom-report.glade, gnucash/gtkbuilder/dialog-find-account.glade, gnucash/gtkbuilder/dialog-options.glade, gnucash/gtkbuilder/dialog-trans-assoc.glade, gnucash/report/report-gnome/dialog-custom-report.c, libgnucash/app-utils/gnc-component-manager.c
Not sure if this all can be on maint but happy to split if required.
=> Change some dialogues to GtkWindows with some small changes

doc/guile-hackers.txt, gnucash/gnome-utils/dialog-options.c, gnucash/gnome/gnc-budget-view.c, gnucash/gschemas/org.gnucash.gschema.xml.in, gnucash/gtkbuilder/dialog-preferences.glade, gnucash/import-export/aqb/gnc-file-aqb-import.c, gnucash/import-export/csv-exp/assistant-csv-export.c, gnucash/report/business-reports/receipt.scm, gnucash/report/jqplot/jquery.jqplot.js, gnucash/report/jqplot/plugins/jqplot.barRenderer.js, gnucash/report/jqplot/plugins/jqplot.bubbleRenderer.js, gnucash/report/report-system/eguile-utilities.scm, gnucash/report/standard-reports/budget-barchart.scm, gnucash/report/standard-reports/budget.scm, libgnucash/app-utils/calculation/fin.c, libgnucash/app-utils/guile-util.h
Thanks for fixing these typos.
=> Fix minor typos

gnucash/gnome-utils/gnc-main-window.c, gnucash/register/ledger-core/gncEntryLedgerModel.c, gnucash/register/ledger-core/split-register-control.c, gnucash/register/ledger-core/split-register-model-save.c, gnucash/register/ledger-core/split-register-model.c, gnucash/register/ledger-core/split-register.c, gnucash/register/register-core/datecell.h, gnucash/register/register-gnome/datecell-gnome.c, libgnucash/engine/qofbook.cpp, libgnucash/engine/qofbook.h
These bugs were reported by Geert and hopefully fix the issues raised with the date warning and the removal of the gdate function.
=> Register Date bugs

bindings/python/tests/CMakeLists.txt, bindings/python/tests/runTests.py.in, bindings/python/tests/test_query.py
add test for creating query object and setting search_for
related to Bug 796137 and fix in commit 1a7c5b9a32df1d0ccd7e739a70b3d0f38e4dda36
=> add basic test for python query

po/fr.po, po/glossary/fr.po
Corrections de traductions trop littéraires de l'anglais
=> French translation update

gnucash/gnome-utils/dialog-options.c, gnucash/gnome-utils/gnc-file.c, gnucash/gnome/dialog-sx-since-last-run.c, gnucash/gtkbuilder/assistant-csv-price-import.glade, gnucash/gtkbuilder/assistant-csv-trans-import.glade, gnucash/gtkbuilder/dialog-account.glade, gnucash/gtkbuilder/dialog-import.glade, gnucash/import-export/csv-exp/assistant-csv-export.c, gnucash/import-export/csv-exp/assistant-csv-export.h, gnucash/import-export/csv-imp/assistant-csv-account-import.c, gnucash/import-export/csv-imp/assistant-csv-price-import.cpp, gnucash/import-export/csv-imp/assistant-csv-trans-import.cpp, gnucash/import-export/csv-imp/csv-account-import.c, gnucash/import-export/import-main-matcher.c
Geert suggested a couple of changes which I have implemented here namely..
CSV import alignment change,
A missing update that should of used a parent window parameter,
And the ability to double click on a file name for file selection.
There are a couple of other bug fixes that I think should be OK but as always will wait for feedback.
=> Some follow up changes after OK button PR

data/accounts/de_AT/CMakeLists.txt, data/accounts/de_AT/acctchrt_ekr2017.gnucash-xea
I have created an austrian account template based on the publication of the Chamber of Public Accountants (KSW).
Additional question: Do I have to edit the file 'data/accounts/de_AT/CMakeLists.txt' manually?
=>  Adding austrian account template 

gnucash/gnome-search/dialog-search.c, gnucash/gnome-utils/dialog-account.c, gnucash/gnome-utils/dialog-utils.c, gnucash/gnome-utils/dialog-utils.h, gnucash/gnome-utils/gnc-file.c, gnucash/gnome-utils/gnc-tree-view.c, gnucash/gnome/gnc-budget-view.c, gnucash/gnome/gnc-plugin-page-account-tree.c, gnucash/gnome/gnc-split-reg.c, gnucash/gtkbuilder/assistant-csv-account-import.glade, gnucash/gtkbuilder/dialog-customer.glade, gnucash/gtkbuilder/dialog-invoice.glade, gnucash/gtkbuilder/dialog-lot-viewer.glade, gnucash/gtkbuilder/dialog-order.glade, gnucash/gtkbuilder/dialog-search.glade, gnucash/gtkbuilder/dialog-tax-info.glade, gnucash/gtkbuilder/dialog-totd.glade, gnucash/gtkbuilder/dialog-vendor.glade, gnucash/gtkbuilder/gnc-plugin-page-budget.glade, gnucash/import-export/aqb/dialog-ab.glade, gnucash/import-export/csv-imp/csv-account-import.c, gnucash/register/ledger-core/split-register.c, gnucash/register/ledger-core/split-register.h, gnucash/ui/gnc-plugin-page-account-tree-ui.xml, libgnucash/engine/Scrub.c, libgnucash/engine/Scrub.h
I think they are all fairly straight forward which should be OK hopefully.
Not sure about the last two but it's the only way I could think off simply. Maybe the last one could get a list of split accounts, scan the open registers and then only try to refresh those registers or maybe the rollback should do it somehow.
For info, I can probably make changes up to Christmas.
=> Some more fixes

gnucash/import-export/customer-import/dialog-customer-import-gui.c, gnucash/import-export/customer-import/dialog-customer-import.c
[797029 Import Customer & Vendors: blank name and company in import data row crashes GnuCash](https://bugs.gnucash.org/show_bug.cgi?id=797029)
[797031 Import customer & Vendors: import can create customer and vendors without address data](
https://bugs.gnucash.org/show_bug.cgi?id=797031)
[797030 Import Customer & Vendors: several issues with the matching of data rows](https://bugs.gnucash.org/show_bug.cgi?id=797030)
=> Fixes for bugs 797029 7970331 797030 in Import Customers & Vendors

gnucash/gnome-utils/gnc-gnome-utils.c, gnucash/gnome-utils/gnome-utils.scm, gnucash/report/standard-reports/advanced-portfolio.scm, gnucash/report/standard-reports/category-barchart.scm, gnucash/report/standard-reports/general-ledger.scm, gnucash/report/standard-reports/test/test-standard-category-report.scm, gnucash/report/standard-reports/transaction.scm, libgnucash/app-utils/date-utilities.scm, libgnucash/app-utils/options.scm, libgnucash/app-utils/test/test-date-utilities.scm, libgnucash/scm/utilities.scm
Some quick bugfixes with associated tests, separate from ~the difficult PRs~ refactoring commits.
=> scheme bugfixes

data/accounts/CMakeLists.txt, data/accounts/fr_BE/CMakeLists.txt, data/accounts/fr_BE/acctchrt_brokerage.gnucash-xea, data/accounts/fr_BE/acctchrt_business.gnucash-xea, data/accounts/fr_BE/acctchrt_carloan.gnucash-xea, data/accounts/fr_BE/acctchrt_cdmoneymkt.gnucash-xea, data/accounts/fr_BE/acctchrt_childcare.gnucash-xea, data/accounts/fr_BE/acctchrt_common.gnucash-xea, data/accounts/fr_BE/acctchrt_currency.gnucash-xea, data/accounts/fr_BE/acctchrt_eduloan.gnucash-xea, data/accounts/fr_BE/acctchrt_fixedassets.gnucash-xea, data/accounts/fr_BE/acctchrt_homeloan.gnucash-xea, data/accounts/fr_BE/acctchrt_homeown.gnucash-xea, data/accounts/fr_BE/acctchrt_otherloan.gnucash-xea, data/accounts/fr_BE/acctchrt_renter.gnucash-xea, data/accounts/fr_BE/acctchrt_retiremt.gnucash-xea, data/accounts/fr_BE/acctchrt_spouseinc.gnucash-xea, data/accounts/fr_BE/acctchrt_spouseretire.gnucash-xea, data/accounts/fr_CA/acctchrt_basecommune.gnucash-xea, data/accounts/fr_CH/acctchrt_common.gnucash-xea, data/accounts/fr_CH/acctchrt_spouseinc.gnucash-xea, data/accounts/fr_FR/acctchrt_common.gnucash-xea, data/accounts/fr_FR/acctchrt_spouseretire.gnucash-xea
Hello,
This adds the accounts templates for fr_BE (French Belgium)
It's almost a copy of the fr_FR templates. There are still some localization to do (ie the name of some organizations or taxes, like URSSAF) but it should be a good base already
=> Add accounts templates for fr_BE

bindings/python/example_scripts/gncinvoice_jinja.py, bindings/python/example_scripts/str_methods.py
Work on python example scripts. Change str_methods.py and gnc_jinja.py from python 2 to python 3. Some improvements to gnc_jinja.py.
=> Pr python2to3 str methods gnc jinja

bindings/python/example_scripts/account_analysis.py, bindings/python/example_scripts/gnc_convenience.py, bindings/python/example_scripts/latex_invoices.py, bindings/python/example_scripts/new_book_with_opening_balances.py, bindings/python/example_scripts/priceDB_test.py, bindings/python/example_scripts/price_database_example.py, bindings/python/example_scripts/quotes_historic.py, bindings/python/example_scripts/rest-api/gnucash_rest.py, bindings/python/example_scripts/simple_book.py, bindings/python/example_scripts/simple_business_create.py, bindings/python/example_scripts/simple_invoice_insert.py, bindings/python/example_scripts/simple_session.py, bindings/python/example_scripts/simple_sqlite_create.py, bindings/python/example_scripts/simple_test.py
I ran the python 2to3 utility on all the example files. Shebang has been modified to reflect the step to python3.
=> Pr python2to3

bindings/python/example_scripts/rest-api/gnucash_simple.py
Some changes to Tom Lofts REST-API (which I first used, it's quite nice !). I see that there's a separate repository https://github.com/loftx/gnucash-rest. I don't know where the actual development takes place.
I can only receive my invoices using these modifications. Tom, could you please have a look at this ?
@loftx
=> Pr python2to3 rest api

gnucash/python/init.py, gnucash/python/pycons/console.py
suggested fix for bugtracker https://bugs.gnucash.org/show_bug.cgi?id=797200
=> Pr dont close gnucash on pycons close

po/he.po
Plus fix some bidi conversion when Latin and Hebrew chars appear both in the same sentence.
=> Update he.po to v3.7

po/hr.po
=> Update hr.po file with 3.7 pot-file

gnucash/report/reports/standard/budget.scm
=> [budget] show budget-notes in report as footnotes

po/he.po
Fixed some typos
Update to the latest .POT
=> Hebrew translation update v3.7

gnucash/gnome-utils/dialog-utils.c, gnucash/gnome-utils/dialog-utils.h, gnucash/gnome-utils/gnc-tree-model-account.c, gnucash/gnome-utils/window-main-summarybar.c, gnucash/gnome/gnc-budget-view.c, gnucash/report/business-reports/invoice.scm
Discussion from [1](https://github.com/christopherlam/gnucash/commit/5db0acb10ce2375ebdc9b7905e51f0918706722a#commitcomment-36199350) and [2](https://github.com/christopherlam/gnucash/commit/812912b9a124387f15bbafc83323ffa9a1830476#commitcomment-36200644) brought out in open.
And candidate fix for bug 797401.
=> invoice gets page-width, remove some memory leaks

gnucash/import-export/bi-import/dialog-bi-import-gui.c, gnucash/import-export/bi-import/dialog-bi-import.c, gnucash/import-export/bi-import/dialog-bi-import.h
Several bug fixes and improvements in Import Bills & Invoices.
* Bug [797024 Import Bills & Invoices: import matches csv data rows with too few separators, messing up the import data](https://bugs.gnucash.org/show_bug.cgi?id=797024)
* Take all header data for an invoice from the first data row of that invoice. Previously, the import function took the header data for posting from the last row, and all other header data from the first row of an invoice.
* Bug [796987 Import Bills & Invoices: fixing import items only works in special case](https://bugs.gnucash.org/show_bug.cgi?id=796987)
* Validate header fields only for the first data row of an invoice.
* An error in a data row will cause the full invoice to be ignored; previously only that row would be ignored.
* Bug [796986 Import Bills & …
=> Bugs and improvements Import Bills & Invoices

gnucash/report/html-barchart.scm, gnucash/report/html-linechart.scm, gnucash/report/html-piechart.scm, gnucash/report/html-scatter.scm
=> [html-pie/scatter/bar/linechart] defer to html-chart renderer

gnucash/gnome/gnc-budget-view.c
This PR creates fix for budget_totals when using books with feature unreversed-budgets.
It requires book with feature enabled.
It interprets the budget-data assuming internal budget-values are natural numbers. When feature is made mandatory (after data conversion) in master branch, the old unfeatured data handling may be removed.
[budget-featured.zip](https://github.com/Gnucash/gnucash/files/4154575/budget-featured.zip)
https://github.com/Gnucash/gnucash/commit/f59e3ca751ac149177925d7b94e1ffa21fedd5a7#commitcomment-37085580
https://github.com/Gnucash/gnucash/pull/503#issuecomment-581142658
=> [gnc-budget-viewer.c] fix budget totals for unreverse-budgets featured books

gnucash/import-export/import-backend.c, libgnucash/engine/Account.cpp, libgnucash/engine/kvp-frame.hpp, libgnucash/engine/test/gtest-import-map.cpp
This PR fixes bug [797587](https://bugs.gnucash.org/show_bug.cgi?id=797587)
=> Bug 797587  - Token handling for bayesian import matching is incorrect 

bindings/python/example_scripts/simple_book.py, bindings/python/example_scripts/simple_session.py, bindings/python/example_scripts/simple_test.py, bindings/python/gnucash_core.py, bindings/python/tests/test_split.py, bindings/python/tests/test_transaction.py
Two changes:
1. Make equality tests work for Split and Transaction. When calling things like transaction.GetSplitList(), you get new class instances of the Splits which will not compare correctly with existing instances. See unit tests for details. I went with a GUID compare--if you think it should be more than that, let me know.
2. Make Session into a context manager. This makes the API feel a little more pythonic, and helps people like me who forget to call end() or save(). Since this isn't a substantial change I didn't write any unit tests; I updated one of the example scripts as a demo.
Let me know what suggestions you have.
=> quality-of-life improvements for python bindings

libgnucash/engine/Account.cpp
These look like yak-shaving, but IMHO clarifies and simplifies them greatly. I believe these are well tested.
=> clean up some account.cpp funcs

libgnucash/app-utils/gnc-ui-util.c, libgnucash/engine/gnc-numeric.cpp
The function gnc_numeric_to_decimal() should return TRUE if num is 0 but currently does not.
=> 797318 - Amounts ending in zero displayed as fractions

gnucash/python/init.py, gnucash/python/pycons/console.py
I'd like to be able to access the variables of the calling context. That makes developing and debugging easier.
=> expose variables of calling context to shell

bindings/python/CMakeLists.txt, bindings/python/app_utils.py
I'd like to have wrapper methods that return instances
=> high level python wrappers for app-utils

gnucash/gnome/window-reconcile.c
Previous code was ugly - reused char *amount for all strings including non-amount statement-date, gratuitous balance reversals and immediate re-reversals. Refactor common code to render and colorise amount into widget. Verified matches current behaviour in both BANK and CREDITCARD accounts. Instead of reversing sign, render, and re-reversing sign, the rendering function will handle sign reversal using a local variable. I have a suspicion WidgetSetAmount can be upgraded to a common utility library.
=> [window-reconcile] refactor common actions into WidgetSetAmount

po/fi.po, po/glossary/CMakeLists.txt, po/glossary/fi.po
I was looking if GnuCash would fit my accounting needs, but found the Finnish translations in bad shape. This is not very complete, but thought I better make this pull request to make the effort visible to others.
I have not yet done any accounting using GnuCash and if I actually get to it I'm sure there will be more translations and corrections.
While incomplete, I think this is an improvement and good enough for merge.
=> L10N:fi: Update translations and add glossary

gnucash/python/init.py
Just a little bit of output reformatting and code explanation for the python shell. Taken from #655 (https://github.com/Gnucash/gnucash/pull/655/commits/e2707f13102a5495e53a6bf38b28eb4287abf9f5). #655 goes to master. This can go to maint.
=> improve output and explain code for python shell

gnucash/report/reports/standard/test/test-transaction.scm, gnucash/report/trep-engine.scm
add Filter option to make Transaction Filter case insensitive. Into maint or master?
=> [trep-engine] add option Filter/Transaction Filter is case insensitive

gnucash/gnome/dialog-payment.c
sorts documents in dialog-payment.c by date, then by document ID.
=> Bug 796932 - Invoices order when assigning payments

gnucash/register/register-gnome/combocell-gnome.c, gnucash/register/register-gnome/gnucash-date-picker.c, gnucash/register/register-gnome/gnucash-item-edit.c, gnucash/register/register-gnome/gnucash-item-list.c, gnucash/register/register-gnome/gnucash-item-list.h, po/POTFILES.in
@jralls I have added your changes to this PR along with a couple of other changes I had noticed.
Note, I also moved the gnc_item_list_select and the unblock_list_signals to outside of the if block.
=> Gnc item edit changes

gnucash/gnucash-cli.cpp, gnucash/gnucash-commands.cpp, gnucash/gnucash-commands.hpp, gnucash/report/report-core.scm
Lists available reports, show options modified in a specified report.
I think this is simple enough.
This mechanism would need to change if future reports are saved within datafile.
=> cli report upgrades

po/hr.po
Updated Croatian (hr) translation with "gnucash-4.0.pot" file from http://translationproject.org/domain/gnucash.html
=> Updated Croatian (hr) translation

po/glossary/it.po, po/it.po
Nuova traduzione italiana, per gnucash-4.0
=> L10N:it: 5551 messaggi tradotti.

bindings/python/example_scripts/CMakeLists.txt, bindings/python/example_scripts/export_account_totals.py
This example exports acount totals of all accounts into a CSV file.
This has been asked before: https://money.stackexchange.com/questions/111786/exporting-account-totals-in-gnucash
=> Add Python example export_account_totals.py

gnucash/gnome/gnc-plugin-page-register.c
Pros: shows all invoices associated with txn.
Cons: if txns has both invoice-payment splits (have lots) and overpayment (has no lot), and the APAR overpayment split is selected, it'll prompt user to select from the invoices.
Consider a payment which pays 2 invoices for $225 and $120, and also an overpayment of $10. It'll have 4 splits:
- AP $225
- AP $120
- AP $10
- Bank -$355
We'd expect AP splits for $225 and $120 to immediately open the associated invoice, and the bank -$355 to offer selection. This works. However AP $10 split->invoice will offer selection as well, which is not necessarily intuitive. It may be considered "overengineering" to prevent this.
=> Bug 787295 - Allow UI jump from Business accounts to their relevant invoice/bill/voucher

po/nb.po
Only a partial update, way too much to do in one batch! The po-file now has 2793 translations of 5573 strings, or 50.12 % of the strings are now translated! ;)
Perhaps a slight warning: A lot of strings are translated with the fuzzy solution, and many of them are really long way off. Some are so far off I wonder if users may run into problems due to this. I have no solutions though, it is only an observation from the (mis)translated strings.
=> L10N: nb: partial updated translation

gnucash/report/html-chart.scm, gnucash/report/html-utilities.scm, gnucash/report/reports/example/welcome-to-gnucash.scm, gnucash/report/reports/standard/new-owner-report.scm, gnucash/report/reports/standard/price-scatter.scm
html-chart copies from stylesheet title & text font styles into chartjs JSON property.
=> Bug 797893 - Unable to change font size in charts 

gnucash/gnome/gnc-plugin-page-register.c
Thanks in advance for reviewing.
=> Fix typo: the the -> the

po/it.po
=> L10N:<IT>: Updated Italian translation; 5528 translated messagges.

gnucash/import-export/import-main-matcher.c
Adding tooltips in a GtkTreeView is actually surprisingly straightforward, if one could use this word in the context of gtk.
The "description" field is often quite long for imported transactions. So users (and myself) may need to see the full content, but the screen has only finite width. Showing the full text as tooltip helps a lot.
=> Add tooltip in import matcher window for description and memo column.

gnucash/gnome-utils/dialog-account.c, gnucash/gnucash-fallback.css, gnucash/gtkbuilder/window-autoclear.glade
As the warning does not belong in the tests, I created a separate PR for the dialog improvement - mostly because code is still down.
=> Amend autoclear dialog - spin-off from PR #805

libgnucash/app-utils/c-interface.scm, libgnucash/app-utils/date-utilities.scm
Cleanup, rearranges strings. Need to confirm i18n still works well. @fellen
=> [date-utilities] Convert reldate list into srfi-9 records

gnucash/report/trep-engine.scm, libgnucash/app-utils/options.scm
=> Bug 798036 - Transaction Report should offer price source

gnucash/import-export/aqb/CMakeLists.txt, gnucash/import-export/aqb/dialog-ab.glade, gnucash/import-export/aqb/gnc-flicker-gui.c, gnucash/import-export/aqb/gnc-flicker-gui.h, gnucash/import-export/aqb/gnc-gwen-gui.c, gnucash/import-export/aqb/gschemas/CMakeLists.txt, gnucash/import-export/aqb/gschemas/org.gnucash.dialogs.flicker.gschema.xml.in
Partly fixes bug 667490.
It implements the display of flashing optical TAN challenges (aka
flicker) in the "Enter TAN" dialog box.
=> Bug 667490 - Support chipTAN optical "Flicker code"

bindings/guile/core-utils.scm
When a guile coder uses a variable but omits `use-modules`, this code will scan *all* available modules and offer the appropriate module name. As test, modify a .scm file (eg options.scm or report-core.scm) and add a reference to `gnc-build-url`.
Before: Unbound variable: gnc-build-url
After: Unbound variable: gnc-build-url. Did you forget (use-module (sw_gnc_html))?
Mergeable after 4.3 is released.
=> [4.4] Use custom unbound-variable exception printer

libgnucash/app-utils/CMakeLists.txt
I think this works?
business-prefs needs options and business-options
business-options needs options
options needs date-utilities
=> [app-utils] fix dependency chain

gnucash/gnome/assistant-hierarchy.c
The commit of this mr fixes https://bugs.gnucash.org/show_bug.cgi?id=798070
=> Bug 798070 - Opening balance does not update when creating account from Account Hierarchy

data/accounts/da/acctchrt_common.gnucash-xea
As per the discussion in https://github.com/Gnucash/gnucash/pull/873#pullrequestreview-567912602
=> Also make underholdning and afstemning placeholders

bindings/guile/test/CMakeLists.txt, common/test-core/CMakeLists.txt, gnucash/gnome/CMakeLists.txt, gnucash/import-export/qif-imp/CMakeLists.txt, gnucash/report/CMakeLists.txt, gnucash/report/stylesheets/CMakeLists.txt, gnucash/report/test/CMakeLists.txt, libgnucash/app-utils/CMakeLists.txt, libgnucash/tax/CMakeLists.txt
Remove deprecated scheme modules in 5.x -- continuation of #855
=> Remove scheme deprecated module

gnucash/gnome-utils/gnc-main-window.c
@jralls  I think this covers the destroying of main windows with no plugin pages. I have tested this on my Linux VM and also Windows10 by trying various combinations of windows with pages, closing pages and quitting, having all empty windows and quitting and nothing untoward showed up.
Does this look OK to you?
=> Follow up to Bug 798098 fix

po/de.po
I'd be glad if this could be merged :)
=> Fix orthographic errors in German translation

gnucash/gnome/dialog-sx-editor.c
This branch aims to enable GtkWidget sensitivities if and only if the SX is enabled.
Upcoming:
=> [dialog-sx-editor]: Enable SX toggles if enabled.

.gitignore, libgnucash/engine/gnc-pricedb.c
plug memory leak. use `g_list_find`.
=> gnc-pricedb: plug memory leak

bindings/guile/test/test-engine-extras.scm, gnucash/report/report-utilities.scm, gnucash/report/reports/CMakeLists.txt, gnucash/report/reports/standard/ifrs-cost-basis.scm, gnucash/report/reports/standard/test/CMakeLists.txt, gnucash/report/reports/standard/test/test-ifrs-cost-basis.scm, gnucash/report/reports/standard/test/test-register.scm
offshoot from #818 -- average-cost-base calculator report commits only.
=> average-cost-base report

gnucash/gnome-utils/gnc-main-window.c, gnucash/gschemas/org.gnucash.gschema.xml.in, gnucash/gtkbuilder/dialog-preferences.glade
adds new preference. works well.
=> preference setting to open new tabs adjacent to currently active tab

data/accounts/de_DE/acctchrt_skr49.gnucash-xea
I noticed a couple of mistakes in the file, that are now fixed.
=> fix skr49 accounts (de)

data/accounts/zh_TW/CMakeLists.txt, data/accounts/zh_TW/acctchrt_brokerage.gnucash-xea, data/accounts/zh_TW/acctchrt_business.gnucash-xea, data/accounts/zh_TW/acctchrt_carloan.gnucash-xea, data/accounts/zh_TW/acctchrt_cdmoneymkt.gnucash-xea, data/accounts/zh_TW/acctchrt_checkbook.gnucash-xea, data/accounts/zh_TW/acctchrt_childcare.gnucash-xea, data/accounts/zh_TW/acctchrt_common.gnucash-xea, data/accounts/zh_TW/acctchrt_eduloan.gnucash-xea, data/accounts/zh_TW/acctchrt_fixedassets.gnucash-xea, data/accounts/zh_TW/acctchrt_homeloan.gnucash-xea, data/accounts/zh_TW/acctchrt_homeown.gnucash-xea, data/accounts/zh_TW/acctchrt_otherloan.gnucash-xea, data/accounts/zh_TW/acctchrt_renter.gnucash-xea, data/accounts/zh_TW/acctchrt_retiremt.gnucash-xea, data/accounts/zh_TW/acctchrt_spouseinc.gnucash-xea, data/accounts/zh_TW/acctchrt_spouseretire.gnucash-xea, data/accounts/zh_TW/acctchrt_vehicle.gnucash-xea
Translate account hierarchy examples for zh_TW and teak them suitable for normal use case in zh_TW.
=> add account examples for zh_TW.

gnucash/gnome-utils/gnc-file.c, gnucash/gnome-utils/gnc-plugin-page.c, gnucash/gnome-utils/gnc-plugin.c, gnucash/gnome/business-gnome-utils.c, gnucash/gnome/gnc-budget-view.c, gnucash/gnome/gnc-plugin-page-owner-tree.c, libgnucash/engine/Account.cpp, libgnucash/engine/Scrub.c, libgnucash/engine/Split.c, libgnucash/engine/Transaction.c, libgnucash/engine/gnc-budget.c, libgnucash/engine/gnc-commodity.c, libgnucash/engine/gnc-lot.c, libgnucash/engine/gncInvoice.c, libgnucash/engine/gncJob.c, libgnucash/engine/qof-backend.cpp
~instead of `qof_print_date` string which must be freed.~
=> various memory leaks plugged

gnucash/gnome/dialog-customer.c, gnucash/gnome/dialog-employee.c, gnucash/gnome/dialog-vendor.c, gnucash/import-export/customer-import/dialog-customer-import.c
This will be more efficient.
I find a small problem, in Employee Report, the name appears twice.
=> remove setting address while a new customer/vendor/employee or import a new customer

libgnucash/engine/Account.h
As discussed at
https://lists.gnucash.org/pipermail/gnucash-user/2021-June/096893.html
=> Explain out what AsOfDate means in the doc

gnucash/register/register-gnome/combocell-gnome.c, gnucash/register/register-gnome/gnucash-item-edit.c
@jralls 
These are my changes for bug798162, the last commit is a small refactor to the gnc_combo_cell_modify_verify. I think it does make it flow better, not sure what else can be achieved.
Still think it fixes the problem with further testing but as always can you give it a spin to confirm.
=> Bug798162 -  Type Ahead Initialization Problem

gnucash/import-export/import-main-matcher.c, gnucash/register/ledger-core/gncEntryLedgerModel.c, gnucash/register/ledger-core/split-register-model.c, libgnucash/backend/xml/gnc-xml-backend.cpp
=> More memory leaks

gnucash/report/reports/standard/equity-statement.scm, gnucash/report/reports/standard/test/test-equity-statement.scm
Fix Bug 798211 <https://bugs.gnucash.org/show_bug.cgi?id=798211>
=> Bug 798211 - Equity statement double calculates unrealized gain

libgnucash/engine/gnc-pricedb.c
There's no point setting old_price when doing bulk updates because it's not used.
=> [gnc-pricedb] Don't lookup old prices when doing bulk updates

gnucash/import-export/aqb/assistant-ab-initial.glade
Thanks in advance for reviewing.
=> Fix minor typo: choosen -> chosen

bindings/python/example_scripts/Invoice.tex.tmpl, bindings/python/example_scripts/Invoice_2.tex.tmpl, bindings/python/example_scripts/latex_invoices.py
Various fixes to get latex_invoice.py working again
=> Fix latex_invoice.py

libgnucash/engine/Account.cpp
Continuation of #1086, thanks to valgrind
=> Account.cpp optimisations

libgnucash/engine/Split.c
`qof_book_use_trading_accounts` is called a lot especially from register code which calls `xaccSplitGetOtherSplit`. Cache its value from kvp. Also, more leaks.
=> Maint speedup and leaks

libgnucash/engine/Account.cpp, libgnucash/engine/AccountP.h, libgnucash/engine/Split.c, libgnucash/engine/SplitP.h, libgnucash/engine/Transaction.c, libgnucash/engine/TransactionP.h, libgnucash/engine/gnc-commodity.c, libgnucash/engine/gnc-lot.c, libgnucash/engine/gncInvoice.c
cache GValue string into commodity struct
=> Maint cache gvalue string

gnucash/import-export/import-main-matcher.c
=> Maint Generic Import Transaction Matcher - fix crashes

gnucash/gnome/dialog-customer.c
=> add a shipping contact name column for FindCustomerDialog

gnucash/gnome/assistant-stock-split.c, gnucash/gnome/gnc-plugin-page-register.c, libgnucash/engine/Transaction.c, libgnucash/engine/TransactionP.h, libgnucash/engine/mocks/gmock-Transaction.h
post string freeze
* When reversing a transaction which is already reversed, offer a jump to the reversal transaction.
=> General progress

gnucash/gnome-utils/gnc-main-window.c, gnucash/gnome/dialog-imap-editor.c, gnucash/gnome/dialog-invoice.c, gnucash/gnome/dialog-payment.c, gnucash/gnome/dialog-price-edit-db.c, gnucash/gnome/dialog-sx-editor.c, gnucash/gnome/dialog-sx-editor2.c, gnucash/gnome/gnc-plugin-page-account-tree.c, gnucash/gnome/gnc-plugin-page-sx-list.c, gnucash/register/ledger-core/gnc-ledger-display.c, libgnucash/core-utils/gnc-glib-utils.c, libgnucash/core-utils/gnc-glib-utils.h, libgnucash/core-utils/test/test-gnc-glib-utils.c, libgnucash/engine/Recurrence.c, libgnucash/engine/gncIDSearch.c
for review candidate g_list_length comparator function names... `gnc_list_length_gt` `gnc_list_length_lt` `gnc_list_length_eq`?
=> gnc_list_length comparator functions

gnucash/gnome/dialog-sx-since-last-run.c
mainly removing calls to `g_list_length` where appropriate.
=> Maint progress2

gnucash/gnome/window-reconcile.c
=> Addendum to #1227 fd3ec14f6 optionally raises descendants' editlevel

bindings/python/example_scripts/qof.py
Example file for qof-queries in python bindings
=> python qof examples

gnucash/gtkbuilder/dialog-preferences.glade
on preference "Enable update match action" tooltip text.
=> Preferences, Import: UPDATE AND RECONCILE should be UPDATE AND CLEAR

gnucash/gnome/gnc-budget-view.c
~1. remove dead code~
2. fix a crasher in budget view
=> various code progress

gnucash/gnome/gnc-budget-view.c, gnucash/gnome/gnc-plugin-budget.c, gnucash/gnome/gnc-plugin-page-budget.c
Disable some budget features if book is readonly
=> Budgets are sensitive to readonly status

gnucash/gnome/assistant-stock-transaction.cpp, gnucash/gtkbuilder/assistant-stock-transaction.glade
Further progress. Can show non-critical warnings as well as errors.
=> Add warning if adding stock transaction dated before the latest existing stock account transaction

gnucash/gnome/assistant-stock-transaction.cpp
- guards against unassigned std::optional
- ~skip check txn_date < last txn date if the stock acct is empty~
- ~UX improvement, don't reset txn_types unnecessarily~
=> stock assistant

gnucash/gnome-utils/gnc-ui.h, gnucash/gnome/dialog-sx-since-last-run.c, gnucash/gtkbuilder/dialog-sx.glade
=> Bug 771095, partially solved. Inserting a help button in the Since-Last-Run dialog.

gnucash/gnome-utils/gnc-gtk-utils.c, gnucash/gnome-utils/gnc-gtk-utils.h, gnucash/gnome-utils/gnc-main-window.c, gnucash/gnucash-core-app.cpp, gnucash/gnucash-core-app.hpp, gnucash/gnucash.css, libgnucash/core-utils/gnc-filepath-utils.cpp, libgnucash/core-utils/gnc-filepath-utils.h
Show paths in About box. Paths are clickable. Any other paths to be included?
=> Show paths

gnucash/gnome/gnc-plugin-page-account-tree.c
Premise: if, upon startup, the page is on the account register, and selection is on a leaf account, the "Edit > Renumber subaccounts" menuitem is incorrectly selectable. This bug exists because the sensitivites are being set in two different functions.
This commit tidies it up, centralizing the setting of sensitivities.
=> Account tree: set menu sensitivities in only 1 function

data/accounts/fr_CH/CMakeLists.txt, data/accounts/fr_CH/acctchrt_pme-19.gnucash-xea
Adding Swiss SMB (PME) account template, based on Sterchi
Original pull request : https://github.com/Gnucash/gnucash/pull/1400
I've created a new pull request with all the corrections and the two commits that are needed
=> Create Swiss SMB (PME) account Template 2019 (translated and adapted from chkmu)

bindings/python/example_scripts/rest-api/gnucash_rest.py, bindings/python/example_scripts/simple_invoice_insert.py, doc/examples/taxreport.gnucash, gnucash/gnome-utils/gnc-gtk-utils.c, gnucash/gnome-utils/gnc-main-window.c, gnucash/gnome-utils/gnc-tree-view-split-reg.c, gnucash/gnome/gnc-plugin-page-register2.c, gnucash/gtkbuilder/dialog-preferences.glade, gnucash/import-export/aqb/gnc-ab-utils.c, gnucash/register/register-core/datecell.h, gnucash/report/report-core.scm, gnucash/report/reports/locale-specific/us/taxtxf.scm, libgnucash/backend/xml/gnc-account-xml-v2.cpp, libgnucash/core-utils/gnc-filepath-utils.cpp, libgnucash/doc/constraints.txt, libgnucash/doc/engine.txt, libgnucash/engine/qofbook.h, libgnucash/engine/test/test-numeric.cpp
=> Fix various typos

gnucash/gnome/gnc-budget-view.c
Draft commits for master. Would not merge until 4.x is EOL, to ensure code base does not diverge too much.
=> Fix GncBudget Sign Reversal

gnucash/report/reports/standard/investment-lots.scm, libgnucash/engine/gnc-optiondb.cpp
A few for @mcbridebt - some options are dependent on others. They should be modified to improve UX. Does this report have any other dependent options? Also some cleanup.
=> cleanup investment-lots

gnucash/report/reports/standard/balsheet-pnl.scm
Generate a separate exchange-fn for each date. Cache its result.
=> [balsheet-pnl] Generate a separate exchange-fn for each date. Cache its result.

gnucash/register/ledger-core/test/utest-split-register-copy-ops.c, libgnucash/backend/dbi/test/test-backend-dbi-basic.cpp
- test_gnc_txn_to_float_txn_cut_semantics
- test_dbi_business_store_and_reload
=> Fix some typos so that the correct tests are run

gnucash/gnome/window-reconcile.c
with g_action_map_lookup_action
=> Replace deprecated (since 2.38) g_simple_action_group_lookup

CMakeLists.txt
Good for declaring variables at point of use
=> Allow C declarations after statements

data/accounts/de_DE/acctchrt_skr49.gnucash-xea
With this merge request [bug 798732](https://bugs.gnucash.org/show_bug.cgi?id=798732) will be fixed.
=> Bug 798732: Type of balance carry forward accounts for german skr49 account template fixed

gnucash/import-export/csv-imp/assistant-csv-trans-import.cpp, gnucash/import-export/csv-imp/gnc-imp-props-tx.hpp
Attempts to fix MacOS build error.
=> MacOS - try with non-const key for map

libgnucash/app-utils/gnc-gsettings.cpp
This alternative implementation gets rid of caching the GSettings objects except for keeping track of signal handlers.
Will slow down GSettings interactions, but in general they are already that fast, there is no noticeable side effect.
=> Bug 798749 - Fails to read gsettings on startup

gnucash/gnome-utils/dialog-account.c, gnucash/gnome-utils/gnc-dense-cal-store.c, gnucash/gnome-utils/gnc-dense-cal-store.h, gnucash/gnome/dialog-customer.c, gnucash/gnome/dialog-employee.c, gnucash/gnome/dialog-job.c, gnucash/gnome/dialog-sx-editor.c, gnucash/gnome/dialog-sx-from-trans.c, gnucash/gnome/dialog-vendor.c, gnucash/gtkbuilder/dialog-customer.glade, gnucash/gtkbuilder/dialog-employee.glade, gnucash/gtkbuilder/dialog-vendor.glade, gnucash/import-export/import-backend.cpp, gnucash/report/eguile-utilities.scm
A small collection of tidying up. Primarily: gtk_entry_get_text instead of gtk_editable_get_chars.
=> minor changes

libgnucash/engine/Account.cpp, libgnucash/engine/Split.c, libgnucash/engine/gnc-commodity.c, libgnucash/engine/gnc-lot.c, libgnucash/engine/gncInvoice.c, libgnucash/engine/qofinstance.cpp, libgnucash/engine/test/utest-Account.cpp, po/hu.po
=> [engine] don't use is_unset to cache char*

CMakeLists.txt, gnucash/gnome-utils/gnc-main-window.cpp
... and always check glib and gtk versions.
=> Replace deprecated gdk screen width and height

gnucash/import-export/aqb/gnc-plugin-aqbanking.c
.. does nothing
Action activate needs to change the state
Note that there is another bug (also present in maint) where the menu entry does nothing the first time it is clicked
=> Fix regression: Actions > Online Actions > Show log window

bindings/guile/gnc-optiondb.i, gnucash/gnome-utils/dialog-options.cpp, libgnucash/engine/gnc-option.hpp
Fixes [Bug 798778](https://bugs.gnucash.org/show_bug.cgi?id=798778).
I think.
=> GnuCash quits abruptly when attempting to edit options

libgnucash/app-utils/gnc-quotes.cpp, libgnucash/app-utils/test/gtest-gnc-quotes.cpp, libgnucash/backend/sql/gnc-sql-column-table-entry.cpp, libgnucash/backend/xml/sixtp-dom-generators.cpp, libgnucash/core-utils/test/gtest-path-utilities.cpp, libgnucash/engine/kvp-value.cpp, libgnucash/engine/kvp-value.hpp, libgnucash/engine/test/gtest-qofquerycore.cpp, libgnucash/engine/test/test-account-object.cpp, libgnucash/engine/test/test-guid.cpp, libgnucash/engine/test/test-kvp-value.cpp, libgnucash/engine/test/test-lots.cpp, libgnucash/engine/test/test-query.cpp
These are some pretty straightforward fixes.
Some more complicated fixes follow later in separate PRs, to facilitate easy review.
=> Fix memory leaks from test suite
